# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IPlugInDialog
                                 A QGIS plugin
 Plugin to perform interpolation task for onfarm research module
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lucas Johannsen
        email                : lucas.johannsen@fh-kiel.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *i
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtWidgets import QProgressDialog, QMessageBox, QPushButton, QDialogButtonBox
from qgis.core import (QgsMapLayerProxyModel, QgsFieldProxyModel, QgsProject, QgsMessageLog, Qgis,
                      QgsRasterLayer, QgsRectangle, QgsCoordinateReferenceSystem)

from .variogram_dialog import VariogramDialog
from .config import InterpolationConfig, InterpolationMethod
from .exceptions import (
    InterpolationError,
    DataValidationError,
    GeometryError,
    CoordinateSystemError,
    InterpolationCalculationError
)

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Optimierung.ui'))


class IPlugInDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface, parent=None):
        """Constructor."""
        super(IPlugInDialog, self).__init__(parent)
        self.iface = iface
        self.plugin = None  # Will be set by the plugin instance
        self.plugin_dir = None
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Initialize UI components
        self.setup_ui_components()
        
        # Connect signals
        self.connect_signals()
        
        # Load saved settings
        self.load_settings()
        
        # Update UI state after initialization
        self.update_ui_state()
# UI COMPONENTEN WERDEN HIER AUFGESETZT 
    def setup_ui_components(self):
        """Setup UI components after loading."""
        # Set up map layer combo box to show only point layers
        self.mMapLayerComboBox.setFilters(QgsMapLayerProxyModel.PointLayer)
        
        # Set up target layer combo box to show only point layers
        self.mMapLayerComboBox_target_layer.setFilters(QgsMapLayerProxyModel.PointLayer)
        
        # Set up covariate point layer combo box to show only point layers
        self.mMapLayerComboBox_covariate_point.setFilters(QgsMapLayerProxyModel.PointLayer)
        
        # Set up boundary layer combo box to show only polygon layers
        self.mMapLayerComboBox_boundary.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        
        # Set field types to numeric
        self.mFieldComboBox.setFilters(QgsFieldProxyModel.Numeric)
        self.mFieldComboBox_covariate.setFilters(QgsFieldProxyModel.Numeric)
        
        # Set default values from InterpolationConfig
        self.doubleSpinBox_cellsize.setValue(InterpolationConfig.DEFAULT_CELL_SIZE)
        self.doubleSpinBox_cellsize.setRange(
            InterpolationConfig.DEFAULT_CELL_SIZE_MIN, 
            InterpolationConfig.DEFAULT_CELL_SIZE_MAX
        )
        self.doubleSpinBox_cellsize.setDecimals(2)
        
        self.doubleSpinBox_sill.setValue(InterpolationConfig.DEFAULT_SILL)
        self.doubleSpinBox_sill.setRange(
            InterpolationConfig.DEFAULT_SILL_MIN, 
            InterpolationConfig.DEFAULT_SILL_MAX
        )
        self.doubleSpinBox_sill.setDecimals(3)
        
        self.doubleSpinBox_range.setValue(InterpolationConfig.DEFAULT_RANGE)
        self.doubleSpinBox_range.setRange(
            InterpolationConfig.DEFAULT_RANGE_MIN, 
            InterpolationConfig.DEFAULT_RANGE_MAX
        )
        self.doubleSpinBox_range.setDecimals(2)
        
        self.doubleSpinBox_nugget.setValue(InterpolationConfig.DEFAULT_NUGGET)
        self.doubleSpinBox_nugget.setRange(
            InterpolationConfig.DEFAULT_NUGGET_MIN, 
            InterpolationConfig.DEFAULT_NUGGET_MAX
        )
        self.doubleSpinBox_nugget.setDecimals(3)
        
        # Setup lags spinbox (Raster tab)
        self.spinBox_lags.setValue(InterpolationConfig.DEFAULT_NLAGS)
        self.spinBox_lags.setRange(
            InterpolationConfig.MIN_LAGS, 
            InterpolationConfig.MAX_LAGS
        )
        
        # Setup point interpolation tab parameters
        if hasattr(self, 'doubleSpinBox_sill_point'):
            self.doubleSpinBox_sill_point.setValue(InterpolationConfig.DEFAULT_SILL)
            self.doubleSpinBox_sill_point.setRange(
                InterpolationConfig.DEFAULT_SILL_MIN, 
                InterpolationConfig.DEFAULT_SILL_MAX
            )
            self.doubleSpinBox_sill_point.setDecimals(3)
        
        if hasattr(self, 'doubleSpinBox_range_point'):
            self.doubleSpinBox_range_point.setValue(InterpolationConfig.DEFAULT_RANGE)
            self.doubleSpinBox_range_point.setRange(
                InterpolationConfig.DEFAULT_RANGE_MIN, 
                InterpolationConfig.DEFAULT_RANGE_MAX
            )
            self.doubleSpinBox_range_point.setDecimals(2)
        
        if hasattr(self, 'doubleSpinBox_nugget_point'):
            self.doubleSpinBox_nugget_point.setValue(InterpolationConfig.DEFAULT_NUGGET)
            self.doubleSpinBox_nugget_point.setRange(
                InterpolationConfig.DEFAULT_NUGGET_MIN, 
                InterpolationConfig.DEFAULT_NUGGET_MAX
            )
            self.doubleSpinBox_nugget_point.setDecimals(3)
        
        if hasattr(self, 'spinBox_lags_point'):
            self.spinBox_lags_point.setValue(InterpolationConfig.DEFAULT_NLAGS)
            self.spinBox_lags_point.setRange(
                InterpolationConfig.MIN_LAGS, 
                InterpolationConfig.MAX_LAGS
            )
        
        # Initialize interpolation method combo boxes with available methods
        if hasattr(self, 'comboBox_method'):
            self.comboBox_method.clear()
            self.comboBox_method.addItems(InterpolationMethod.get_all_methods())
            self.comboBox_method.setCurrentIndex(0)  # Default: Ordinary Kriging
        
        if hasattr(self, 'comboBox_method_point'):
            self.comboBox_method_point.clear()
            self.comboBox_method_point.addItems(InterpolationMethod.get_all_methods())
            self.comboBox_method_point.setCurrentIndex(0)  # Default: Ordinary Kriging
        
        # Initialize stacked widgets to show Ordinary Kriging parameters (index 0)
        if hasattr(self, 'stackedWidget_method_params'):
            self.stackedWidget_method_params.setCurrentIndex(0)
        
        if hasattr(self, 'stackedWidget_method_params_point'):
            self.stackedWidget_method_params_point.setCurrentIndex(0)
        
        # Load saved settings
        self.load_settings()
        
        # Hide progress bar initially
        if hasattr(self, 'progressBar'):
            self.progressBar.hide()

        # Add variogram analysis and interpolation buttons to kriging page using layout
        self.analyze_variogram_button = QPushButton("Variogram Analyse")
        self.analyze_variogram_button.setEnabled(False)
        self.interpolate_button = QPushButton("Interpolieren")
        # Use the layout from page_kriging (should be present after UI edit)
        layout = self.page_kriging.layout()
        if layout is not None:
            layout.addWidget(self.analyze_variogram_button)
            #layout.addWidget(self.interpolate_button)
        else:
            # Fallback: just parent to page_kriging if layout missing
            self.analyze_variogram_button.setParent(self.page_kriging)
            #self.interpolate_button.setParent(self.page_kriging)

        # Add variogram analysis button for point interpolation (page_kriging_2)
        self.analyze_variogram_button_points = QPushButton("Variogram Analyse")
        self.analyze_variogram_button_points.setEnabled(False)
        layout_points = self.page_kriging_2.layout() if hasattr(self, 'page_kriging_2') else None
        if layout_points is not None:
            layout_points.addWidget(self.analyze_variogram_button_points)
        elif hasattr(self, 'page_kriging_2'):
            self.analyze_variogram_button_points.setParent(self.page_kriging_2)

        # Create labels for optimized variogram parameters (Raster tab)
        self.create_optimized_parameter_labels_raster()
        
        # Initialize variogram_info storage for both tabs
        self.variogram_info_raster = None
        self.variogram_info_point = None
        
        # Create labels for optimized variogram parameters (Point tab)
        self.create_optimized_parameter_labels_point()
        
        # Initialize range parameter visibility based on LOADED variogram model
        # This must happen AFTER creating optimized parameter labels
        if hasattr(self, 'comboBox_variogram'):
            current_model = self.comboBox_variogram.currentText()
            self.on_variogram_model_changed_raster(current_model)
        
        if hasattr(self, 'comboBox_variogram_point'):
            current_model_point = self.comboBox_variogram_point.currentText()
            self.on_variogram_model_changed_point(current_model_point)

        # --- Optimierung: Hinzufügen-Button anbinden ---
        if hasattr(self, 'pushButton'):
            self.pushButton.clicked.connect(self.raster_interpolation_layer_add)
        if hasattr(self, 'pushButton_5'):
            self.pushButton_5.clicked.connect(self.point_interpolation_layer_add)
        if hasattr(self, 'pushButton_4'):
            self.pushButton_4.clicked.connect(self.target_layer_add)
        if hasattr(self, 'pushButton_2'):
            self.pushButton_2.clicked.connect(self.boundary_layer_add)

    def create_optimized_parameter_labels_raster(self):
        """Create labels to display optimized variogram parameters for raster tab."""
        parent_widget = self.page_kriging_3 if hasattr(self, 'page_kriging_3') else self
        
        # Create a group box for optimized parameters
        self.optimized_params_group_raster = QtWidgets.QGroupBox("Optimierte Parameter:", parent_widget)
        self.optimized_params_group_raster.setVisible(False)  # Hidden initially
        self.optimized_params_group_raster.setFixedHeight(110)  # Feste Höhe
        self.optimized_params_group_raster.setFixedWidth(250)  # Feste Breite
        
        # Create layout for the group box
        params_layout = QtWidgets.QFormLayout()
        
        # Create labels for optimized values
        self.label_optimized_nugget_raster = QtWidgets.QLabel("—")
        self.label_optimized_range_raster = QtWidgets.QLabel("—")
        self.label_optimized_sill_raster = QtWidgets.QLabel("—")
        
        # Create label for range row (to be able to hide it)
        self.label_optimized_range_label_raster = QtWidgets.QLabel("Range:")
        
        # Style labels
        for label in [self.label_optimized_nugget_raster, self.label_optimized_range_raster, self.label_optimized_sill_raster]:
            label.setStyleSheet("QLabel { color: #2E7D32; font-weight: bold; }")
        
        # Add to layout
        params_layout.addRow("Sill:", self.label_optimized_sill_raster)
        params_layout.addRow(self.label_optimized_range_label_raster, self.label_optimized_range_raster)
        params_layout.addRow("Nugget:", self.label_optimized_nugget_raster)
        
        self.optimized_params_group_raster.setLayout(params_layout)
        
        # Add to page layout
        layout = parent_widget.layout()
        if layout:
            layout.addWidget(self.optimized_params_group_raster)

    def create_optimized_parameter_labels_point(self):
        """Create labels to display optimized variogram parameters for point tab."""
        parent_widget = self.page_kriging_4 if hasattr(self, 'page_kriging_4') else self
        
        # Create a group box for optimized parameters
        self.optimized_params_group_point = QtWidgets.QGroupBox("Optimierte Parameter:", parent_widget)
        self.optimized_params_group_point.setVisible(False)  # Hidden initially
        self.optimized_params_group_point.setFixedHeight(110)  # Feste Höhe
        self.optimized_params_group_point.setFixedWidth(250)  # Feste Breite        
        # Create layout for the group box
        params_layout = QtWidgets.QFormLayout()
        
        # Create labels for optimized values
        self.label_optimized_nugget_point = QtWidgets.QLabel("—")
        self.label_optimized_range_point = QtWidgets.QLabel("—")
        self.label_optimized_sill_point = QtWidgets.QLabel("—")
        
        # Create label for range row (to be able to hide it)
        self.label_optimized_range_label_point = QtWidgets.QLabel("Range:")
        
        # Style labels
        for label in [self.label_optimized_nugget_point, self.label_optimized_range_point, self.label_optimized_sill_point]:
            label.setStyleSheet("QLabel { color: #2E7D32; font-weight: bold; }")
        
        # Add to layout
        params_layout.addRow("Sill:", self.label_optimized_sill_point)
        params_layout.addRow(self.label_optimized_range_label_point, self.label_optimized_range_point)
        params_layout.addRow("Nugget:", self.label_optimized_nugget_point)
        
        self.optimized_params_group_point.setLayout(params_layout)
        
        # Add to page layout
        layout = parent_widget.layout()
        if layout:
            layout.addWidget(self.optimized_params_group_point)

# VERBINDUNG DER SIGNAL
    def _validate_and_add_layer(self, layer_combo, field_combo=None, layer_type_name="Layer"):
        """
        Generische Helper-Funktion für Layer-Validierung mit UTM-Konvertierung.
        
        Args:
            layer_combo: QgsMapLayerComboBox - Die ComboBox mit dem zu validierenden Layer
            field_combo: QgsFieldComboBox (optional) - Die ComboBox mit dem Feld
            layer_type_name: str - Name des Layer-Typs für Fehlermeldungen
            
        Returns:
            bool: True wenn erfolgreich, False bei Fehler
        """
        try:
            # Layer holen
            layer = layer_combo.currentLayer() if hasattr(layer_combo, 'currentLayer') else None
            if layer is None:
                QMessageBox.warning(self, "Eingabe fehlt", "Bitte wählen Sie einen Layer aus.")
                return False
            
            # Optional: Feld holen
            field = None
            if field_combo is not None:
                field = field_combo.currentField() if hasattr(field_combo, 'currentField') else None
                if not field:
                    QMessageBox.warning(self, "Eingabe fehlt", "Bitte wählen Sie einen Layer und ein Attribut aus.")
                    return False
            
            layer_name = layer.name()
            
            # Validierung (nutzt Plugin-Backend, konvertiert ggf. zu UTM und legt neuen Layer an)
            if field is not None:
                self.plugin.validate_input_data(layer, field)
            else:
                self.plugin.validate_input_data(layer)
            
            # Nach möglicher UTM-Konvertierung gezielt nach neuem Layer suchen
            utm_layer = None
            project = QgsProject.instance()
            for lyr in project.mapLayers().values():
                if lyr.name().startswith("UTM_") and layer_name in lyr.name():
                    utm_layer = lyr
                    break
            
            # ComboBox auf UTM-Layer setzen, falls konvertiert wurde
            if utm_layer:
                layer_combo.setLayer(utm_layer)
            
            # Erfolgsmeldung
            if field is not None:
                self.iface.messageBar().pushSuccess(
                    "I-PlugIn - Validierung",
                    f"Layer '{layer.name()}', Feld '{field}' ist gültig und kann verwendet werden."
                )
            else:
                self.iface.messageBar().pushSuccess(
                    "I-PlugIn - Validierung",
                    f"Layer '{layer.name()}' ist gültig und kann verwendet werden."
                )
            
            return True
            
        except DataValidationError as e:
            self.iface.messageBar().pushWarning("I-PlugIn - Datenvalidierung", str(e), duration=5)
            return False
        except GeometryError as e:
            self.iface.messageBar().pushWarning("I-PlugIn - Geometrie", str(e), duration=5)
            return False
        except CoordinateSystemError as e:
            self.iface.messageBar().pushWarning("I-PlugIn - Koordinatensystem", str(e), duration=5)
            return False
        except InterpolationError as e:
            self.iface.messageBar().pushCritical("I-PlugIn - Fehler", str(e), duration=5)
            return False
        except Exception as e:
            self.iface.messageBar().pushCritical("I-PlugIn - Unerwarteter Fehler", str(e), duration=5)
            return False
    
    def boundary_layer_add(self):
        """Validiert den Boundary-Layer im Optimierungs-Tab."""
        self._validate_and_add_layer(
            layer_combo=self.mMapLayerComboBox_boundary,
            field_combo=None,
            layer_type_name="Boundary"
        )
    def target_layer_add(self):
        """Validiert den Ziel-Layer für Punkt-Interpolation."""
        self._validate_and_add_layer(
            layer_combo=self.mMapLayerComboBox_target_layer,
            field_combo=None,
            layer_type_name="Ziel"
        )

    def raster_interpolation_layer_add(self):
        """Validiert den Input-Layer und Feld für Raster-Interpolation."""
        self._validate_and_add_layer(
            layer_combo=self.mMapLayerComboBox,
            field_combo=self.mFieldComboBox,
            layer_type_name="Raster-Input"
        )

    def point_interpolation_layer_add(self):
        """Validiert den Kovariaten-Layer und Feld für Punkt-Interpolation."""
        self._validate_and_add_layer(
            layer_combo=self.mMapLayerComboBox_covariate_point,
            field_combo=self.mFieldComboBox_covariate,
            layer_type_name="Kovariaten"
        )

    def show_variogram_analysis_points(self):
        """Show variogram analysis dialog with current parameters for point interpolation."""
        # Create progress dialog immediately
        progress = QProgressDialog(
            "Variogramm-Analyse läuft...",
            "Abbrechen",
            0,
            0,
            self
        )
        progress.setWindowTitle("I-PlugIn")
        progress.setWindowModality(Qt.WindowModal)
        progress.setMinimumDuration(0)  # Show immediately
        progress.setAutoClose(True)
        progress.setAutoReset(True)
        progress.setCancelButton(None)  # No cancel button for variogram analysis
        
        try:
            # Show progress dialog immediately
            progress.show()
            QCoreApplication.processEvents()  # Force UI update
            
            # Get current parameters for point interpolation
            params = self.get_point_interpolation_parameters()
            if not params:
                progress.close()
                return

            # Get input data for point interpolation
            covariate_layer = params.get('covariate_layer')
            covariate_field = params.get('covariate_field')
            boundary = None  # Optional: use a boundary if relevant for points

            # Prepare data (x, y, z from covariate layer)
            x, y, z = self.plugin.prepare_data(covariate_layer, covariate_field, boundary)
            if x is None or len(x) == 0:
                progress.close()
                QgsMessageLog.logMessage(
                    "No valid data points found for point variogram analysis",
                    "I-PlugIn",
                    Qgis.Warning
                )
                return

            # Analyze variogram (using point params)
            results = self.plugin.analyze_variogram(x, y, z, params)
            if not results:
                progress.close()
                return
                
            # Store variogram_info for later use
            self.variogram_info_point = results

            # Close progress dialog
            progress.close()

            # Update dialog with optimized parameters for points
            self.update_variogram_parameters({
                'nugget': results['parameters']['nugget'],
                'range': results['parameters']['range'],
                'sill': results['parameters']['sill'],
                'metrics': results['metrics']
            }, point_tab=True)

            # Show dialog
            dialog = VariogramDialog(self)
            dialog.display_results(results['plot_path'], results['metrics'])
            dialog.exec_()

        except InterpolationCalculationError as e:
            progress.close()
            QMessageBox.critical(self, "Variogramm-Analyse fehlgeschlagen", str(e))
        except DataValidationError as e:
            progress.close()
            QMessageBox.warning(self, "Datenvalidierung", str(e))
        except InterpolationError as e:
            progress.close()
            QMessageBox.critical(self, "Fehler", str(e))
        except Exception as e:
            progress.close()
            QgsMessageLog.logMessage(
                f"Unerwarteter Fehler bei Variogramm-Analyse: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )
            QMessageBox.critical(self, "Unerwarteter Fehler", f"Ein unerwarteter Fehler ist aufgetreten:\n\n{str(e)}")

    def connect_signals(self):
        """Connect signals to slots."""
        # Connect layer selection changes to field combo boxes
        self.mMapLayerComboBox.layerChanged.connect(self.on_layer_changed)
        self.mMapLayerComboBox.layerChanged.connect(self.sync_target_layer)
        self.mMapLayerComboBox_covariate_point.layerChanged.connect(self.on_covariate_layer_changed)

        # Connect interpolation method changes to parameter widget switching
        self.comboBox_method.currentTextChanged.connect(self.on_interpolation_method_changed_raster)
        if hasattr(self, 'comboBox_method_point'):
            self.comboBox_method_point.currentTextChanged.connect(self.on_interpolation_method_changed_point)
        
        # Connect interpolation buttons
        #self.interpolate_button.clicked.connect(self.accept)
        self.button_interpolate_points.clicked.connect(self.interpolate_points)
        self.button_interpolate_points_2.clicked.connect(self.accept)
        
        # Connect variogram analysis button
        self.analyze_variogram_button.clicked.connect(self.show_variogram_analysis)
        # Connect variogram analysis button for point interpolation
        self.analyze_variogram_button_points.clicked.connect(self.show_variogram_analysis_points)
        
        # Connect UI state updates for raster tab
        self.mMapLayerComboBox.layerChanged.connect(self.update_ui_state)
        self.mFieldComboBox.fieldChanged.connect(self.update_ui_state)
        self.comboBox_variogram.currentTextChanged.connect(self.update_ui_state)
        self.comboBox_variogram.currentTextChanged.connect(self.reset_variogram_parameters_raster)
        self.comboBox_variogram.currentTextChanged.connect(self.on_variogram_model_changed_raster)
        self.spinBox_lags.valueChanged.connect(self.update_ui_state)
        
        # Connect UI state updates for point interpolation tab
        self.mMapLayerComboBox_covariate_point.layerChanged.connect(self.update_ui_state)
        self.mFieldComboBox_covariate.fieldChanged.connect(self.update_ui_state)
        self.comboBox_variogram_point.currentTextChanged.connect(self.update_ui_state)
        self.comboBox_variogram_point.currentTextChanged.connect(self.reset_variogram_parameters_point)
        self.comboBox_variogram_point.currentTextChanged.connect(self.on_variogram_model_changed_point)
        self.spinBox_lags_point.valueChanged.connect(self.update_ui_state)
        
        # Connect numeric input validation for raster tab
        self.doubleSpinBox_nugget.valueChanged.connect(self.validate_variogram_parameters)
        self.doubleSpinBox_sill.valueChanged.connect(self.validate_variogram_parameters)
        self.doubleSpinBox_range.valueChanged.connect(self.validate_variogram_parameters)
        
        # Connect numeric input validation for point tab
        self.doubleSpinBox_nugget_point.valueChanged.connect(self.validate_variogram_parameters_point)
        self.doubleSpinBox_sill_point.valueChanged.connect(self.validate_variogram_parameters_point)
        self.doubleSpinBox_range_point.valueChanged.connect(self.validate_variogram_parameters_point)

    def on_layer_changed(self, layer):
        """Handle layer change in the main data combobox."""
        self.mFieldComboBox.setLayer(layer)

    def on_covariate_layer_changed(self, layer):
        """Handle layer change in the covariate combobox."""
        self.mFieldComboBox_covariate.setLayer(layer)

    def sync_target_layer(self, layer):
        """Synchronize target layer with input layer."""
        if layer:
            self.mMapLayerComboBox_target_layer.setLayer(layer)

    def on_interpolation_method_changed_raster(self, method_name):
        """Handle interpolation method change for raster tab.
        
        Switches the visible parameter widget in the stacked widget based on
        the selected interpolation method.
        
        Args:
            method_name (str): Name of the selected interpolation method
        """
        if not hasattr(self, 'stackedWidget_method_params'):
            return
            
        # Get the index for this method
        method_index = InterpolationMethod.get_method_index(method_name)
        
        # Switch to the corresponding parameter page
        self.stackedWidget_method_params.setCurrentIndex(method_index)
        
        # Log the change
        QgsMessageLog.logMessage(
            f"Raster tab: Switched to parameter page {method_index} for method '{method_name}'",
            "I-PlugIn",
            Qgis.Info
        )
        
        # Update UI state to enable/disable buttons appropriately
        self.update_ui_state()

    def on_interpolation_method_changed_point(self, method_name):
        """Handle interpolation method change for point tab.
        
        Switches the visible parameter widget in the stacked widget based on
        the selected interpolation method.
        
        Args:
            method_name (str): Name of the selected interpolation method
        """
        if not hasattr(self, 'stackedWidget_method_params_point'):
            return
            
        # Get the index for this method
        method_index = InterpolationMethod.get_method_index(method_name)
        
        # Switch to the corresponding parameter page
        self.stackedWidget_method_params_point.setCurrentIndex(method_index)
        
        # Log the change
        QgsMessageLog.logMessage(
            f"Point tab: Switched to parameter page {method_index} for method '{method_name}'",
            "I-PlugIn",
            Qgis.Info
        )
        
        # Update UI state to enable/disable buttons appropriately
        self.update_ui_state()

    def on_variogram_model_changed_raster(self, model_name):
        """Handle variogram model change for raster tab.
        
        Shows/hides the range parameter based on the selected variogram model.
        Linear models don't have a range parameter (unbounded growth).
        
        Args:
            model_name (str): Name of the selected variogram model
        """
        is_linear = (model_name == "Linear")
        
        # Hide range parameter for Linear model (input parameters)
        if hasattr(self, 'label_range_3'):
            self.label_range_3.setVisible(not is_linear)
        if hasattr(self, 'doubleSpinBox_range'):
            self.doubleSpinBox_range.setVisible(not is_linear)
        
        # Hide range parameter in optimized parameters display
        if hasattr(self, 'label_optimized_range_label_raster'):
            self.label_optimized_range_label_raster.setVisible(not is_linear)
        if hasattr(self, 'label_optimized_range_raster'):
            self.label_optimized_range_raster.setVisible(not is_linear)
        
        # Log the change
        QgsMessageLog.logMessage(
            f"Raster tab: Range parameter {'hidden' if is_linear else 'visible'} for model '{model_name}'",
            "I-PlugIn",
            Qgis.Info
        )

    def on_variogram_model_changed_point(self, model_name):
        """Handle variogram model change for point tab.
        
        Shows/hides the range parameter based on the selected variogram model.
        Linear models don't have a range parameter (unbounded growth).
        
        Args:
            model_name (str): Name of the selected variogram model
        """
        is_linear = (model_name == "Linear")
        
        # Hide range parameter for Linear model (input parameters)
        if hasattr(self, 'label_range_4'):
            self.label_range_4.setVisible(not is_linear)
        if hasattr(self, 'doubleSpinBox_range_point'):
            self.doubleSpinBox_range_point.setVisible(not is_linear)
        
        # Hide range parameter in optimized parameters display
        if hasattr(self, 'label_optimized_range_label_point'):
            self.label_optimized_range_label_point.setVisible(not is_linear)
        if hasattr(self, 'label_optimized_range_point'):
            self.label_optimized_range_point.setVisible(not is_linear)
        
        # Log the change
        QgsMessageLog.logMessage(
            f"Point tab: Range parameter {'hidden' if is_linear else 'visible'} for model '{model_name}'",
            "I-PlugIn",
            Qgis.Info
        )

    def get_point_interpolation_parameters(self):
        """Sammelt die Parameter für die Punkt-Interpolation."""
        params = {
            'target_layer': self.mMapLayerComboBox_target_layer.currentLayer(),
            'covariate_layer': self.mMapLayerComboBox_covariate_point.currentLayer(),
            'covariate_field': self.mFieldComboBox_covariate.currentField(),
            'method': 'ordinary_kriging',
            'variogram_model': self.comboBox_variogram_point.currentText(),
            'sill': self.doubleSpinBox_sill_point.value(),
            'range': self.doubleSpinBox_range_point.value(),
            'nugget': self.doubleSpinBox_nugget_point.value(),
            'nlags': self.spinBox_lags_point.value()
        }
        
        # Use stored variogram_info if available from analysis, otherwise create fallback
        if self.variogram_info_point:
            params['variogram_info'] = self.variogram_info_point
        else:
            # Fallback: Create variogram_info with UI values (no analysis performed)
            params['variogram_info'] = {
                'metrics': {},
                'parameters': {
                    'nugget': params['nugget'],
                    'range': params['range'],
                    'sill': params['sill'],
                    'model_type': params['variogram_model']
                },
                'experimental': {'lags': [], 'semivariance': []},
                'model': {'lags': [], 'semivariance': []},
                'plot_path': None
            }
        return params
        
    def validate_point_interpolation_inputs(self):
        """Validiert die Eingaben für die Punkt-Interpolation."""
        # Check target layer
        if not self.mMapLayerComboBox_target_layer.currentLayer():
            QMessageBox.warning(self, "Warnung", "Bitte wählen Sie einen Ziel-Layer aus.")
            return False
        
        # Check covariate layer
        if not self.mMapLayerComboBox_covariate_point.currentLayer():
            QMessageBox.warning(self, "Warnung", "Bitte wählen Sie einen Kovariaten-Layer aus.")
            return False
            
        # Check covariate field (not the raster field!)
        if not self.mFieldComboBox_covariate.currentField():
            QMessageBox.warning(self, "Warnung", "Bitte wählen Sie ein Kovariaten-Feld aus.")
            return False

        # Check for zero and NULL values in the COVARIATE field (not target!)
        has_zero = False
        has_null = False
        from qgis.PyQt.QtCore import QVariant
        
        covariate_layer = self.mMapLayerComboBox_covariate_point.currentLayer()
        covariate_field = self.mFieldComboBox_covariate.currentField()
        
        for feature in covariate_layer.getFeatures():
            value = feature[covariate_field]
            # Check for NULL values
            if value is None or (isinstance(value, QVariant) and value.isNull()):
                has_null = True
                break
            try:
                if float(value) == 0:
                    has_zero = True
                    break
            except (ValueError, TypeError, AttributeError):
                # Value not convertible - treat as invalid
                has_null = True
                break
        
        if has_null:
            QMessageBox.warning(
                self,
                "Warnung",
                "Kovariaten-Daten enthalten leere oder ungültige Werte (NULLs). Die Interpolation kann dies nicht verarbeiten. Bitte filtern."
            )
            return False
            
        if has_zero:
            QMessageBox.warning(
                self,
                "Warnung",
                "Kovariaten-Daten enthalten 0 Werte. Die Interpolation kann dies nicht verarbeiten. Bitte filtern."
            )
            return False
            
        return True

    def interpolate_points(self):
        """Handle point interpolation button click."""
        try:
            # Validate inputs
            if not self.validate_point_interpolation_inputs():
                return
                
            # Get parameters
            params = self.get_point_interpolation_parameters()
            
            # Save current settings
            self.save_settings()
            
            # Create progress dialog
            progress = QProgressDialog(
                "Punkt-Interpolation läuft...",
                "Abbrechen",
                0,
                0,
                self
            )
            progress.setWindowTitle("I-PlugIn")
            progress.setWindowModality(Qt.WindowModal)
            progress.setMinimumDuration(0)
            progress.setAutoClose(True)
            progress.setAutoReset(True)
            progress.setMinimum(0)
            progress.setMaximum(0)  # Unbestimmter Fortschritt
            
            # Run interpolation
            if self.plugin:
                try:
                    # Show progress dialog
                    progress.show()
                    
                    # Process events to keep UI responsive
                    QCoreApplication.processEvents()
                    
                    # Run interpolation
                    self.plugin.run_point_interpolation(params)
                    
                    # Close progress dialog
                    progress.close()
                    
                    # Erstelle passende Success-Nachricht basierend auf Backup-Status
                    backup_msg = ""
                    if params.get('backup_created'):
                        backup_msg = "\n\nErstellung eines Backups des Ziel-Layers wurde im Projektverzeichnis unter 'backups/' durchgeführt."
                    elif params.get('backup_path'):
                        backup_msg = "\n\nEin Backup des Ziel-Layers existiert bereits im Projektverzeichnis unter 'backups/'."
                    
                    QMessageBox.information(
                        self,
                        "Erfolg",
                        f"Punkt-Interpolation erfolgreich abgeschlossen.{backup_msg}"
                    )
                    
                except InterpolationError as e:
                    progress.close()
                    raise
                except Exception as e:
                    progress.close()
                    raise
                    
                finally:
                    progress.close()
            
        except DataValidationError as e:
            QMessageBox.warning(self, "Datenvalidierung", str(e))
        except GeometryError as e:
            QMessageBox.warning(self, "Geometrie-Problem", str(e))
        except InterpolationCalculationError as e:
            QMessageBox.critical(self, "Interpolation fehlgeschlagen", str(e))
        except InterpolationError as e:
            QMessageBox.critical(self, "Fehler", str(e))
        except Exception as e:
            QMessageBox.critical(
                self,
                "Unerwarteter Fehler",
                f"Ein unerwarteter Fehler ist aufgetreten:\n\n{str(e)}"
            )

    def save_settings(self):
        """Save current settings."""
        settings = QSettings()
        
        # Save layer and field selections
        if self.mMapLayerComboBox.currentLayer():
            settings.setValue("IPlugIn/input_layer", self.mMapLayerComboBox.currentLayer().id())
        if self.mFieldComboBox.currentField():
            settings.setValue("IPlugIn/input_field", self.mFieldComboBox.currentField())
        if self.mMapLayerComboBox_boundary.currentLayer():
            settings.setValue("IPlugIn/boundary_layer", self.mMapLayerComboBox_boundary.currentLayer().id())

        # Save interpolation settings
        settings.setValue("IPlugIn/cell_size", self.doubleSpinBox_cellsize.value())
        
        # Save variogram model selection (but NOT the parameters - they should always start with defaults)
        settings.setValue("IPlugIn/variogram_model", self.comboBox_variogram.currentIndex())
        # Note: nugget, range, sill, lags are NOT saved - they reset to defaults on each plugin open

    def load_settings(self):
        """Load saved settings."""
        settings = QSettings()
        
        # Block signals during loading to prevent cascade updates
        widgets_to_block = [
            self.mMapLayerComboBox, self.mFieldComboBox, self.mMapLayerComboBox_boundary,
            self.doubleSpinBox_cellsize, self.comboBox_variogram,
            self.doubleSpinBox_nugget, self.doubleSpinBox_range, self.doubleSpinBox_sill,
            self.spinBox_lags
        ]
        for widget in widgets_to_block:
            if widget:
                widget.blockSignals(True)
        
        # Load layer and field selections
        layer_id = settings.value("IPlugIn/input_layer", "")
        if layer_id:
            layer = QgsProject.instance().mapLayer(layer_id)
            if layer:
                self.mMapLayerComboBox.setLayer(layer)
                
        field = settings.value("IPlugIn/input_field", "")
        if field:
            self.mFieldComboBox.setField(field)
            
        boundary_id = settings.value("IPlugIn/boundary_layer", "")
        if boundary_id:
            layer = QgsProject.instance().mapLayer(boundary_id)
            if layer:
                self.mMapLayerComboBox_boundary.setLayer(layer)
                      
        # Load interpolation settings with Config defaults
        self.doubleSpinBox_cellsize.setValue(
            float(settings.value("IPlugIn/cell_size", InterpolationConfig.DEFAULT_CELL_SIZE))
        )
        
        # Load variogram model selection
        try:
            variogram_idx = int(settings.value("IPlugIn/variogram_model", 0))
            if 0 <= variogram_idx < self.comboBox_variogram.count():
                self.comboBox_variogram.setCurrentIndex(variogram_idx)
        except (ValueError, TypeError):
            # If there's an error, just set to first item
            self.comboBox_variogram.setCurrentIndex(0)
            
        # Always use default values for variogram parameters (not loaded from settings)
        # This ensures parameters start fresh on each plugin open
        self.doubleSpinBox_nugget.setValue(InterpolationConfig.DEFAULT_NUGGET)
        self.doubleSpinBox_range.setValue(InterpolationConfig.DEFAULT_RANGE)
        self.doubleSpinBox_sill.setValue(InterpolationConfig.DEFAULT_SILL)
        self.spinBox_lags.setValue(InterpolationConfig.DEFAULT_NLAGS)
        
        # Unblock signals after loading
        for widget in widgets_to_block:
            if widget:
                widget.blockSignals(False)

    def set_plugin_directory(self, directory):
        """Set the plugin output directory."""
        self.plugin_dir = directory

    def get_parameters(self):
        """Get parameters from dialog."""
        params = {
            'input_layer': self.mMapLayerComboBox.currentLayer(),
            'input_field': self.mFieldComboBox.currentField(),
            'method': 'ordinary_kriging',
            'cell_size': self.doubleSpinBox_cellsize.value(),
            'boundary_layer': self.mMapLayerComboBox_boundary.currentLayer(),
            'variogram_model': self.comboBox_variogram.currentText(),
            'sill': self.doubleSpinBox_sill.value(),
            'range': self.doubleSpinBox_range.value(),
            'nugget': self.doubleSpinBox_nugget.value(),
            'nlags': self.spinBox_lags.value()
        }
        
        # Add variogram_info if available from analysis
        if self.variogram_info_raster:
            params['variogram_info'] = self.variogram_info_raster
        
        return params

    def get_kriging_parameters(self):
        """Get current kriging parameters from UI."""
        try:
            return {
                'variogram_model': self.comboBox_variogram.currentText().lower(),
                'nugget': self.doubleSpinBox_nugget.value(),
                'range': self.doubleSpinBox_range.value(),
                'sill': self.doubleSpinBox_sill.value(),
                'nlags': self.spinBox_lags.value()
            }
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Failed to get kriging parameters: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )
            return None
# VALIDIERT DIE EINBEBENEN SACHEN
    def validate_inputs(self):
        """Validate user inputs."""
        # Check input layer
        input_layer = self.mMapLayerComboBox.currentLayer()
        if not input_layer:
            QMessageBox.warning(
                self,
                "Warnung",
                "Bitte wählen Sie einen Eingabelayer aus."
            )
            return False
            
        # Check if input layer has features
        if input_layer.featureCount() == 0:
            QMessageBox.warning(
                self,
                "Warnung",
                "Der ausgewählte Eingabelayer enthält keine Features."
            )
            return False
            
        # Check field selection
        field = self.mFieldComboBox.currentField()
        if not field:
            QMessageBox.warning(
                self,
                "Warnung",
                "Bitte wählen Sie ein Feld für die Interpolation aus."
            )
            return False
            
        # Check if field exists in layer
        if field not in [field.name() for field in input_layer.fields()]:
            QMessageBox.warning(
                self,
                "Warnung",
                "Das ausgewählte Feld existiert nicht im Eingabelayer."
            )
            return False

        # Check for zero values and NULLs in the selected field
        has_zero = False
        has_null = False
        from qgis.PyQt.QtCore import QVariant
        for feature in input_layer.getFeatures():
            value = feature[field]
            # Prüfe auf echte Nullwerte und auf QVariant/None
            if value is None or (isinstance(value, QVariant) and value.isNull()):
                has_null = True
                break
            try:
                if float(value) == 0:
                    has_zero = True
                    break
            except (ValueError, TypeError, AttributeError):
                # Falls ein Wert nicht konvertierbar ist, als ungültig behandeln
                has_null = True
                break
        if has_null:
            QMessageBox.warning(
                self,
                "Warnung",
                "Daten enthalten leere oder ungültige Werte (NULLs). Die Interpolation kann dies nicht verarbeiten. Bitte filtern."
            )
            return False
        if has_zero:
            QMessageBox.warning(
                self,
                "Warnung",
                "Daten enthalten 0 Werte. Die Interpolation kann dies nicht verarbeiten. Bitte filtern."
            )
            return False

        # Check cell size
        if self.doubleSpinBox_cellsize.value() <= 0:
            QMessageBox.warning(
                self,
                "Warnung",
                "Die Zellgröße muss größer als 0 sein."
            )
            return False
            
        # Check boundary layer if selected
        boundary_layer = self.mMapLayerComboBox_boundary.currentLayer()
        if boundary_layer:
            if boundary_layer.featureCount() == 0:
                QMessageBox.warning(
                    self,
                    "Warnung",
                    "Der ausgewählte Grenzlayer enthält keine Features."
                )
                return False
                
            # Check if any boundary polygons intersect with the input points
            has_intersection = False
            for point_feature in input_layer.getFeatures():
                for boundary_feature in boundary_layer.getFeatures():
                    if point_feature.geometry().intersects(boundary_feature.geometry()):
                        has_intersection = True
                        break
                if has_intersection:
                    break
                    
            if not has_intersection:
                reply = QMessageBox.question(
                    self,
                    "Warnung",
                    "Keine Punkte liegen innerhalb der ausgewählten Grenze. "
                    "Möchten Sie trotzdem fortfahren?",
                    QMessageBox.Yes | QMessageBox.No,
                    QMessageBox.No
                )
                if reply == QMessageBox.No:
                    return False
            
        return True
# DAS PASSIERT WENN MAN OK DRÜCKT 
    def accept(self):
        """Handle OK button click."""
        if not self.validate_inputs():
            return
            
        try:
            # Get and save parameters
            params = self.get_parameters()
            self.save_settings()  # This will save all current UI values
            
            # Store parameters for plugin to use
            if self.plugin:
                self.plugin.last_parameters = params
            
            # Accept dialog
            super().accept()
            
        except DataValidationError as e:
            QMessageBox.warning(self, "Datenvalidierung", str(e))
        except GeometryError as e:
            QMessageBox.warning(self, "Geometrie-Problem", str(e))
        except InterpolationCalculationError as e:
            QMessageBox.critical(self, "Interpolation fehlgeschlagen", str(e))
        except InterpolationError as e:
            QMessageBox.critical(self, "Fehler", str(e))
        except Exception as e:
            QMessageBox.critical(
                self,
                "Unerwarteter Fehler",
                f"Ein unerwarteter Fehler ist aufgetreten:\n\n{str(e)}"
            )

    def show_variogram_analysis(self):
        """Show variogram analysis dialog with current parameters."""
        # Create progress dialog immediately
        progress = QProgressDialog(
            "Variogramm-Analyse läuft...",
            "Abbrechen",
            0,
            0,
            self
        )
        progress.setWindowTitle("I-PlugIn")
        progress.setWindowModality(Qt.WindowModal)
        progress.setMinimumDuration(0)  # Show immediately
        progress.setAutoClose(True)
        progress.setAutoReset(True)
        progress.setCancelButton(None)  # No cancel button for variogram analysis
        
        try:
            # Show progress dialog immediately
            progress.show()
            QCoreApplication.processEvents()  # Force UI update
            
            # Get current parameters
            params = self.get_kriging_parameters()
            if not params:
                progress.close()
                return
                
            # Get input data
            layer = self.mMapLayerComboBox.currentLayer()
            field = self.mFieldComboBox.currentField()
            boundary = self.mMapLayerComboBox_boundary.currentLayer()
            
            # Prepare data
            x, y, z = self.plugin.prepare_data(layer, field, boundary)
            if x is None or len(x) == 0:
                progress.close()
                QgsMessageLog.logMessage(
                    "No valid data points found for variogram analysis",
                    "I-PlugIn",
                    Qgis.Warning
                )
                return
                
            # Analyze variogram
            results = self.plugin.analyze_variogram(x, y, z, params)
            if not results:
                progress.close()
                return
                
            # Store variogram_info for later use in get_parameters()
            self.variogram_info_raster = results
                
            # Close progress dialog
            progress.close()
                
            # Update dialog with optimized parameters
            self.update_variogram_parameters({
                'nugget': results['parameters']['nugget'],
                'range': results['parameters']['range'],
                'sill': results['parameters']['sill'],
                'metrics': results['metrics']
            }, point_tab=False)
                
            # Show dialog
            dialog = VariogramDialog(self)
            dialog.display_results(results['plot_path'], results['metrics'])
            dialog.exec_()
            
        except InterpolationCalculationError as e:
            progress.close()
            QMessageBox.critical(self, "Variogramm-Analyse fehlgeschlagen", str(e))
        except DataValidationError as e:
            progress.close()
            QMessageBox.warning(self, "Datenvalidierung", str(e))
        except InterpolationError as e:
            progress.close()
            QMessageBox.critical(self, "Fehler", str(e))
        except Exception as e:
            progress.close()
            QgsMessageLog.logMessage(
                f"Unerwarteter Fehler bei Variogramm-Analyse: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )
            QMessageBox.critical(self, "Unerwarteter Fehler", f"Ein unerwarteter Fehler ist aufgetreten:\n\n{str(e)}")

    def update_ui_state(self):
        """Update UI state based on current selections."""
        try:
            # Check if we have valid input data for raster tab
            has_valid_inputs = bool(
                self.mMapLayerComboBox.currentLayer() is not None and
                self.mFieldComboBox.currentField() and
                self.comboBox_variogram.currentText() != ''
            )
            
            # Enable analyze button if we have valid inputs
            self.analyze_variogram_button.setEnabled(has_valid_inputs)

            # Check if we have valid input data for point interpolation tab
            has_valid_point_inputs = bool(
                self.mMapLayerComboBox_covariate_point.currentLayer() is not None and
                self.mFieldComboBox_covariate.currentField() and
                self.comboBox_variogram_point.currentText() != ''
            )
            self.analyze_variogram_button_points.setEnabled(has_valid_point_inputs)

            # Enable parameter inputs for raster tab
            self.doubleSpinBox_nugget.setEnabled(has_valid_inputs)
            self.doubleSpinBox_range.setEnabled(has_valid_inputs)
            self.doubleSpinBox_sill.setEnabled(has_valid_inputs)
            
            # Enable parameter inputs for point interpolation tab
            self.doubleSpinBox_nugget_point.setEnabled(has_valid_point_inputs)
            self.doubleSpinBox_range_point.setEnabled(has_valid_point_inputs)
            self.doubleSpinBox_sill_point.setEnabled(has_valid_point_inputs)
                
        except Exception as e:
            QgsMessageLog.logMessage(
                f"UI state update failed: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )

    def reset_variogram_parameters_raster(self):
        """Reset variogram parameters to defaults when model changes (raster tab)."""
        try:
            # Block signals to prevent triggering validation during reset
            self.doubleSpinBox_nugget.blockSignals(True)
            self.doubleSpinBox_range.blockSignals(True)
            self.doubleSpinBox_sill.blockSignals(True)
            
            # Reset to default values
            self.doubleSpinBox_nugget.setValue(InterpolationConfig.DEFAULT_NUGGET)
            self.doubleSpinBox_range.setValue(InterpolationConfig.DEFAULT_RANGE)
            self.doubleSpinBox_sill.setValue(InterpolationConfig.DEFAULT_SILL)
            
            # Unblock signals
            self.doubleSpinBox_nugget.blockSignals(False)
            self.doubleSpinBox_range.blockSignals(False)
            self.doubleSpinBox_sill.blockSignals(False)
            
            # Hide optimized parameters group box
            if hasattr(self, 'optimized_params_group_raster'):
                self.optimized_params_group_raster.setVisible(False)
            
            # Hide metrics label if it exists
            if hasattr(self, 'metrics_label_raster'):
                self.metrics_label_raster.setVisible(False)
                
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Failed to reset variogram parameters (Raster): {str(e)}",
                "I-PlugIn",
                Qgis.Warning
            )

    def reset_variogram_parameters_point(self):
        """Reset variogram parameters to defaults when model changes (point tab)."""
        try:
            # Block signals to prevent triggering validation during reset
            self.doubleSpinBox_nugget_point.blockSignals(True)
            self.doubleSpinBox_range_point.blockSignals(True)
            self.doubleSpinBox_sill_point.blockSignals(True)
            
            # Reset to default values
            self.doubleSpinBox_nugget_point.setValue(InterpolationConfig.DEFAULT_NUGGET)
            self.doubleSpinBox_range_point.setValue(InterpolationConfig.DEFAULT_RANGE)
            self.doubleSpinBox_sill_point.setValue(InterpolationConfig.DEFAULT_SILL)
            
            # Unblock signals
            self.doubleSpinBox_nugget_point.blockSignals(False)
            self.doubleSpinBox_range_point.blockSignals(False)
            self.doubleSpinBox_sill_point.blockSignals(False)
            
            # Hide optimized parameters group box
            if hasattr(self, 'optimized_params_group_point'):
                self.optimized_params_group_point.setVisible(False)
            
            # Hide metrics label if it exists
            if hasattr(self, 'metrics_label_points'):
                self.metrics_label_points.setVisible(False)
                
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Failed to reset variogram parameters (Point): {str(e)}",
                "I-PlugIn",
                Qgis.Warning
            )

    def validate_variogram_parameters(self):
        """Validate variogram parameters for raster tab and update UI state."""
        try:
            nugget = self.doubleSpinBox_nugget.value()
            sill = self.doubleSpinBox_sill.value()
            range_ = self.doubleSpinBox_range.value()
            
            # Warn if parameters might be suboptimal
            warnings = []
            
            if nugget < 0:
                warnings.append("Nugget sollte nicht negativ sein")
            
            if range_ <= 0:
                warnings.append("Range sollte größer als 0 sein")
            
            if sill <= 0:
                warnings.append("Sill sollte größer als 0 sein")
            
            if nugget > sill:
                warnings.append("Nugget sollte nicht größer als Sill sein")
            
            # Show warnings if any
            if warnings:
                warning_text = "\n".join(warnings)
                QgsMessageLog.logMessage(
                    f"Variogram Parameter Warnings (Raster):\n{warning_text}",
                    "I-PlugIn",
                    Qgis.Warning
                )
            
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Parameter validation failed (Raster): {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )

    def validate_variogram_parameters_point(self):
        """Validate variogram parameters for point tab and update UI state."""
        try:
            nugget = self.doubleSpinBox_nugget_point.value()
            sill = self.doubleSpinBox_sill_point.value()
            range_ = self.doubleSpinBox_range_point.value()
            
            # Warn if parameters might be suboptimal
            warnings = []
            
            if nugget < 0:
                warnings.append("Nugget sollte nicht negativ sein")
            
            if range_ <= 0:
                warnings.append("Range sollte größer als 0 sein")
            
            if sill <= 0:
                warnings.append("Sill sollte größer als 0 sein")
            
            if nugget > sill:
                warnings.append("Nugget sollte nicht größer als Sill sein")
            
            # Show warnings if any
            if warnings:
                warning_text = "\n".join(warnings)
                QgsMessageLog.logMessage(
                    f"Variogram Parameter Warnings (Point):\n{warning_text}",
                    "I-PlugIn",
                    Qgis.Warning
                )
            
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Parameter validation failed (Point): {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )

    def update_variogram_parameters(self, parameters, point_tab=False):
        """Update optimized variogram parameters in labels (NOT spinboxes - those remain as user input)."""
        try:
            if not parameters:
                return

            # Check if this is a linear model (has slope instead of range/sill)
            is_linear = parameters.get('slope') is not None and parameters.get('range') is None

            if point_tab:
                # Update optimized parameter labels for point tab
                nugget = parameters.get('nugget')
                nugget_str = f"{nugget:.3f}" if nugget is not None else "N/A"
                
                self.label_optimized_nugget_point.setText(nugget_str)
                
                if is_linear:
                    # Linear model: show slope instead of range/sill
                    slope = parameters.get('slope')
                    slope_str = f"{slope:.6f}" if slope is not None else "N/A"
                    self.label_optimized_range_point.setText(f"Slope: {slope_str}")
                    self.label_optimized_sill_point.setText("N/A (Linear)")
                else:
                    # Other models: show range and sill
                    range_val = parameters.get('range')
                    sill = parameters.get('sill')
                    range_str = f"{range_val:.2f}" if range_val is not None else "N/A"
                    sill_str = f"{sill:.3f}" if sill is not None else "N/A"
                    self.label_optimized_range_point.setText(range_str)
                    self.label_optimized_sill_point.setText(sill_str)
                
                # Show the optimized parameters group box
                self.optimized_params_group_point.setVisible(True)
                
                # Use a dedicated metrics label for the point tab
                if not hasattr(self, 'metrics_label_points'):
                    parent_widget = self.page_kriging_2 if hasattr(self, 'page_kriging_2') else self
                    self.metrics_label_points = QtWidgets.QLabel(parent_widget)
                    layout = parent_widget.layout()
                    if not layout:
                        layout = QtWidgets.QVBoxLayout(parent_widget)
                        parent_widget.setLayout(layout)
                    layout.addWidget(self.metrics_label_points)
                metrics_label = self.metrics_label_points
            else:
                # Update optimized parameter labels for raster tab
                nugget = parameters.get('nugget')
                nugget_str = f"{nugget:.3f}" if nugget is not None else "N/A"
                
                self.label_optimized_nugget_raster.setText(nugget_str)
                
                if is_linear:
                    # Linear model: show slope instead of range/sill
                    slope = parameters.get('slope')
                    slope_str = f"{slope:.6f}" if slope is not None else "N/A"
                    self.label_optimized_range_raster.setText(f"Slope: {slope_str}")
                    self.label_optimized_sill_raster.setText("N/A (Linear)")
                else:
                    # Other models: show range and sill
                    range_val = parameters.get('range')
                    sill = parameters.get('sill')
                    range_str = f"{range_val:.2f}" if range_val is not None else "N/A"
                    sill_str = f"{sill:.3f}" if sill is not None else "N/A"
                    self.label_optimized_range_raster.setText(range_str)
                    self.label_optimized_sill_raster.setText(sill_str)
                
                # Show the optimized parameters group box
                self.optimized_params_group_raster.setVisible(True)
                
                # Use a dedicated metrics label for the raster tab
                if not hasattr(self, 'metrics_label_raster'):
                    parent_widget = self.page_kriging if hasattr(self, 'page_kriging') else self
                    self.metrics_label_raster = QtWidgets.QLabel(parent_widget)
                    layout = parent_widget.layout()
                    if not layout:
                        layout = QtWidgets.QVBoxLayout(parent_widget)
                        parent_widget.setLayout(layout)
                    layout.addWidget(self.metrics_label_raster)
                metrics_label = self.metrics_label_raster

            # Update metrics display only in the correct tab
            metrics = parameters.get('metrics', {})
            if metrics:
                # Format metrics safely - check if values exist before formatting
                rmse = metrics.get('rmse')
                r2 = metrics.get('r2')
                
                rmse_str = f"{rmse:.3f}" if rmse is not None else "N/A"
                r2_str = f"{r2:.3f}" if r2 is not None else "N/A"
                
                metrics_text = (
                    f"<b>Variogramm Metriken:</b><br>"
                    f"RMSE: {rmse_str}<br>"
                    f"R²: {r2_str}"
                )
                metrics_label.setText(metrics_text)
                metrics_label.setVisible(True)
            else:
                metrics_label.setVisible(False)

        except Exception as e:
            QgsMessageLog.logMessage(
                f"Failed to update variogram parameters: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )
