# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IPlugInDialog
                                 A QGIS plugin
 Plugin to perform interpolation task for onfarm research module
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lucas Johannsen
        email                : lucas.johannsen@fh-kiel.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtWidgets import QProgressDialog, QMessageBox, QPushButton, QDialogButtonBox
from qgis.core import (QgsMapLayerProxyModel, QgsFieldProxyModel, QgsProject, QgsMessageLog, Qgis,
                      QgsRasterLayer, QgsRectangle, QgsCoordinateReferenceSystem)

from .variogram_dialog import VariogramDialog

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Optimierung.ui'))


class IPlugInDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface, parent=None):
        """Constructor."""
        super(IPlugInDialog, self).__init__(parent)
        self.iface = iface
        self.plugin = None  # Will be set by the plugin instance
        self.plugin_dir = None
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Initialize UI components
        self.setup_ui_components()
        
        # Connect signals
        self.connect_signals()
        
        # Load saved settings
        self.load_settings()
# UI COMPONENTEN WERDEN HIER AUFGESETZT 
    def setup_ui_components(self):
        """Setup UI components after loading."""
        # Set up map layer combo box to show only point layers
        self.mMapLayerComboBox.setFilters(QgsMapLayerProxyModel.PointLayer)
        
        # Set up target layer combo box to show only point layers
        self.mMapLayerComboBox_target_layer.setFilters(QgsMapLayerProxyModel.PointLayer)
        
        # Set up covariate point layer combo box to show only point layers
        self.mMapLayerComboBox_covariate_point.setFilters(QgsMapLayerProxyModel.PointLayer)
        
        # Set up boundary layer combo box to show only polygon layers
        self.mMapLayerComboBox_boundary.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        
        # Set field types to numeric
        self.mFieldComboBox.setFilters(QgsFieldProxyModel.Numeric)
        self.mFieldComboBox_covariate.setFilters(QgsFieldProxyModel.Numeric)
        
        # Set default values
        self.doubleSpinBox_cellsize.setValue(10.0)
        self.doubleSpinBox_cellsize.setRange(0.1, 10000.0)  # Allow larger cell sizes
        self.doubleSpinBox_cellsize.setDecimals(2)
        
        self.doubleSpinBox_sill.setValue(0.1)
        self.doubleSpinBox_sill.setRange(0.0, 10000.0)  # Allow larger sill values
        self.doubleSpinBox_sill.setDecimals(3)
        
        self.doubleSpinBox_range.setValue(100.0)
        self.doubleSpinBox_range.setRange(0.1, 10000.0)  # Allow larger range values
        self.doubleSpinBox_range.setDecimals(2)
        
        self.doubleSpinBox_nugget.setValue(0.0)
        self.doubleSpinBox_nugget.setRange(0.0, 10000.0)  # Allow larger nugget values
        self.doubleSpinBox_nugget.setDecimals(3)
        
        # Setup lags spinbox
        self.spinBox_lags.setValue(10)
        self.spinBox_lags.setRange(3, 20)  # Min 3, Max 20 lags
        
        # Load saved settings
        self.load_settings()
        
        # Hide progress bar initially
        if hasattr(self, 'progressBar'):
            self.progressBar.hide()

        # Add variogram analysis and interpolation buttons to kriging page using layout
        self.analyze_variogram_button = QPushButton("Variogram Analyse")
        self.analyze_variogram_button.setEnabled(False)
        self.interpolate_button = QPushButton("Interpolieren")
        # Use the layout from page_kriging (should be present after UI edit)
        layout = self.page_kriging.layout()
        if layout is not None:
            layout.addWidget(self.analyze_variogram_button)
            #layout.addWidget(self.interpolate_button)
        else:
            # Fallback: just parent to page_kriging if layout missing
            self.analyze_variogram_button.setParent(self.page_kriging)
            #self.interpolate_button.setParent(self.page_kriging)

        # Add variogram analysis button for point interpolation (page_kriging_2)
        self.analyze_variogram_button_points = QPushButton("Variogram Analyse")
        self.analyze_variogram_button_points.setEnabled(False)
        layout_points = self.page_kriging_2.layout() if hasattr(self, 'page_kriging_2') else None
        if layout_points is not None:
            layout_points.addWidget(self.analyze_variogram_button_points)
        elif hasattr(self, 'page_kriging_2'):
            self.analyze_variogram_button_points.setParent(self.page_kriging_2)

# VERBINDUNG DER SIGNAL 

    def show_variogram_analysis_points(self):
        """Show variogram analysis dialog with current parameters for point interpolation."""
        try:
            # Get current parameters for point interpolation
            params = self.get_point_interpolation_parameters()
            if not params:
                return

            # Get input data for point interpolation
            covariate_layer = params.get('covariate_layer')
            covariate_field = params.get('covariate_field')
            boundary = None  # Optional: use a boundary if relevant for points

            # Prepare data (x, y, z from covariate layer)
            x, y, z = self.plugin.prepare_data(covariate_layer, covariate_field, boundary)
            if x is None or len(x) == 0:
                QgsMessageLog.logMessage(
                    "No valid data points found for point variogram analysis",
                    "I-PlugIn",
                    Qgis.Warning
                )
                return

            # Analyze variogram (using point params)
            results = self.plugin.analyze_variogram(x, y, z, params)
            if not results:
                return

            # Update dialog with optimized parameters for points
            self.update_variogram_parameters({
                'nugget': results['parameters']['nugget'],
                'range': results['parameters']['range'],
                'sill': results['parameters']['sill'],
                'metrics': results['metrics']
            }, point_tab=True)

            # Show dialog
            dialog = VariogramDialog(self)
            dialog.display_results(results['plot_path'], results['metrics'])
            dialog.exec_()

        except Exception as e:
            QgsMessageLog.logMessage(
                f"Failed to show point variogram analysis: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )

    def connect_signals(self):
        """Connect signals to slots."""
        # Connect layer selection changes to field combo boxes
        self.mMapLayerComboBox.layerChanged.connect(self.on_layer_changed)
        self.mMapLayerComboBox.layerChanged.connect(self.sync_target_layer)
        self.mMapLayerComboBox_covariate_point.layerChanged.connect(self.on_covariate_layer_changed)

        # Connect interpolation buttons
        #self.interpolate_button.clicked.connect(self.accept)
        self.button_interpolate_points.clicked.connect(self.interpolate_points)
        self.button_interpolate_points_2.clicked.connect(self.accept)
        
        # Connect variogram analysis button
        self.analyze_variogram_button.clicked.connect(self.show_variogram_analysis)
        # Connect variogram analysis button for point interpolation
        self.analyze_variogram_button_points.clicked.connect(self.show_variogram_analysis_points)
        
        # Connect UI state updates
        self.mMapLayerComboBox.layerChanged.connect(self.update_ui_state)
        self.mFieldComboBox.fieldChanged.connect(self.update_ui_state)
        self.comboBox_variogram.currentTextChanged.connect(self.update_ui_state)
        # Add signal connections for point interpolation tab
        self.mMapLayerComboBox_covariate_point.layerChanged.connect(self.update_ui_state)
        self.mFieldComboBox_covariate.fieldChanged.connect(self.update_ui_state)
        self.comboBox_variogram_point.currentTextChanged.connect(self.update_ui_state)
        self.spinBox_lags_point.valueChanged.connect(self.update_ui_state)
        
        # Connect numeric input validation
        self.doubleSpinBox_nugget.valueChanged.connect(self.validate_variogram_parameters)
        self.doubleSpinBox_sill.valueChanged.connect(self.validate_variogram_parameters)
        self.doubleSpinBox_range.valueChanged.connect(self.validate_variogram_parameters)

    def on_layer_changed(self, layer):
        """Handle layer change in the main data combobox."""
        self.mFieldComboBox.setLayer(layer)

    def on_covariate_layer_changed(self, layer):
        """Handle layer change in the covariate combobox."""
        self.mFieldComboBox_covariate.setLayer(layer)

    def sync_target_layer(self, layer):
        """Synchronize target layer with input layer."""
        if layer:
            self.mMapLayerComboBox_target_layer.setLayer(layer)

    def get_point_interpolation_parameters(self):
        """Sammelt die Parameter für die Punkt-Interpolation."""
        params = {
            'target_layer': self.mMapLayerComboBox_target_layer.currentLayer(),
            'covariate_layer': self.mMapLayerComboBox_covariate_point.currentLayer(),
            'covariate_field': self.mFieldComboBox_covariate.currentField(),
            'method': 'ordinary_kriging',
            'variogram_model': self.comboBox_variogram_point.currentText(),
            'sill': self.doubleSpinBox_sill_point.value(),
            'range': self.doubleSpinBox_range_point.value(),
            'nugget': self.doubleSpinBox_nugget_point.value(),
            'nlags': self.spinBox_lags_point.value()
        }
        # Inject variogram_info if not already present (i.e., if no analysis was performed)
        if 'variogram_info' not in params:
            params['variogram_info'] = {
                'metrics': {},
                'parameters': {
                    'nugget': params['nugget'],
                    'range': params['range'],
                    'sill': params['sill'],
                    'model_type': params['variogram_model']
                },
                'experimental': {'lags': [], 'semivariance': []},
                'model': {'lags': [], 'semivariance': []},
                'plot_path': None
            }
        return params
        
    def validate_point_interpolation_inputs(self):
        """Validiert die Eingaben für die Punkt-Interpolation."""
        if not self.mMapLayerComboBox_target_layer.currentLayer():
            QMessageBox.warning(self, "Warnung", "Bitte wählen Sie einen Ziel-Layer aus.")
            return False
            
        if not self.mFieldComboBox.currentField():
            QMessageBox.warning(self, "Warnung", "Bitte wählen Sie ein Eingabe-Feld aus.")
            return False

                # Check for zero values in the selected field
        has_zero = False
        for feature in self.mMapLayerComboBox_target_layer.currentLayer().getFeatures():
            value = feature[self.mFieldComboBox.currentField()]
            try:
                if value is not None and float(value) == 0:
                    has_zero = True
                    break
            except Exception:
                continue
        if has_zero:
            QMessageBox.warning(
                self,
                "Warnung",
                "Daten enthalten 0 Werte. Die Interpolation kann dies nicht verarbeiten. Bitte filtern."
            )
            return False
            
        if not self.mMapLayerComboBox_target_layer.currentLayer():
            QMessageBox.warning(self, "Warnung", "Bitte wählen Sie einen Ziel-Layer aus.")
            return False
            
        return True

    def interpolate_points(self):
        """Handle point interpolation button click."""
        try:
            # Validate inputs
            if not self.validate_point_interpolation_inputs():
                return
                
            # Get parameters
            params = self.get_point_interpolation_parameters()
            
            # Save current settings
            self.save_settings()
            
            # Create progress dialog
            progress = QProgressDialog(
                "Punkt-Interpolation läuft...",
                "Abbrechen",
                0,
                0,
                self
            )
            progress.setWindowTitle("I-PlugIn")
            progress.setWindowModality(Qt.WindowModal)
            progress.setMinimumDuration(0)
            progress.setAutoClose(True)
            progress.setAutoReset(True)
            progress.setMinimum(0)
            progress.setMaximum(0)  # Unbestimmter Fortschritt
            
            # Run interpolation
            if self.plugin:
                try:
                    # Show progress dialog
                    progress.show()
                    
                    # Process events to keep UI responsive
                    QCoreApplication.processEvents()
                    
                    # Run interpolation
                    self.plugin.run_point_interpolation(params)
                    
                    # Close progress dialog
                    progress.close()
                    
                    QMessageBox.information(
                        self,
                        "Erfolg",
                        "Punkt-Interpolation erfolgreich abgeschlossen."
                    )
                    
                except Exception as e:
                    progress.close()
                    raise e
                    
                finally:
                    progress.close()
            
        except Exception as e:
            QMessageBox.critical(
                self,
                "Fehler",
                f"Fehler bei der Punkt-Interpolation: {str(e)}"
            )

    def save_settings(self):
        """Save current settings."""
        settings = QSettings()
        
        # Save layer and field selections
        if self.mMapLayerComboBox.currentLayer():
            settings.setValue("IPlugIn/input_layer", self.mMapLayerComboBox.currentLayer().id())
        if self.mFieldComboBox.currentField():
            settings.setValue("IPlugIn/input_field", self.mFieldComboBox.currentField())
        if self.mMapLayerComboBox_boundary.currentLayer():
            settings.setValue("IPlugIn/boundary_layer", self.mMapLayerComboBox_boundary.currentLayer().id())

        # Save interpolation settings
        settings.setValue("IPlugIn/cell_size", self.doubleSpinBox_cellsize.value())
        
        # Save kriging parameters - store index for combobox
        settings.setValue("IPlugIn/variogram_model", self.comboBox_variogram.currentIndex())
        settings.setValue("nugget", self.doubleSpinBox_nugget.value())
        settings.setValue("range", self.doubleSpinBox_range.value())
        settings.setValue("sill", self.doubleSpinBox_sill.value())
        settings.setValue("lags", self.spinBox_lags.value())

    def load_settings(self):
        """Load saved settings."""
        settings = QSettings()
        
        # Load layer and field selections
        layer_id = settings.value("IPlugIn/input_layer", "")
        if layer_id:
            layer = QgsProject.instance().mapLayer(layer_id)
            if layer:
                self.mMapLayerComboBox.setLayer(layer)
                
        field = settings.value("IPlugIn/input_field", "")
        if field:
            self.mFieldComboBox.setField(field)
            
        boundary_id = settings.value("IPlugIn/boundary_layer", "")
        if boundary_id:
            layer = QgsProject.instance().mapLayer(boundary_id)
            if layer:
                self.mMapLayerComboBox_boundary.setLayer(layer)
                      
        # Load interpolation settings
        self.doubleSpinBox_cellsize.setValue(float(settings.value("IPlugIn/cell_size", 10.0)))
        
        # Load kriging parameters
        try:
            variogram_idx = int(settings.value("IPlugIn/variogram_model", 0))
            if 0 <= variogram_idx < self.comboBox_variogram.count():
                self.comboBox_variogram.setCurrentIndex(variogram_idx)
        except (ValueError, TypeError):
            # If there's an error, just set to first item
            self.comboBox_variogram.setCurrentIndex(0)
            
        self.doubleSpinBox_nugget.setValue(float(settings.value("nugget", 0.0)))
        self.doubleSpinBox_range.setValue(float(settings.value("range", 100.0)))
        self.doubleSpinBox_sill.setValue(float(settings.value("sill", 1.0)))
        self.spinBox_lags.setValue(int(settings.value("lags", 15)))

    def set_plugin_directory(self, directory):
        """Set the plugin output directory."""
        self.plugin_dir = directory

    def get_parameters(self):
        """Get parameters from dialog."""
        params = {
            'input_layer': self.mMapLayerComboBox.currentLayer(),
            'input_field': self.mFieldComboBox.currentField(),
            'method': 'ordinary_kriging',
            'cell_size': self.doubleSpinBox_cellsize.value(),
            'boundary_layer': self.mMapLayerComboBox_boundary.currentLayer(),
            'variogram_model': self.comboBox_variogram.currentText(),
            'sill': self.doubleSpinBox_sill.value(),
            'range': self.doubleSpinBox_range.value(),
            'nugget': self.doubleSpinBox_nugget.value(),
            'nlags': self.spinBox_lags.value()
        }
        
        return params

    def get_kriging_parameters(self):
        """Get current kriging parameters from UI."""
        try:
            return {
                'variogram_model': self.comboBox_variogram.currentText().lower(),
                'nugget': self.doubleSpinBox_nugget.value(),
                'range': self.doubleSpinBox_range.value(),
                'sill': self.doubleSpinBox_sill.value(),
                'nlags': self.spinBox_lags.value()
            }
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Failed to get kriging parameters: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )
            return None
# VALIDIERT DIE EINBEBENEN SACHEN
    def validate_inputs(self):
        """Validate user inputs."""
        # Check input layer
        input_layer = self.mMapLayerComboBox.currentLayer()
        if not input_layer:
            QMessageBox.warning(
                self,
                "Warnung",
                "Bitte wählen Sie einen Eingabelayer aus."
            )
            return False
            
        # Check if input layer has features
        if input_layer.featureCount() == 0:
            QMessageBox.warning(
                self,
                "Warnung",
                "Der ausgewählte Eingabelayer enthält keine Features."
            )
            return False
            
        # Check field selection
        field = self.mFieldComboBox.currentField()
        if not field:
            QMessageBox.warning(
                self,
                "Warnung",
                "Bitte wählen Sie ein Feld für die Interpolation aus."
            )
            return False
            
        # Check if field exists in layer
        if field not in [field.name() for field in input_layer.fields()]:
            QMessageBox.warning(
                self,
                "Warnung",
                "Das ausgewählte Feld existiert nicht im Eingabelayer."
            )
            return False

        # Check for zero values and NULLs in the selected field
        has_zero = False
        has_null = False
        from qgis.PyQt.QtCore import QVariant
        for feature in input_layer.getFeatures():
            value = feature[field]
            # Prüfe auf echte Nullwerte und auf QVariant/None
            if value is None or (isinstance(value, QVariant) and value.isNull()):
                has_null = True
                break
            try:
                if float(value) == 0:
                    has_zero = True
                    break
            except Exception:
                # Falls ein Wert nicht konvertierbar ist, als ungültig behandeln
                has_null = True
                break
        if has_null:
            QMessageBox.warning(
                self,
                "Warnung",
                "Daten enthalten leere oder ungültige Werte (NULLs). Die Interpolation kann dies nicht verarbeiten. Bitte filtern."
            )
            return False
        if has_zero:
            QMessageBox.warning(
                self,
                "Warnung",
                "Daten enthalten 0 Werte. Die Interpolation kann dies nicht verarbeiten. Bitte filtern."
            )
            return False

        # Check cell size
        if self.doubleSpinBox_cellsize.value() <= 0:
            QMessageBox.warning(
                self,
                "Warnung",
                "Die Zellgröße muss größer als 0 sein."
            )
            return False
            
        # Check boundary layer if selected
        boundary_layer = self.mMapLayerComboBox_boundary.currentLayer()
        if boundary_layer:
            if boundary_layer.featureCount() == 0:
                QMessageBox.warning(
                    self,
                    "Warnung",
                    "Der ausgewählte Grenzlayer enthält keine Features."
                )
                return False
                
            # Check if any boundary polygons intersect with the input points
            has_intersection = False
            for point_feature in input_layer.getFeatures():
                for boundary_feature in boundary_layer.getFeatures():
                    if point_feature.geometry().intersects(boundary_feature.geometry()):
                        has_intersection = True
                        break
                if has_intersection:
                    break
                    
            if not has_intersection:
                reply = QMessageBox.question(
                    self,
                    "Warnung",
                    "Keine Punkte liegen innerhalb der ausgewählten Grenze. "
                    "Möchten Sie trotzdem fortfahren?",
                    QMessageBox.Yes | QMessageBox.No,
                    QMessageBox.No
                )
                if reply == QMessageBox.No:
                    return False
            
        return True
# DAS PASSIERT WENN MAN OK DRÜCKT 
    def accept(self):
        """Handle OK button click."""
        if not self.validate_inputs():
            return
            
        try:
            # Get and save parameters
            params = self.get_parameters()
            self.save_settings()  # This will save all current UI values
            
            # Store parameters for plugin to use
            if self.plugin:
                self.plugin.last_parameters = params
            
            # Accept dialog
            super().accept()
            
        except Exception as e:
            QMessageBox.critical(
                self,
                "Fehler",
                f"Fehler bei der Interpolation: {str(e)}"
            )

    def show_variogram_analysis(self):
        """Show variogram analysis dialog with current parameters."""
        try:
            # Get current parameters
            params = self.get_kriging_parameters()
            if not params:
                return
                
            # Get input data
            layer = self.mMapLayerComboBox.currentLayer()
            field = self.mFieldComboBox.currentField()
            boundary = self.mMapLayerComboBox_boundary.currentLayer()
            
            # Prepare data
            x, y, z = self.plugin.prepare_data(layer, field, boundary)
            if x is None or len(x) == 0:
                QgsMessageLog.logMessage(
                    "No valid data points found for variogram analysis",
                    "I-PlugIn",
                    Qgis.Warning
                )
                return
                
            # Analyze variogram
            results = self.plugin.analyze_variogram(x, y, z, params)
            if not results:
                return
                
            # Update dialog with optimized parameters
            self.update_variogram_parameters({
                'nugget': results['parameters']['nugget'],
                'range': results['parameters']['range'],
                'sill': results['parameters']['sill'],
                'metrics': results['metrics']
            }, point_tab=False)
                
            # Show dialog
            dialog = VariogramDialog(self)
            dialog.display_results(results['plot_path'], results['metrics'])
            dialog.exec_()
            
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Failed to show variogram analysis: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )

    def update_ui_state(self):
        """Update UI state based on current selections."""
        try:
            # Check if we have valid input data
            has_valid_inputs = bool(
                self.mMapLayerComboBox.currentLayer() is not None and
                self.mFieldComboBox.currentField() and
                self.comboBox_variogram.currentText() != ''
            )
            
            # Enable analyze button if we have valid inputs
            self.analyze_variogram_button.setEnabled(has_valid_inputs)

            # Enable analyze button for point interpolation if valid
            has_valid_point_inputs = bool(
                self.mMapLayerComboBox_covariate_point.currentLayer() is not None and
                self.mFieldComboBox_covariate.currentField() and
                self.comboBox_variogram_point.currentText() != ''
            )
            self.analyze_variogram_button_points.setEnabled(has_valid_point_inputs)

            # Enable parameter inputs if we have valid inputs
            self.doubleSpinBox_nugget.setEnabled(has_valid_inputs)
            self.doubleSpinBox_range.setEnabled(has_valid_inputs)
            self.doubleSpinBox_sill.setEnabled(has_valid_inputs)
            # Enable parameter inputs for point interpolation if we have valid inputs
            self.doubleSpinBox_nugget_point.setEnabled(has_valid_point_inputs)
            self.doubleSpinBox_range_point.setEnabled(has_valid_point_inputs)
            self.doubleSpinBox_sill_point.setEnabled(has_valid_point_inputs)
            
            # Validate parameters if we have valid inputs
            if has_valid_inputs:
                self.validate_variogram_parameters()
                
        except Exception as e:
            QgsMessageLog.logMessage(
                f"UI state update failed: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )

    def validate_variogram_parameters(self):
        """Validate variogram parameters and update UI state."""
        try:
            nugget = self.doubleSpinBox_nugget.value()
            sill = self.doubleSpinBox_sill.value()
            range_ = self.doubleSpinBox_range.value()
            
            # Warn if parameters might be suboptimal
            warnings = []
            
            if nugget < 0:
                warnings.append("Nugget sollte nicht negativ sein")
            
            if range_ <= 0:
                warnings.append("Range sollte größer als 0 sein")
            
            if sill <= 0:
                warnings.append("Sill sollte größer als 0 sein")
            
            if nugget > sill:
                warnings.append("Nugget sollte nicht größer als Sill sein")
            
            # Show warnings if any
            if warnings:
                warning_text = "\n".join(warnings)
                QgsMessageLog.logMessage(
                    f"Variogram Parameter Warnings:\n{warning_text}",
                    "I-PlugIn",
                    Qgis.Warning
                )
            
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Parameter validation failed: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )

    def update_variogram_parameters(self, parameters, point_tab=False):
        """Update variogram parameters in the UI (raster or point tab, strictly separated)."""
        try:
            if not parameters:
                return

            if point_tab:
                # Update only point tab widgets
                self.doubleSpinBox_nugget_point.setValue(parameters.get('nugget', 0.0))
                self.doubleSpinBox_range_point.setValue(parameters.get('range', 100.0))
                self.doubleSpinBox_sill_point.setValue(parameters.get('sill', 1.0))
                # Use a dedicated metrics label for the point tab
                if not hasattr(self, 'metrics_label_points'):
                    parent_widget = self.page_kriging_2 if hasattr(self, 'page_kriging_2') else self
                    self.metrics_label_points = QtWidgets.QLabel(parent_widget)
                    layout = parent_widget.layout()
                    if not layout:
                        layout = QtWidgets.QVBoxLayout(parent_widget)
                        parent_widget.setLayout(layout)
                    layout.addWidget(self.metrics_label_points)
                metrics_label = self.metrics_label_points
            else:
                # Update only raster tab widgets
                self.doubleSpinBox_nugget.setValue(parameters.get('nugget', 0.0))
                self.doubleSpinBox_range.setValue(parameters.get('range', 100.0))
                self.doubleSpinBox_sill.setValue(parameters.get('sill', 1.0))
                # Use a dedicated metrics label for the raster tab
                if not hasattr(self, 'metrics_label_raster'):
                    parent_widget = self.page_kriging if hasattr(self, 'page_kriging') else self
                    self.metrics_label_raster = QtWidgets.QLabel(parent_widget)
                    layout = parent_widget.layout()
                    if not layout:
                        layout = QtWidgets.QVBoxLayout(parent_widget)
                        parent_widget.setLayout(layout)
                    layout.addWidget(self.metrics_label_raster)
                metrics_label = self.metrics_label_raster

            # Update metrics display only in the correct tab
            metrics = parameters.get('metrics', {})
            if metrics:
                metrics_text = (
                    f"<b>Variogramm Metriken:</b><br>"
                    f"RMSE: {metrics.get('rmse', 'N/A'):.3f}<br>"
                    f"R²: {metrics.get('r2', 'N/A'):.3f}"
                )
                metrics_label.setText(metrics_text)
                metrics_label.setVisible(True)
            else:
                metrics_label.setVisible(False)

        except Exception as e:
            QgsMessageLog.logMessage(
                f"Failed to update variogram parameters: {str(e)}",
                "I-PlugIn",
                Qgis.Critical
            )
