# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IPlugIn
                                 A QGIS plugin
 Plugin to perform interpolation task for onfarm research module
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lucas Johannsen
        email                : lucas.johannsen@fh-kiel.de
 ***************************************************************************/

 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
import json
from datetime import datetime
from pathlib import Path
import numpy as np
from osgeo import gdal
import matplotlib.pyplot as plt

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QProgressDialog
from qgis.core import (
    QgsMessageLog,
    QgsProject,
    QgsVectorLayer,
    QgsRasterLayer,
    QgsCoordinateReferenceSystem,
    QgsVectorFileWriter,
    QgsRasterFileWriter,
    QgsCoordinateTransform,
    QgsPointXY,
    QgsProcessingFeedback,
    Qgis,
    QgsFeature, 
    QgsField, 
    QgsGeometry, 
    QgsWkbTypes,
    QgsVectorDataProvider,
    QgsSingleBandPseudoColorRenderer,
    QgsColorRampShader,
    QgsRasterShader,
    QgsGradientColorRamp,
    QgsGradientStop,
    QgsGraduatedSymbolRenderer,
    QgsRendererRange,
    QgsMarkerSymbol
)
from qgis.PyQt.QtGui import QColor
from pykrige import OrdinaryKriging
import processing

from .i_plugin_dialog import IPlugInDialog
from .variogram_models import (
    VARIOGRAM_MODELS,
    optimize_variogram_parameters,
)
from .variogram_plotter import VariogramPlotter

# Initialize Qt resources from file resources.py
from . import resources
from .config import InterpolationConfig
from .exceptions import (
    InterpolationError,
    DataValidationError,
    GeometryError,
    CoordinateSystemError,
    InterpolationCalculationError,
    OutputError
)

INTERPOLATION_LIBS_AVAILABLE = True


class IPlugIn:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IPlugIn_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&OFR 3. Kartenerzeugen und Datensätze anreichern')
        self.dlg = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('IPlugIn', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True,
                  add_to_menu=True, add_to_toolbar=True, status_tip=None,
                  whats_this=None, parent=None):
        """Add a toolbar icon to the toolbar."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        
        # Check if required libraries are available
        if not INTERPOLATION_LIBS_AVAILABLE:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Missing Dependencies",
                "Some required libraries are missing. Please install:\n"
                "- pykrige\n"
                "Using pip or your package manager."
            )

        icon_path = f'{self.plugin_dir}/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'OFR I Interpolation'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&I-PlugIn'),
                action)
            self.iface.removeToolBarIcon(action)

    # ==================== HELPER FUNCTIONS ====================
    
    def is_utm_crs(self, crs):
        """Prüft ob ein CRS ein UTM-Koordinatensystem ist.
        
        Args:
            crs (QgsCoordinateReferenceSystem): Das zu prüfende CRS
            
        Returns:
            bool: True wenn CRS ein UTM-System ist (EPSG:326xx oder EPSG:327xx)
        """
        if not crs or not crs.isValid():
            return False
        auth_id = crs.authid()
        return auth_id.startswith('EPSG:326') or auth_id.startswith('EPSG:327')
    
    def log(self, message, level=Qgis.Info):
        """Vereinfachtes Logging für das Plugin.
        
        Args:
            message (str): Die Log-Nachricht
            level (Qgis.MessageLevel): Log-Level (Info, Warning, Critical, Success)
        """
        QgsMessageLog.logMessage(message, "I-PlugIn", level)
    
    # ==================== DATA HANDLING ====================

    def get_field_value(self, feature, field_name):
        """Safely get numeric value from field, handling QVariant types."""
        value = feature[field_name]
        
        # Handle NULL or None values
        if value is None:
            return None
            
        # Handle QVariant values
        if isinstance(value, QVariant):
            if value.isNull():
                return None
            # Convert QVariant to Python type
            try:
                if value.type() == QVariant.String:
                    return float(value.toString())
                else:
                    return float(value.toDouble()[0])
            except (ValueError, TypeError, AttributeError):
                return None
                
        # Handle direct numeric values
        try:
            return float(value)
        except (ValueError, TypeError):
            return None
# LAYER AUF GEOMETRY ÜBERPRÜFEN UND DIE GEOM RETURN
    def get_valid_geometry(self, feature):
        """Überprüft und validiert die Geometrie eines Features.
        
        Diese Methode führt mehrere Prüfungen durch:
        1. Prüft ob das Feature überhaupt eine Geometrie hat
        2. Prüft ob die Geometrie nicht None ist
        3. Versucht ungültige Geometrien zu reparieren
        
        Args:
            feature (QgsFeature): Das zu prüfende Feature
            
        Returns:
            QgsGeometry or None: Die validierte Geometrie oder None wenn die Geometrie
                                ungültig ist und nicht repariert werden konnte
        
        Logs:
            Info: Wenn Feature keine Geometrie hat
            Info: Wenn Geometrie None ist
            Info: Original Geometrie-Typ
            Info: Wenn Reparatur versucht wird
            Warning: Wenn Reparatur fehlschlägt
        """
        if not feature.hasGeometry():
            self.log("Feature has no geometry")
            return None
            
        geom = feature.geometry()
        if not geom:
            self.log("Geometry is None")
            return None
            
        self.log(f"Original geometry type: {geom.wkbType()}")
        
        # Try to fix any invalid geometries
        if not geom.isGeosValid():
            self.log("Invalid geometry, attempting to fix")
            geom = geom.makeValid()
            if not geom.isGeosValid():
                self.log("Failed to fix invalid geometry", Qgis.Warning)
                return None
                
        return geom
        
    def convert_to_utm(self, layer):
        """Konvertiert einen Layer in das passende UTM-Koordinatensystem.
        
        Diese Methode führt folgende Schritte durch:
        1. Prüft ob der Layer bereits in UTM ist (EPSG:326xx oder EPSG:327xx)
        2. Prüft ob bereits ein konvertierter Layer im Projekt existiert
        3. Berechnet den Mittelpunkt des Layers und die passende UTM-Zone
        4. Erstellt einen neuen Layer mit eindeutigem Dateinamen
        
        Args:
            layer (QgsVectorLayer): Der zu konvertierende Layer
            
        Returns:
            QgsVectorLayer: Der konvertierte Layer im UTM-Format oder der originale Layer,
                           wenn dieser bereits in UTM ist
            
        Raises:
            CoordinateSystemError: Wenn die Konvertierung fehlschlägt
            
        Notes:
            - Prüft auf existierende UTM-Layer im Projekt (vermeidet Duplikate)
            - Generiert eindeutige Dateinamen bei Konflikten
            - Der neue Layer wird automatisch dem Projekt hinzugefügt
            - Der Dateiname des neuen Layers beginnt mit 'UTM_'
            - Für die Nord-/Südhalbkugel werden die EPSG-Codes 326xx/327xx verwendet
        """
        source_crs = layer.crs()
        
        # Check if already in UTM
        if self.is_utm_crs(source_crs):
            self.log(f"Layer '{layer.name()}' ist bereits in UTM ({source_crs.authid()})")
            return layer
        
        # Calculate target UTM zone first
        extent = layer.extent()
        center_x = (extent.xMinimum() + extent.xMaximum()) / 2
        center_y = (extent.yMinimum() + extent.yMaximum()) / 2

        # Transform center to WGS84
        wgs84_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        transformer = QgsCoordinateTransform(source_crs, wgs84_crs, QgsProject.instance())
        center_point_wgs84 = transformer.transform(QgsPointXY(center_x, center_y))
        lon = center_point_wgs84.x()
        lat = center_point_wgs84.y()

        # Calculate UTM zone
        utm_zone = int((lon + 180) / 6) + 1
        target_epsg = 32600 + utm_zone if lat >= 0 else 32700 + utm_zone
        target_crs = QgsCoordinateReferenceSystem(f"EPSG:{target_epsg}")
        
        # Check if a UTM-converted layer already exists in the project
        new_layer_name = InterpolationConfig.UTM_LAYER_PREFIX + layer.name()
        project = QgsProject.instance()
        
        for existing_layer in project.mapLayers().values():
            # Prüfe ob Layer mit gleichem Namen und passendem UTM-CRS existiert
            if (existing_layer.name() == new_layer_name and 
                isinstance(existing_layer, QgsVectorLayer) and
                existing_layer.crs().authid() == target_crs.authid()):
                
                self.log(
                    f"UTM-Layer '{new_layer_name}' existiert bereits im Projekt "
                    f"mit CRS {target_crs.authid()}. Verwende existierenden Layer.",
                    Qgis.Info
                )
                return existing_layer
        
        # Get project directory or home directory as fallback
        project_file = project.fileName()
        if project_file:
            project_dir = Path(os.path.dirname(project_file))
        else:
            project_dir = Path(os.path.expanduser("~"))
            
        # Ensure output directory exists
        project_dir.mkdir(parents=True, exist_ok=True)

        # Generate unique output path to avoid file conflicts
        base_output_path = project_dir / f"{new_layer_name}.shp"
        output_path = base_output_path
        counter = 1
        
        # Check if file already exists and generate unique name
        while output_path.exists():
            self.log(
                f"Datei '{output_path}' existiert bereits. Generiere eindeutigen Namen.",
                Qgis.Warning
            )
            output_path = project_dir / f"{new_layer_name}_{counter}.shp"
            counter += 1
        
        output_path_str = str(output_path)
        self.log(f"Erstelle neuen UTM-Layer: {output_path_str}")

        # Reproject layer
        params = {
            'INPUT': layer,
            'TARGET_CRS': target_crs,
            'OUTPUT': output_path_str
        }
        
        try:
            feedback = QgsProcessingFeedback()
            result = processing.run("native:reprojectlayer", params, feedback=feedback)
        except Exception as e:
            self.log(f"Fehler bei der UTM-Konvertierung: {str(e)}", Qgis.Critical)
            raise CoordinateSystemError(
                f"Die UTM-Konvertierung für Layer '{layer.name()}' ist fehlgeschlagen: {str(e)}"
            )

        # Load and verify new layer
        # Use the layer name without counter suffix for display
        display_name = new_layer_name if counter == 1 else f"{new_layer_name}_{counter-1}"
        new_layer = QgsVectorLayer(result['OUTPUT'], display_name, "ogr")
        
        if not new_layer.isValid():
            self.log("Failed to create UTM layer", Qgis.Critical)
            raise CoordinateSystemError(
                f"Der erstellte UTM-Layer für '{layer.name()}' ist ungültig."
            )

        # Add to project and return
        project.addMapLayer(new_layer)
        self.log(
            f"UTM-Layer '{display_name}' erfolgreich erstellt "
            f"(CRS: {target_crs.authid()}, Datei: {output_path.name})",
            Qgis.Success
        )
        return new_layer
# DIE BOUNDARY POLYGONS ÜBERPRÜFEN UND RETURN 
    def combine_boundary_geometries(self, boundary_layer):
        """Kombiniert alle gültigen Polygon-Geometrien eines Boundary-Layers zu einer einzigen Geometrie.
        
        Diese Methode verarbeitet sowohl Einzel- als auch Multipart-Geometrien:
        1. Prüft jeden Feature auf gültige Geometrie
        2. Bei Multipart-Geometrien:
           - Zerlegt sie in ihre Einzelteile
           - Verarbeitet jedes Teil einzeln
        3. Bei Einzelgeometrien:
           - Fügt sie direkt zur Gesamtgeometrie hinzu
        4. Kombiniert alle gültigen Teile zu einer Gesamtgeometrie
        
        Args:
            boundary_layer (QgsVectorLayer): Der Layer mit den zu kombinierenden Polygonen
            
        Returns:
            QgsGeometry or None: Die kombinierte Geometrie aller gültigen Polygone oder
                                None wenn keine gültigen Geometrien gefunden wurden
        
        Logs:
            Info: Wenn kein Layer übergeben wurde
            Info: Anzahl der Features im Layer
            Info: Ungültige Geometrien in Features
            Info: Verarbeitung von Multi/Single-Part Geometrien
            Warning: Fehler beim Kombinieren oder Verarbeiten von Geometrien
        
        Notes:
            - Ungültige Geometrien werden übersprungen
            - Bei Fehlern beim Kombinieren wird der Prozess fortgesetzt
            - Unterstützt nur Polygon-Geometrien
        """
        if not boundary_layer:
            self.log("No boundary layer provided")
            return None
            
        self.log(f"Processing boundary layer with {boundary_layer.featureCount()} features")
        
        boundary_geom = None
        for feature in boundary_layer.getFeatures():
            geom = self.get_valid_geometry(feature)
            if not geom:
                self.log("Invalid geometry in boundary feature")
                continue
                
            # Handle different geometry types
            if geom.isMultipart():
                self.log("Processing multipart geometry")
                try:
                    if geom.type() == QgsWkbTypes.PolygonGeometry:
                        parts = geom.asMultiPolygon()
                    else:
                        self.log(f"Unexpected geometry type: {geom.type()}")
                        continue
                        
                    for part in parts:
                        part_geom = QgsGeometry.fromPolygonXY(part)
                        if not part_geom or not part_geom.isGeosValid():
                            self.log("Invalid part geometry")
                            continue
                            
                        if boundary_geom is None:
                            boundary_geom = part_geom
                        else:
                            try:
                                boundary_geom = boundary_geom.combine(part_geom)
                            except (RuntimeError, ValueError, TypeError) as e:
                                self.log(f"Error combining geometries: {str(e)}", Qgis.Warning)
                                continue
                            except Exception as e:
                                # Unerwarteter Fehler - sollte nicht ignoriert werden
                                self.log(f"Unexpected error combining geometries: {str(e)}", Qgis.Critical)
                                raise
                except (RuntimeError, ValueError, TypeError, AttributeError) as e:
                    self.log(f"Error processing multipart geometry: {str(e)}", Qgis.Warning)
                    continue
                except Exception as e:
                    # Unerwarteter Fehler
                    self.log(f"Unexpected error in multipart geometry: {str(e)}", Qgis.Critical)
                    raise
            else:
                self.log("Processing single part geometry")
                if boundary_geom is None:
                    boundary_geom = geom
                else:
                    try:
                        boundary_geom = boundary_geom.combine(geom)
                    except (RuntimeError, ValueError, TypeError) as e:
                        self.log(f"Error combining geometries: {str(e)}", Qgis.Warning)
                        continue
                    except Exception as e:
                        # Unerwarteter Fehler
                        self.log(f"Unexpected error combining geometries: {str(e)}", Qgis.Critical)
                        raise
                    
        if not boundary_geom:
            self.log("No valid boundary geometry created", Qgis.Warning)
            raise GeometryError(
                f"Der Grenzlayer '{boundary_layer.name()}' enthält keine gültigen Polygone. "
                "Bitte überprüfen Sie die Geometrien im Layer."
            )
            
        # Try to fix any invalid geometries after combining
        if not boundary_geom.isGeosValid():
            self.log("Combined geometry is invalid, attempting to fix")
            boundary_geom = boundary_geom.makeValid()
            if not boundary_geom.isGeosValid():
                self.log("Failed to fix combined geometry", Qgis.Warning)
                raise GeometryError(
                    f"Die kombinierten Grenzpolygone im Layer '{boundary_layer.name()}' sind ungültig. "
                    "Bitte überprüfen Sie die Geometrien im Layer."
                )
            
        self.log("Successfully created valid boundary geometry")
        return boundary_geom
# CHECKS DIE DATEN DIE EINGEBEN WERDEN OB SIE IN DER BOUNDARY LIEGEN
    def validate_input_data(self, layer, field_name=None, boundary_layer=None):
        """Validiert die Eingabedaten für die Interpolation.
        
        Führt umfangreiche Prüfungen der Eingabedaten durch:
        1. Layer-Prüfungen:
           - Existenz von Features
           - Gültiges Koordinatensystem (UTM)
           - Automatische UTM-Konvertierung bei Bedarf
        2. Feld-Prüfungen (optional):
           - Existenz gültiger numerischer Werte (nur wenn field_name gesetzt)
        3. Boundary-Prüfungen (optional):
           - Gültigkeit der Geometrien
           - UTM-Konvertierung wenn nötig
           - Lage der Punkte innerhalb der Boundary
        
        Args:
            layer (QgsVectorLayer): Der zu prüfende Eingabe-Layer
            field_name (str, optional): Name des Feldes mit den zu interpolierenden Werten (optional)
            boundary_layer (QgsVectorLayer, optional): Layer mit Begrenzungspolygonen
            
        Returns:
            None: Diese Funktion gibt nichts zurück. Sie wird nur für ihre Seiteneffekte
                  (Validierung und Exception-Throwing) verwendet.
            
        Raises:
            ValueError: Bei ungültigen Eingabedaten mit erklärender Nachricht:
                       - Keine Features im Layer
                       - Keine gültigen Werte im Feld
                       - UTM-Konvertierung fehlgeschlagen
                       - Ungültige Boundary-Geometrien
        
        Notes:
            - Bietet interaktive UTM-Konvertierung mit Benutzerabfrage
            - Prüft auch auf NaN-Werte im Zielfeld (nur wenn field_name gesetzt)
            - Boundary-Layer ist optional
            - Wenn field_name nicht gesetzt ist, werden nur Layer- und Boundary-Prüfungen durchgeführt
        """
        # Check if layer has features
        if layer.featureCount() == 0:
            raise DataValidationError(
                f"Der Eingabelayer '{layer.name()}' enthält keine Punkte. "
                "Bitte wählen Sie einen Layer mit Punktdaten aus."
            )
        
        # Feld-Prüfungen nur wenn field_name gesetzt ist
        if field_name is not None:
            valid_count = 0
            zero_count = 0
            total_count = 0
            for feature in layer.getFeatures():
                total_count += 1
                value = self.get_field_value(feature, field_name)
                if value is not None and not np.isnan(value):
                    valid_count += 1
                    if value == 0:
                        zero_count += 1
            if valid_count == 0:
                raise DataValidationError(
                    f"Das ausgewählte Feld '{field_name}' im Layer '{layer.name()}' enthält keine gültigen Werte. "
                    "Bitte wählen Sie ein Feld mit numerischen Werten aus."
                )
            # Warnung wenn alle oder die meisten Werte Null sind
            if zero_count > 0:
                zero_percentage = (zero_count / valid_count) * 100
                if zero_percentage > InterpolationConfig.ZERO_VALUE_WARNING_THRESHOLD:
                    msg_box = QMessageBox()
                    msg_box.setIcon(QMessageBox.Warning)
                    msg_box.setText(f"Warnung: {zero_percentage:.1f}% der Werte sind Null")
                    msg_box.setInformativeText(
                        f"Von {valid_count} gültigen Werten sind {zero_count} Null-Werte.\n"
                        "Dies könnte zu Problemen bei der Interpolation führen."
                    )
                    msg_box.setStandardButtons(QMessageBox.Ok)
                    msg_box.exec_()
        
        # Check if layer is in UTM coordinate system
        if not self.is_utm_crs(layer.crs()):
            msg_box = QMessageBox()
            msg_box.setIcon(QMessageBox.Question)
            msg_box.setText("Der Layer ist nicht im UTM-Format.")
            msg_box.setInformativeText("Soll der Layer automatisch in das passende UTM-Format konvertiert werden?")
            msg_box.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
            msg_box.setDefaultButton(QMessageBox.Yes)
            
            if msg_box.exec_() == QMessageBox.Yes:
                utm_layer = self.convert_to_utm(layer)
                if utm_layer:
                    layer = utm_layer
                else:
                    raise CoordinateSystemError(
                        f"Die UTM-Konvertierung für Layer '{layer.name()}' ist fehlgeschlagen."
                    )
            else:
                self.log(
                    "Benutzer hat UTM-Konvertierung abgelehnt. Fahre mit originalem CRS fort.",
                    Qgis.Warning
                )
        
        # If boundary layer is specified, check if points fall within it and convert to UTM if needed
        if boundary_layer:
            if not self.is_utm_crs(boundary_layer.crs()):
                utm_boundary = self.convert_to_utm(boundary_layer)
                if utm_boundary:
                    boundary_layer = utm_boundary
                else:
                    raise CoordinateSystemError(
                        f"Die UTM-Konvertierung des Boundary-Layers '{boundary_layer.name()}' ist fehlgeschlagen."
                    )
        if boundary_layer:
            if boundary_layer.featureCount() == 0:
                raise DataValidationError(
                    f"Der Grenzlayer '{boundary_layer.name()}' enthält keine Features. "
                    "Bitte wählen Sie einen Layer mit Polygonen aus."
                )
                
            # Get first valid boundary geometry
            boundary_geom = None
            for feature in boundary_layer.getFeatures():
                geom = feature.geometry()
                if geom and geom.isGeosValid():
                    boundary_geom = geom
                    break
                    
            if not boundary_geom:
                raise GeometryError(
                    f"Der Grenzlayer '{boundary_layer.name()}' enthält keine gültigen Polygone. "
                    "Bitte überprüfen Sie die Geometrien im Layer."
                )
                
            # Check points against boundary
            points_within = 0
            for feature in layer.getFeatures():
                geom = feature.geometry()
                if not geom:
                    continue
                    
                if geom.within(boundary_geom):
                    points_within += 1
                    
            if points_within == 0:
                raise GeometryError(
                    f"Keine Punkte aus Layer '{layer.name()}' liegen innerhalb der Grenze '{boundary_layer.name()}'. "
                    "Bitte überprüfen Sie die Lage der Punkte und die Grenze."
                )
                
            self.log(f"{points_within} Punkte liegen innerhalb der Grenze")
        
        # Validation erfolgreich - keine Rückgabe nötig (wird nur für Seiteneffekte verwendet)


################################ Interpolation beginnt #####################################################################        
# ERSTELLT NUMPY ARRAYS UM DIE DATEN FÜRS KRIGING VORZUBEREITEN
    def prepare_data(self, layer, field_name, boundary_layer=None):
        """Bereitet die Vektordaten für die Kriging-Interpolation vor.
        
        Transformiert die Eingabedaten in das für Kriging benötigte Format:
        1. Validierung der Eingabedaten:
           - Prüft Layer und Feldwerte
           - Prüft UTM-Koordinatensystem
           - Prüft Boundary wenn vorhanden
        2. Extraktion der Daten:
           - Koordinaten (x, y) aus den Geometrien
           - Werte (z) aus dem spezifizierten Feld
        3. Filterung der Daten:
           - Nur gültige Geometrien
           - Nur Punkte innerhalb der Boundary (wenn vorhanden)
           - Nur nicht-None und nicht-NaN Werte
        
        Args:
            layer (QgsVectorLayer): Layer mit den Punktdaten
            field_name (str): Name des Feldes mit den zu interpolierenden Werten
            boundary_layer (QgsVectorLayer, optional): Layer mit Begrenzungspolygonen
            
        Returns:
            tuple: (x, y, z) - NumPy Arrays mit den Koordinaten und Werten:
                   - x (np.array): X-Koordinaten der Punkte
                   - y (np.array): Y-Koordinaten der Punkte
                   - z (np.array): Zu interpolierende Werte
                   Oder (None, None, None) wenn keine gültigen Daten gefunden wurden
            
        Raises:
            ValueError: Wenn die Validierung fehlschlägt oder keine gültigen Daten
                       gefunden werden
        
        Notes:
            - Loggt die Anzahl der Features in Input- und Boundary-Layer
            - Ungültige Geometrien oder Werte werden stillschweigend übersprungen
            - Boundary-Check ist optional und wird nur durchgeführt wenn boundary_layer
              übergeben wurde
        """
        # Log initial layer states
        self.log(f"Input layer feature count: {layer.featureCount()}")
        if boundary_layer:
            self.log(f"Boundary layer feature count: {boundary_layer.featureCount()}")
        
        # Validate input data
        self.validate_input_data(layer, field_name, boundary_layer)
        
        # Initialize arrays for coordinates and values
        x = []
        y = []
        z = []
        
        # Iterate over features in the input layer
        for feature in layer.getFeatures():
            geom = feature.geometry()
            if not geom or not geom.isGeosValid():
                continue
                
            point = geom.asPoint()
            # Nutze get_field_value für robuste Wert-Erkennung (QVariant/NULL/None)
            value = self.get_field_value(feature, field_name)
        
            # Wenn boundary_layer vorhanden, prüfe ob der Punkt in irgendeiner Parzelle liegt
            if boundary_layer:
                point_geom = QgsGeometry.fromPointXY(point)
                in_boundary = False
                for boundary_feature in boundary_layer.getFeatures():
                    if point_geom.within(boundary_feature.geometry()):
                        in_boundary = True
                        break
                if not in_boundary:
                    continue
        
            # Punkt hinzufügen wenn er valide ist
            if value is None:
                msg = f"Ungültiger Wert (NULL/QVariant) im Feld '{field_name}' für Feature-ID {feature.id()}. Bitte bereinigen Sie Ihre Daten."
                self.log(msg, Qgis.Critical)
                # QMessageBox entfernt - wird später in run() oder Dialog gefangen und angezeigt
                raise DataValidationError(msg)
            x.append(point.x())
            y.append(point.y())
            z.append(float(value))
        
        # Convert lists to numpy arrays
        if len(x) > 0:
            x = np.array(x, dtype=np.float64)
            y = np.array(y, dtype=np.float64)
            z = np.array(z, dtype=np.float64)
            return x, y, z
        
        return None, None, None
# ERSTELLT OUTPUT GRID FÜRS KRIGING ERSTELLT DIE COORDINATES 
    def create_output_grid(self, extent, cell_size, boundary_layer=None):
        """Create output grid for interpolation with exact buffer and full debug logging.
        
        Diese Methode erstellt ein regelmäßiges Grid für die Kriging-Interpolation und
        eine Maske, die definiert, welche Pixel innerhalb der Boundary liegen.
        
        Args:
            extent: QgsRectangle mit der Extent für das Grid
            cell_size: Größe einer Rasterzelle in Metern
            boundary_layer: Optional - Layer mit Polygon-Geometrien zur Maskierung
            
        Returns:
            tuple: (x, y, mask)
                - x: numpy array mit X-Koordinaten der Pixel-Zentren
                - y: numpy array mit Y-Koordinaten der Pixel-Zentren (absteigend sortiert)
                - mask: numpy boolean array - True für Pixel innerhalb der Boundary
                
        Notes:
            - Extent wird an Rasterzellen ausgerichtet (floor/ceil)
            - Buffer wird automatisch hinzugefügt (GRID_BUFFER_MULTIPLIER)
            - Maske verwendet Pixel-Polygone statt Punkte für vollständige Abdeckung
            - Pixel werden eingeschlossen, wenn sie die Boundary überlappen (intersects)
        """
        # --- 1. Extent bestimmen ---
        # Verwende die übergebene Extent (kann bereits erweitert sein)
        x_min = extent.xMinimum()
        x_max = extent.xMaximum()
        y_min = extent.yMinimum()
        y_max = extent.yMaximum()

        # --- 2. Extent an Rasterzellen ausrichten ---
        x_min = np.floor(x_min / cell_size) * cell_size
        x_max = np.ceil(x_max / cell_size) * cell_size
        y_min = np.floor(y_min / cell_size) * cell_size
        y_max = np.ceil(y_max / cell_size) * cell_size

        # --- 3. Boundary um cell_size erweitern (zusätzlicher Buffer) ---
        expand = cell_size * InterpolationConfig.GRID_BUFFER_MULTIPLIER
        x_start = x_min - expand
        x_end   = x_max + expand
        y_start = y_min - expand
        y_end   = y_max + expand
        self.log(
            f"Boundary-Extent erweitert: xmin={x_start}, xmax={x_end}, ymin={y_start}, ymax={y_end}"
        )

        # --- 4. Grid erzeugen ---
        nx = int(round((x_end - x_start) / cell_size))
        ny = int(round((y_end - y_start) / cell_size))
        x = np.arange(x_start, x_end + cell_size * InterpolationConfig.GRID_ARANGE_OFFSET, cell_size)
        y = np.arange(y_start, y_end + cell_size * InterpolationConfig.GRID_ARANGE_OFFSET, cell_size)
        x = np.sort(x)
        y = np.sort(y)[::-1]

        # --- 5. Logging aller relevanten Werte ---
        self.log(f"Boundary-Extent: xmin={x_min}, xmax={x_max}, ymin={y_min}, ymax={y_max}")
        self.log(f"Grid-Buffer: {expand} Zellen pro Seite, cell_size={cell_size}")
        self.log(f"Grid X: x[0]={x[0]}, x[-1]={x[-1]}, len={len(x)}")
        self.log(f"Grid Y: y[0]={y[0]}, y[-1]={y[-1]}, len={len(y)}")
        self.log(f"Grid Shape: ({len(y)}, {len(x)})")

        # --- 6. Maskenarray erzeugen (optional) ---
        mask = None
        if boundary_layer:
            xx, yy = np.meshgrid(x, y)
            mask = np.zeros((len(y), len(x)), dtype=bool)
            
            # Erstelle Pixel-Polygone statt nur Punkte für bessere Abdeckung
            half_cell = cell_size / 2.0
            
            for i in range(len(y)):
                for j in range(len(x)):
                    # Erstelle ein Pixel-Polygon (Quadrat um das Pixel-Zentrum)
                    px = xx[i, j]
                    py = yy[i, j]
                    pixel_polygon = QgsGeometry.fromPolygonXY([[
                        QgsPointXY(px - half_cell, py - half_cell),
                        QgsPointXY(px + half_cell, py - half_cell),
                        QgsPointXY(px + half_cell, py + half_cell),
                        QgsPointXY(px - half_cell, py + half_cell),
                        QgsPointXY(px - half_cell, py - half_cell)
                    ]])
                    
                    for feature in boundary_layer.getFeatures():
                        geom = feature.geometry()
                        if geom and geom.isGeosValid():
                            # Pixel ist "drin" wenn es die Boundary überlappt oder berührt
                            if pixel_polygon.intersects(geom):
                                mask[i, j] = True
                                break
            self.log(f"Mask Shape: {mask.shape}")

        return x, y, mask

# ANALYSIERT DAWS VARIOGRAM UND OPTIMIERT DIE PARAMETER RETURNS DICT MIT PARAMETERN
    def calculate_optimal_lags(self, x, y):
        """Calculate optimal number of lags based on data distribution.
        
        Args:
            x, y: Koordinaten der Messpunkte
            
        Returns:
            nlags: Optimale Anzahl der Lags
            max_dist: Maximale Distanz für die Variogrammanalyse
        """
        # Berechne alle paarweisen Distanzen
        distances = []
        n_points = len(x)
        
        for i in range(n_points):
            for j in range(i + 1, n_points):
                dist = np.sqrt((x[i] - x[j])**2 + (y[i] - y[j])**2)
                distances.append(dist)
        
        distances = np.array(distances)
        
        # Berechne Statistiken
        max_dist = np.percentile(distances, InterpolationConfig.DISTANCE_PERCENTILE)
        n_pairs = len(distances)
        
        # Empirische Regeln für die Anzahl der Lags:
        # 1. Quadratwurzel-Regel (oft verwendet in der Histogramm-Analyse)
        n_bins_sqrt = int(np.sqrt(n_pairs))
        
        # 2. Rice-Regel (Alternative zu Sturges, besser für nicht-normale Verteilungen)
        n_bins_rice = int(np.ceil(2 * n_pairs**(1/3)))
        
        # 3. Mindestens 30 Paare pro Lag für statistische Stabilität
        min_pairs_per_lag = InterpolationConfig.MIN_PAIRS_PER_LAG
        max_lags = n_pairs // min_pairs_per_lag
        
        # Wähle die kleinste Anzahl von Lags, die alle Kriterien erfüllt
        nlags = min(n_bins_sqrt, n_bins_rice, max_lags)
        
        # Stelle sicher, dass wir mindestens MIN_LAGS haben
        nlags = max(InterpolationConfig.MIN_LAGS, nlags)
        
        # Logging für Debugging
        self.log(
            f"Variogram Stats:\n"
            f"Pairs: {n_pairs}\n"
            f"Sqrt Bins: {n_bins_sqrt}, Rice Bins: {n_bins_rice}\n"
            f"Max Lags (30 pairs): {max_lags}\n"
            f"Selected Lags: {nlags}\n"
            f"Max Distance: {max_dist:.1f}"
        )
        
        return nlags, max_dist
    
    def analyze_variogram(self, x, y, z, params):
        """Analyze variogram and generate visualization.
        
        Args:
            x, y: Koordinaten der Messpunkte
            z: Messwerte
            params: Dictionary mit Variogramm-Parametern
                - variogram_model: Typ des Variogramm-Modells
                - nugget: Initialer Nugget-Effekt (optional)
                - range: Initiale Range (optional)
                - sill: Initialer Sill (optional)
        
        Returns:
            Dictionary mit:
                - metrics: Anpassungsgüte (RMSE, R², AIC)
                - parameters: Optimierte Parameter (nugget, range, sill)
                - experimental: Experimentelles Variogramm
                - model: Theoretisches Variogramm
                - plot_path: Pfad zur Variogramm-Visualisierung
        """
        try:
            # Prüfe auf ungültige Werte (None, QVariant, NaN) und breche ggf. mit Fehlermeldung ab
            from qgis.PyQt.QtCore import QVariant
            for xi, yi, zi in zip(x, y, z):
                if xi is None or yi is None or zi is None:
                    raise DataValidationError("Die Daten enthalten ungültige Werte (NULL/leer). Bitte bereinigen Sie Ihre Daten.")
                if isinstance(xi, QVariant) and xi.isNull():
                    raise DataValidationError("Die Daten enthalten ungültige Werte (QVariant/leer). Bitte bereinigen Sie Ihre Daten.")
                if isinstance(yi, QVariant) and yi.isNull():
                    raise DataValidationError("Die Daten enthalten ungültige Werte (QVariant/leer). Bitte bereinigen Sie Ihre Daten.")
                if isinstance(zi, QVariant) and zi.isNull():
                    raise DataValidationError("Die Daten enthalten ungültige Werte (QVariant/leer). Bitte bereinigen Sie Ihre Daten.")
                try:
                    if np.isnan(float(xi)) or np.isnan(float(yi)) or np.isnan(float(zi)):
                        raise DataValidationError("Die Daten enthalten ungültige Werte (NaN). Bitte bereinigen Sie Ihre Daten.")
                except Exception:
                    raise ValueError("Die Daten enthalten ungültige Werte (nicht numerisch). Bitte bereinigen Sie Ihre Daten.")
            # Validiere Eingabedaten
            if len(x) < InterpolationConfig.MIN_POINTS_FOR_VARIOGRAM:
                raise DataValidationError(
                    f"Zu wenige Datenpunkte für eine stabile Variogramm-Analyse. "
                    f"Benötigt: {InterpolationConfig.MIN_POINTS_FOR_VARIOGRAM}, Vorhanden: {len(x)}"
                )
            
            # Konvertiere zu numpy arrays
            x = np.asarray(x, dtype=np.float64)
            y = np.asarray(y, dtype=np.float64)
            z = np.asarray(z, dtype=np.float64)
            
            # Prüfe auf gültiges Variogramm-Modell
            model_type = params.get('variogram_model', 'spherical').lower()
            if model_type not in VARIOGRAM_MODELS:
                raise InterpolationCalculationError(
                    f"Ungültiges Variogramm-Modell: {model_type}. "
                    f"Verfügbare Modelle: {', '.join(VARIOGRAM_MODELS.keys())}"
                )
            
            # Verwende Anzahl der Lags aus UI oder berechne sie
            if 'nlags' in params:
                nlags = params['nlags']
                _, max_dist = self.calculate_optimal_lags(x, y)  # Nur für max_dist
            else:
                nlags, max_dist = self.calculate_optimal_lags(x, y)
            
            # Berechne experimentelles Variogramm
            # Log nlags parameter
            self.log(f"Using {nlags} lags for variogram analysis")
            
            ok = OrdinaryKriging(
                x, y, z,
                variogram_model=model_type,
                nlags=nlags,
                enable_plotting=False,
                coordinates_type='euclidean'
            )
            
            # Setze maximale Distanz für das Variogramm
            ok.variogram_model_parameters = [
                params.get('nugget', 0),
                params.get('sill', np.var(z)),
                min(params.get('range', max_dist), max_dist)
            ]
            
            # Hole experimentelle Variogramm-Daten
            lags = ok.lags
            experimental = ok.semivariance
            
            # Initiale Schätzung der Parameter
            initial_guess = [
                params.get('nugget', 0),  # Nugget sollte nicht negativ sein
                params.get('range', np.median(lags)),  # Range etwa in der Mitte der Distanzen
                params.get('sill', np.max(experimental))  # Sill etwa beim Maximum der Semivarianz
            ]
            
            # Optimiere Parameter
            opt_params, metrics = optimize_variogram_parameters(
                lags, experimental, model_type, initial_guess
            )
            
            # Extrahiere optimierte Parameter
            nugget, range_, sill = opt_params
            
            # Berechne theoretisches Variogramm
            model_func = VARIOGRAM_MODELS[model_type]
            model_values = model_func(lags, nugget, range_, sill)
            
            # Berechne zusätzliche Metriken
            n_params = 3  # Nugget, Range, Sill
            n_points = len(lags)
            mse = metrics['rmse'] ** 2  # MSE aus RMSE berechnen
            aic = n_points * np.log(mse) + 2 * n_params  # Akaike Information Criterion
            metrics['aic'] = aic
            metrics['mse'] = mse  # MSE zu Metriken hinzufügen
            
            # Erstelle Plot im Projekt-Output-Verzeichnis
            plotter = VariogramPlotter()
            output_dir = params.get('output_dir')
            base_name = params.get('base_name', 'variogram')
            if output_dir is None:
                # Fallback: plugin dir
                save_path = os.path.join(self.plugin_dir, f'{base_name}{InterpolationConfig.VARIOGRAM_PLOT_SUFFIX}')
            else:
                save_path = os.path.join(output_dir, f'{base_name}{InterpolationConfig.VARIOGRAM_PLOT_SUFFIX}')
            plotter.plot_variogram(
                lags, experimental,
                model_type,
                nugget, range_, sill,
                title=f'Variogramm-Analyse\nRMSE: {metrics["rmse"]:.3f}, R²: {metrics["r2"]:.3f}, AIC: {aic:.1f}',
                save_path=save_path,
                show=False
            )
            plotter.close()
            
            # Logging der Ergebnisse
            self.log(
                f"Variogram Analysis Results:\n"
                f"Model: {model_type}\n"
                f"Parameters - Nugget: {nugget:.3f}, Range: {range_:.3f}, Sill: {sill:.3f}\n"
                f"Metrics - RMSE: {metrics['rmse']:.3f}, R²: {metrics['r2']:.3f}, AIC: {aic:.1f}"
            )
            
            return {
                'metrics': metrics,
                'parameters': {
                    'nugget': nugget,
                    'range': range_,
                    'sill': sill,
                    'model_type': model_type
                },
                'experimental': {
                    'lags': lags.tolist(),
                    'semivariance': experimental.tolist()
                },
                'model': {
                    'lags': lags.tolist(),
                    'semivariance': model_values.tolist()
                },
                'plot_path': save_path
            }
            
        except Exception as e:
            self.log(f"Variogram analysis failed: {str(e)}", Qgis.Critical)
            import traceback
            self.log(f"Traceback: {traceback.format_exc()}", Qgis.Critical)
            return None
# DIE TATSÄCHLICHE INTERPOLATION MIT POINT LAYER FUNKTION IMPLEMENTIERT RETURNS Z-VALUE FOR GRID OR ADDS COLUMN TO THE DATA
    def interpolate_ordinary_kriging(self, x, y, z, grid_x, grid_y, params, style = 'grid'):
        """Führt die Ordinary Kriging Interpolation durch.
        
        Der Prozess läuft in mehreren Schritten ab:
        1. Variogramm-Analyse:
           - Berechnung und Modellierung des experimentellen Variogramms
           - Optimierung der Variogramm-Parameter
           - Validierung des Modells (RMSE, R²)
        2. Kriging-Interpolation:
           - Verwendung der optimierten Variogramm-Parameter
           - Berechnung der Kriging-Gewichte
           - Interpolation auf dem spezifizierten Grid
        
        Args:
            x (np.array): X-Koordinaten der Messpunkte
            y (np.array): Y-Koordinaten der Messpunkte
            z (np.array): Messwerte an den Punkten
            grid_x (np.array): X-Koordinaten des Interpolationsgrids
            grid_y (np.array): Y-Koordinaten des Interpolationsgrids
            params (dict): Parameter für die Interpolation:
                          - nlags (int): Anzahl der Lag-Klassen
                          - variogram_model (str): Typ des Variogramm-Modells
                          - sill (float, optional): Startwert für Sill
                          - range (float, optional): Startwert für Range
                          - nugget (float, optional): Startwert für Nugget
            
        Returns:
            dict: Interpolationsergebnisse mit:
                 - 'values': Interpolierte Werte auf dem Grid
                 - 'variance': Kriging-Varianz auf dem Grid
                 - 'variogram_info': Details zur Variogramm-Analyse
            oder None bei Fehler
            
        Raises:
            ValueError: Bei fehlgeschlagener Variogramm-Analyse
            
        Notes:
            - Loggt detaillierte Informationen zur Variogramm-Analyse
            - Speichert Variogramm-Parameter für spätere Verwendung
            - Verwendet GSTools für die eigentliche Interpolation
        """
        try:
            # Modellabhängige Variogramm-Parameter
            if params['variogram_model'].lower() == 'linear':
                variogram_params = {
                    "slope": params.get('slope', params.get('range', 1.0)),  # Fallback auf range
                    "nugget": params['nugget'],
                    "nlags": params['nlags']
                }
            else:
                variogram_params = {
                    "sill": params['sill'],
                    "range": params['range'],
                    "nugget": params['nugget'],
                    "nlags": params['nlags']
                }
            
            # Initialize kriging model
            ok = OrdinaryKriging(
                x, y, z,
                variogram_model=params['variogram_model'].lower(),
                variogram_parameters=variogram_params,
                nlags=variogram_params['nlags'],
                enable_plotting=False,
                coordinates_type='euclidean'
            )
            
            # Logging der verwendeten Grid-Koordinaten
            self.log(f"Interpolation Grid X: grid_x[0]={grid_x[0]}, grid_x[-1]={grid_x[-1]}, len={len(grid_x)}")
            self.log(f"Interpolation Grid Y: grid_y[0]={grid_y[0]}, grid_y[-1]={grid_y[-1]}, len={len(grid_y)}")
            # Perform interpolation based on style
            if style == 'grid':
                z_pred, z_std = ok.execute('grid', grid_x, grid_y)
                return z_pred.data
            elif style == 'points':
                z_pred, z_std = ok.execute('points', grid_x, grid_y)
                return z_pred
            else:
                raise InterpolationCalculationError(
                    f"Ungültiger style-Parameter: '{style}'. Muss 'grid' oder 'points' sein."
                )
            
                
        except Exception as e:
            self.log(f"Interpolation failed: {str(e)}", Qgis.Critical)
            import traceback
            self.log(f"Traceback: {traceback.format_exc()}", Qgis.Critical)
            raise
# ERSTELLT EIN RASTERLAYER WELCHES AUS DEN VECTORDATEN EIN RASTER MACHT 
    def create_raster_layer(self, data, extent, cell_size, output_path, crs, mask=None, x=None, y=None):
        """Create and save interpolated raster layer."""
        try:
            # Log input dimensions
            self.log(f"Data shape: {data.shape}, Mask shape: {mask.shape if mask is not None else 'None'}")
            
            # Apply mask if provided
            if mask is not None:
                data = np.where(mask, data, np.nan)
            
            # Use the dimensions from the interpolated data
            height, width = data.shape
            
            # Log dimensions
            self.log(f"Using dimensions from data - Width: {width}, Height: {height}")
            
            # Daten müssen nicht mehr geflippt werden, da y absteigend sortiert ist
            # data = np.flipud(data)
            
            # Create raster layer
            driver = gdal.GetDriverByName('GTiff')
            dataset = driver.Create(
                output_path,
                width,
                height,
                1,
                gdal.GDT_Float32
            )
            
            # --- Anpassung für erweitertes Grid (Buffer) ---
            # x und y werden jetzt explizit übergeben!
            if x is not None and y is not None:
                # Debug-Log: Grid- und Extent-Koordinaten
                self.log(f"Grid X: x[0]={x[0]}, x[-1]={x[-1]}, Y: y[0]={y[0]}, y[-1]={y[-1]}")
                self.log(f"Extent: xmin={extent.xMinimum()}, xmax={extent.xMaximum()}, ymin={extent.yMinimum()}, ymax={extent.yMaximum()}")
                x_origin = x[0] - InterpolationConfig.RASTER_PIXEL_OFFSET * cell_size
                y_origin = y[0] + InterpolationConfig.RASTER_PIXEL_OFFSET * cell_size
                dataset.SetGeoTransform((
                    x_origin,  # x origin
                    cell_size,  # pixel width
                    0,
                    y_origin,  # y origin
                    0,
                    -cell_size  # pixel height
                ))
                self.log(
                    f"Raster-GeoTransform gesetzt auf: x_origin={x_origin}, y_origin={y_origin}, pixel_width={cell_size}, pixel_height={-cell_size}"
                )
            else:
                self.log(
                    "WARNUNG: create_raster_layer wurde ohne explizite Übergabe von x/y aufgerufen! Das Raster kann versetzt sein.",
                    Qgis.Warning
                )
                # Fallback: alte Methode
                dataset.SetGeoTransform((
                    extent.xMinimum(),
                    cell_size,
                    0,
                    extent.yMaximum(),
                    0,
                    -cell_size
                ))
            
            # Set projection
            dataset.SetProjection(crs.toWkt())
            
            # Write data
            band = dataset.GetRasterBand(1)
            band.WriteArray(data)
            band.SetNoDataValue(np.nan)
            
            # Close dataset
            dataset = None
            
            return True
            
        except Exception as e:
            self.log(f"Failed to create raster layer: {str(e)}", Qgis.Critical)
            raise

    def apply_color_ramp_to_raster(self, layer):
        """Wendet eine Farbrampe auf ein Raster-Layer an.
        
        Erstellt eine Red → Yellow → Green Farbrampe basierend auf den Min/Max-Werten des Rasters.
        Diese Methode ist optional - wenn sie fehlschlägt, wird nur geloggt, aber keine Exception geworfen.
        
        Args:
            layer (QgsRasterLayer): Das Raster-Layer, auf das die Farbrampe angewendet werden soll
            
        Returns:
            bool: True bei Erfolg, False bei Fehler
            
        Notes:
            - Fehler werden nur geloggt, nicht geworfen (Styling ist optional)
            - Layer bleibt in Graustufen, wenn Styling fehlschlägt
            - Verwendet automatisch Min/Max-Werte aus Band-Statistiken
        """
        try:
            # Prüfe ob Layer gültig ist
            if not layer or not layer.isValid():
                self.log("Ungültiger Layer für Farbrampe - überspringe Styling", Qgis.Warning)
                return False
            
            # Hole Daten-Provider und Band-Statistiken
            provider = layer.dataProvider()
            stats = provider.bandStatistics(1)  # Band 1
            
            min_val = stats.minimumValue
            max_val = stats.maximumValue
            
            self.log(f"Applying color ramp: min={min_val:.2f}, max={max_val:.2f}")
            
            # Erstelle Renderer mit Pseudo-Color
            renderer = QgsSingleBandPseudoColorRenderer(provider, 1)
            
            # Erstelle Gradient Color Ramp (Red → Orange → Yellow → Light Green → Green)
            # Verwende QGIS Standard RYG-Farben aus config.py mit 5 Stops
            color_ramp = QgsGradientColorRamp(
                QColor(*InterpolationConfig.COLOR_RAMP_START),   # Start: Rot (0%)
                QColor(*InterpolationConfig.COLOR_RAMP_END)      # Ende: Grün (100%)
            )
            # Füge Zwischenstopps hinzu für sanfteren Verlauf
            color_ramp.setStops([
                QgsGradientStop(
                    InterpolationConfig.COLOR_RAMP_STOP_1_POSITION,
                    QColor(*InterpolationConfig.COLOR_RAMP_STOP_1)  # Orange (25%)
                ),
                QgsGradientStop(
                    InterpolationConfig.COLOR_RAMP_MIDDLE_POSITION,
                    QColor(*InterpolationConfig.COLOR_RAMP_MIDDLE)  # Gelb (50%)
                ),
                QgsGradientStop(
                    InterpolationConfig.COLOR_RAMP_STOP_2_POSITION,
                    QColor(*InterpolationConfig.COLOR_RAMP_STOP_2)  # Hellgrün (75%)
                )
            ])
            
            # Erstelle Color Ramp Shader (ohne Parameter im Konstruktor)
            shader = QgsColorRampShader()
            shader.setColorRampType(QgsColorRampShader.Interpolated)
            
            # Klassifiziere manuell mit gleichmäßig verteilten Klassen
            num_classes = InterpolationConfig.COLOR_RAMP_CLASSES
            color_ramp_items = []
            
            for i in range(num_classes):
                fraction = i / (num_classes - 1)
                value = min_val + fraction * (max_val - min_val)
                
                # Hole Farbe aus dem Gradient
                color = color_ramp.color(fraction)
                label = f"{value:.2f}"
                
                color_ramp_items.append(
                    QgsColorRampShader.ColorRampItem(value, color, label)
                )
                
                self.log(f"Class {i+1}: value={value:.2f}, color=RGB({color.red()},{color.green()},{color.blue()})")
            
            shader.setColorRampItemList(color_ramp_items)
            self.log(f"Total color ramp items created: {len(color_ramp_items)}")
            
            # WICHTIG: Setze Min/Max explizit
            shader.setMinimumValue(min_val)
            shader.setMaximumValue(max_val)
            
            # Setze Shader im Renderer
            raster_shader = QgsRasterShader()
            raster_shader.setRasterShaderFunction(shader)
            renderer.setShader(raster_shader)
            
            # Wende Renderer auf Layer an
            layer.setRenderer(renderer)
            layer.triggerRepaint()
            
            self.log("Color ramp applied successfully", Qgis.Success)
            return True
            
        except Exception as e:
            # Styling ist optional - logge nur, werfe keine Exception
            # Das Raster ist bereits erstellt und funktioniert, nur die Farben fehlen
            self.log(
                f"Warnung: Farbrampe konnte nicht angewendet werden: {str(e)}. "
                "Layer wird in Graustufen angezeigt.",
                Qgis.Warning
            )
            import traceback
            self.log(f"Traceback: {traceback.format_exc()}", Qgis.Info)
            return False

    def create_vector_layer_from_grid(self, grid_x, grid_y, interpolated_data, output_path, crs, mask=None, field_name="value"):
        """Erstellt einen Punkt-Vector-Layer aus den interpolierten Grid-Daten.
        
        Args:
            grid_x (np.array): X-Koordinaten des Grids
            grid_y (np.array): Y-Koordinaten des Grids
            interpolated_data (np.array): Interpolierte Werte (2D array)
            output_path (str): Pfad für den Output-Shapefile
            crs (QgsCoordinateReferenceSystem): Koordinatensystem
            mask (np.array): Boolean-Maske - True für Punkte innerhalb Boundary (optional)
            field_name (str): Name des Werte-Feldes (default: "value")
            
        Returns:
            bool: True bei Erfolg, False bei Fehler
            
        Notes:
            - Nur Punkte mit mask[i,j]=True werden exportiert (wenn Maske vorhanden)
            - NaN-Werte werden automatisch übersprungen
        """
        try:
            # Erstelle Memory-Layer
            layer = QgsVectorLayer(f"Point?crs={crs.authid()}", "interpolated_points", "memory")
            provider = layer.dataProvider()
            
            # Füge Felder hinzu
            provider.addAttributes([
                QgsField("x", QVariant.Double),
                QgsField("y", QVariant.Double),
                QgsField(field_name, QVariant.Double)
            ])
            layer.updateFields()
            
            # Erstelle Features aus Grid
            features = []
            for i in range(len(grid_y)):
                for j in range(len(grid_x)):
                    value = interpolated_data[i, j]
                    
                    # Überspringe NaN-Werte (außerhalb Boundary)
                    if np.isnan(value):
                        continue
                    
                    # Überspringe Punkte außerhalb der Boundary (wenn Maske vorhanden)
                    if mask is not None and not mask[i, j]:
                        continue
                    
                    # Erstelle Punkt-Feature
                    feature = QgsFeature()
                    feature.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(grid_x[j], grid_y[i])))
                    feature.setAttributes([grid_x[j], grid_y[i], float(value)])
                    features.append(feature)
            
            # Füge alle Features hinzu
            provider.addFeatures(features)
            layer.updateExtents()
            
            self.log(f"Created vector layer with {len(features)} points")
            
            # Speichere als Shapefile
            error = QgsVectorFileWriter.writeAsVectorFormat(
                layer,
                output_path,
                "UTF-8",
                crs,
                "ESRI Shapefile"
            )
            
            if error[0] == QgsVectorFileWriter.NoError:
                self.log(f"Vector layer saved successfully: {output_path}", Qgis.Success)
                return True
            else:
                self.log(f"Error saving vector layer: {error}", Qgis.Warning)
                return False
                
        except Exception as e:
            self.log(f"Failed to create vector layer: {str(e)}", Qgis.Warning)
            import traceback
            self.log(f"Traceback: {traceback.format_exc()}", Qgis.Warning)
            return False

    def apply_graduated_symbology_to_vector(self, layer, field_name):
        """Wendet abgestufte Symbolisierung auf Vector-Layer an.
        
        Verwendet den gleichen Farbverlauf wie beim Raster (Red → Yellow → Green)
        und die gleiche Anzahl an Klassen.
        
        Args:
            layer (QgsVectorLayer): Der Vector-Layer
            field_name (str): Name des Feldes für die Klassifizierung
            
        Returns:
            bool: True bei Erfolg, False bei Fehler
        """
        try:
            # Prüfe ob Layer und Feld gültig sind
            if not layer or not layer.isValid():
                self.log("Ungültiger Layer für Symbolisierung", Qgis.Warning)
                return False
            
            field_index = layer.fields().indexOf(field_name)
            if field_index == -1:
                self.log(f"Feld '{field_name}' nicht gefunden", Qgis.Warning)
                return False
            
            # Hole Min/Max-Werte aus dem Feld
            min_val = layer.minimumValue(field_index)
            max_val = layer.maximumValue(field_index)
            
            self.log(f"Applying graduated symbology: field={field_name}, min={min_val:.2f}, max={max_val:.2f}")
            
            # Erstelle Gradient Color Ramp (gleich wie beim Raster)
            # Verwende QGIS Standard RYG-Farben aus config.py mit 5 Stops
            color_ramp = QgsGradientColorRamp(
                QColor(*InterpolationConfig.COLOR_RAMP_START),   # Start: Rot (0%)
                QColor(*InterpolationConfig.COLOR_RAMP_END)      # Ende: Grün (100%)
            )
            color_ramp.setStops([
                QgsGradientStop(
                    InterpolationConfig.COLOR_RAMP_STOP_1_POSITION,
                    QColor(*InterpolationConfig.COLOR_RAMP_STOP_1)  # Orange (25%)
                ),
                QgsGradientStop(
                    InterpolationConfig.COLOR_RAMP_MIDDLE_POSITION,
                    QColor(*InterpolationConfig.COLOR_RAMP_MIDDLE)  # Gelb (50%)
                ),
                QgsGradientStop(
                    InterpolationConfig.COLOR_RAMP_STOP_2_POSITION,
                    QColor(*InterpolationConfig.COLOR_RAMP_STOP_2)  # Hellgrün (75%)
                )
            ])
            
            # Erstelle Klassen (gleiche Anzahl wie beim Raster)
            num_classes = InterpolationConfig.COLOR_RAMP_CLASSES
            ranges = []
            
            for i in range(num_classes):
                # Berechne Klassengrenzen
                lower = min_val + (i / num_classes) * (max_val - min_val)
                upper = min_val + ((i + 1) / num_classes) * (max_val - min_val)
                
                # Hole Farbe aus dem Gradient (Mitte der Klasse)
                fraction = (i + 0.5) / num_classes
                color = color_ramp.color(fraction)
                
                # Erstelle Symbol für diese Klasse
                symbol = QgsMarkerSymbol.createSimple({
                    'name': 'circle',
                    'color': color.name(),
                    'size': '2',
                    'outline_style': 'no'
                })
                
                # Label für die Klasse
                label = f"{lower:.2f} - {upper:.2f}"
                
                # Erstelle Range
                range_obj = QgsRendererRange(lower, upper, symbol, label)
                ranges.append(range_obj)
            
            # Erstelle Graduated Renderer
            renderer = QgsGraduatedSymbolRenderer(field_name, ranges)
            renderer.setMode(QgsGraduatedSymbolRenderer.Custom)  # Benutzerdefinierte Klassen
            
            # Wende Renderer auf Layer an
            layer.setRenderer(renderer)
            layer.triggerRepaint()
            
            self.log(f"Graduated symbology applied successfully with {num_classes} classes", Qgis.Success)
            return True
            
        except Exception as e:
            self.log(f"Fehler beim Anwenden der Symbolisierung: {str(e)}", Qgis.Warning)
            import traceback
            self.log(f"Traceback: {traceback.format_exc()}", Qgis.Warning)
            return False

# CHECKT OB DAS PROJEKT GESPEICHERT IST
    def get_project_dir(self):
        """Get or create project directory for outputs."""
        project = QgsProject.instance()
        if not project.fileName():
            QMessageBox.warning(
                None,
                "Warnung",
                "Bitte speichern Sie zuerst das QGIS-Projekt."
            )
            return None
            
        # Create project directory if it doesn't exist
        project_dir = Path(project.fileName()).parent / InterpolationConfig.OUTPUT_DIR_NAME
        project_dir.mkdir(exist_ok=True)
        
        return project_dir
# ERSTELLT ODER BENUTZT EINE LAYER GRUPPE       
    def get_layer_group(self):
        """Get or create layer group for plugin outputs."""
        root = QgsProject.instance().layerTreeRoot()
        group_name = InterpolationConfig.LAYER_GROUP_NAME
        
        # Find existing group or create new one
        group = root.findGroup(group_name)
        if not group:
            group = root.addGroup(group_name)
            
        return group
# RETURNS DEN base_name         
    def generate_output_name(self, input_layer, field_name, method):
        """Generate output name based on input parameters."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        base_name = f"{method}_{input_layer.name()}_{field_name}_{timestamp}"
        return base_name
# RETURNS EIN METADATA DICT IN JSON IM ORDNER        
    def save_metadata(self, output_dir, base_name, params, interpolation_type="raster"):
        """Speichert Metadaten über die Interpolation.
        
        Diese Methode ist generisch und funktioniert für beide Interpolationstypen:
        - Raster-Interpolation: Speichert Input-Layer, Feld, Cell-Size, Boundary
        - Punkt-Interpolation: Speichert Kovariaten-Layer, Ziel-Layer, Felder
        
        Args:
            output_dir (Path): Verzeichnis für Metadaten-Datei
            base_name (str): Basis-Name für die Metadaten-Datei
            params (dict): Parameter-Dictionary mit allen Interpolations-Einstellungen
            interpolation_type (str): "raster" oder "point" (default: "raster")
            
        Returns:
            str: Pfad zur erstellten Metadaten-Datei oder None bei Fehler
        """
        try:
            # Basis-Metadaten (für beide Typen gleich)
            metadata = {
                "interpolation_type": interpolation_type,
                "timestamp": datetime.now().isoformat(),
                "method": params.get("method", "ordinary_kriging"),
                "kriging_parameters": {
                    "variogram_model": params.get("variogram_model"),
                    "nlags": params.get("nlags"),
                    "sill": params.get("sill"),
                    "range": params.get("range"),
                    "nugget": params.get("nugget")
                }
            }
            
            # Typ-spezifische Metadaten
            if interpolation_type == "raster":
                metadata.update({
                    "input_layer": params.get("input_layer").name() if params.get("input_layer") else None,
                    "input_field": params.get("input_field"),
                    "cell_size": params.get("cell_size"),
                    "boundary_layer": params.get("boundary_layer").name() if params.get("boundary_layer") else None,
                    "output_format": "GeoTIFF"
                })
            elif interpolation_type == "point":
                metadata.update({
                    "covariate_layer": params.get("covariate_layer").name() if params.get("covariate_layer") else None,
                    "covariate_field": params.get("covariate_field"),
                    "target_layer": params.get("target_layer").name() if params.get("target_layer") else None,
                    "interpolated_points": params.get("interpolated_points_count", "N/A"),
                    "backup_created": params.get("backup_created", False),
                    "backup_path": params.get("backup_path")
                })
            
            # Speichere Metadaten
            metadata_path = output_dir / f"{base_name}{InterpolationConfig.METADATA_SUFFIX}"
            with open(metadata_path, "w") as f:
                json.dump(metadata, f, indent=4)
            
            self.log(f"Metadaten gespeichert: {metadata_path.name}", Qgis.Info)
            return str(metadata_path)
            
        except Exception as e:
            self.log(f"Fehler beim Speichern der Metadaten: {str(e)}", Qgis.Warning)
            return None
# ERSTELLT DIE OUTPUT PATH UND DAS DIR             
    def setup_output_paths(self, input_layer, field_name, method):
        """Setup output paths and directories.
        
        Args:
            input_layer: Input-Layer
            field_name: Feldname
            method: Methoden-Name (z.B. 'ordinary_kriging')
            
        Returns:
            tuple: (output_path, output_dir) - Pfad zur Output-Datei und Output-Verzeichnis
            
        Notes:
            - Mappt Methoden-Namen auf selbsterklärende Ordnernamen
            - 'ordinary_kriging' → 'raster_interpolation'
        """
        project_dir = self.get_project_dir()
        if not project_dir:
            return None, None
            
        # Generate base name for outputs
        base_name = self.generate_output_name(input_layer, field_name, method)
        
        # Map method names to descriptive directory names
        method_dir_mapping = {
            'ordinary_kriging': InterpolationConfig.RASTER_INTERPOLATION_DIR,
            'point_interpolation': InterpolationConfig.POINT_INTERPOLATION_DIR
        }
        
        # Use mapped name or fallback to original method name
        dir_name = method_dir_mapping.get(method, method)
        
        # Create method-specific subdirectory
        output_dir = project_dir / dir_name
        output_dir.mkdir(exist_ok=True)
        
        # Generate output path
        output_path = output_dir / f"{base_name}.tif"
        
        return str(output_path), output_dir

    def create_layer_backup(self, layer, backup_suffix="_backup"):
        """Erstellt ein Backup eines Layers, falls noch nicht vorhanden.
        
        Diese Methode erstellt beim ersten Aufruf ein Backup des Layers.
        Bei weiteren Aufrufen wird das existierende Backup wiederverwendet.
        
        Args:
            layer (QgsVectorLayer): Der zu sichernde Layer
            backup_suffix (str): Suffix für den Backup-Dateinamen (default: "_backup")
            
        Returns:
            tuple: (backup_path, was_created) - Pfad zur Backup-Datei und Boolean ob neu erstellt
                   oder (None, False) bei Fehler
            
        Notes:
            - Prüft ob bereits ein Backup existiert (verhindert mehrfache Backups)
            - Speichert im Projektverzeichnis unter 'backups/'
            - Dateiname: LayerName_backup.shp (ohne Timestamp)
            - Backup wird NICHT automatisch zum Projekt hinzugefügt
            - Idempotent: Mehrfache Aufrufe erstellen nur ein Backup
        """
        try:
            # Prüfe ob Layer gültig ist
            if not layer or not layer.isValid():
                self.log("Ungültiger Layer für Backup", Qgis.Warning)
                return None, False
            
            # Bestimme Backup-Verzeichnis
            project = QgsProject.instance()
            project_file = project.fileName()
            if project_file:
                project_dir = Path(os.path.dirname(project_file))
            else:
                self.log(
                    "QGIS-Projekt ist nicht gespeichert. Backup wird im Home-Verzeichnis erstellt.",
                    Qgis.Warning
                )
                project_dir = Path(os.path.expanduser("~"))
            
            # Erstelle Backup-Verzeichnis
            backup_dir = project_dir / "backups"
            backup_dir.mkdir(exist_ok=True)
            
            # Generiere Backup-Dateinamen
            backup_filename = f"{layer.name()}{backup_suffix}.shp"
            backup_path = backup_dir / backup_filename
            
            # Prüfe ob Backup-Datei bereits existiert
            if backup_path.exists():
                self.log(
                    f"Backup-Datei '{backup_filename}' existiert bereits. "
                    "Überspringe Backup-Erstellung.",
                    Qgis.Info
                )
                return str(backup_path), False  # Existiert bereits, nicht neu erstellt
            
            # Backup existiert noch nicht - erstelle es
            backup_path_str = str(backup_path)
            self.log(f"Erstelle Backup von Layer '{layer.name()}': {backup_path_str}")
            
            # Erstelle Backup mit QGIS Processing
            params = {
                'INPUT': layer,
                'OUTPUT': backup_path_str
            }
            
            feedback = QgsProcessingFeedback()
            result = processing.run("native:savefeatures", params, feedback=feedback)
            
            if result and 'OUTPUT' in result:
                self.log(
                    f"Backup erfolgreich erstellt: {backup_path.name}",
                    Qgis.Success
                )
                
                # Optional: Backup zum Projekt hinzufügen (auskommentiert, da meist nicht gewünscht)
                # backup_layer = QgsVectorLayer(result['OUTPUT'], backup_layer_name, "ogr")
                # if backup_layer.isValid():
                #     project.addMapLayer(backup_layer)
                
                return result['OUTPUT'], True  # Neu erstellt
            else:
                self.log("Backup-Erstellung fehlgeschlagen", Qgis.Critical)
                return None, False
                
        except Exception as e:
            self.log(f"Fehler beim Erstellen des Backups: {str(e)}", Qgis.Critical)
            import traceback
            self.log(f"Traceback: {traceback.format_exc()}", Qgis.Critical)
            return None, False

    def update_target_layer(self, target_layer, target_features, interpolated_values, field_name):
        """Aktualisiert den Ziel-Layer mit den interpolierten Werten."""
        try:
            # Debug: Eingangswerte
            self.log(f"Update Layer Start - Features: {len(target_features)}, Values: {len(interpolated_values)}")
            
            # Starte Bearbeitung des Layers
            if not target_layer.startEditing():
                raise ValueError("Konnte Layer nicht in Bearbeitungsmodus versetzen")
            
            # Debug: Zeige Layer-Informationen
            self.log(f"Layer Typ: {target_layer.type()}, Provider: {target_layer.dataProvider().name()}, CRS: {target_layer.crs().authid()}")
            
            # Debug: Zeige vorhandene Felder
            fields = target_layer.fields()
            self.log(f"Vorhandene Felder: {[field.name() for field in fields]}")
            
            # Generiere kurzen, eindeutigen Feldnamen (max. 10 Zeichen für Shapefile)
            base_field_name = InterpolationConfig.DEFAULT_FIELD_PREFIX
            counter = 1
            field_name = base_field_name
            while target_layer.fields().indexOf(field_name) != -1:
                field_name = f"{base_field_name[:InterpolationConfig.FIELD_NAME_TRUNCATE]}{counter}"
                counter += 1
            
            self.log(f"Verwende Feldnamen: {field_name}")
            
            # Erstelle ein neues Feld mit spezifischer Länge und Präzision für Shapefile
            new_field = QgsField(
                field_name, 
                QVariant.Double, 
                'Real', 
                InterpolationConfig.FIELD_TYPE_DOUBLE_LENGTH, 
                InterpolationConfig.FIELD_TYPE_DOUBLE_PRECISION
            )
            
            # Debug: Zeige Feld-Details
            self.log(f"Neues Feld Details - Name: {new_field.name()}, Typ: {new_field.type()}, TypeName: {new_field.typeName()}, Länge: {new_field.length()}, Präzision: {new_field.precision()}")
            
            # Starte Bearbeitung wenn nicht bereits im Bearbeitungsmodus
            if not target_layer.isEditable():
                if not target_layer.startEditing():
                    raise ValueError("Konnte Layer nicht in Bearbeitungsmodus versetzen")
            
            # Versuche das Attribut hinzuzufügen
            if not target_layer.addAttribute(new_field):
                provider_caps = target_layer.dataProvider().capabilities()
                self.log(f"Provider Capabilities: {provider_caps}")
                raise ValueError(f"Konnte Feld '{field_name}' nicht erstellen")
            
            # Commite die Änderungen
            if not target_layer.commitChanges():
                errors = target_layer.commitErrors()
                raise ValueError(f"Fehler beim Speichern des neuen Feldes: {', '.join(errors)}")
            
            # Starte neue Bearbeitungssession
            if not target_layer.startEditing():
                raise ValueError("Konnte Layer nicht in Bearbeitungsmodus versetzen")
                
            target_layer.updateFields()
            field_idx = target_layer.fields().indexOf(field_name)
            
            self.log(f"Neues Feld '{field_name}' erstellt mit Index {field_idx}")
            
            # Debug: Zeige erste 5 Änderungen
            for i, (feature, value) in enumerate(list(zip(target_features, interpolated_values))[:5]):
                self.log(f"Update #{i}: Feature ID {feature.id()}, Wert {value}")
                if not target_layer.changeAttributeValue(feature.id(), field_idx, float(value)):
                    raise ValueError(f"Fehler beim Aktualisieren von Feature {feature.id()}")
            
            # Rest der Werte
            for feature, value in list(zip(target_features, interpolated_values))[5:]:
                if not target_layer.changeAttributeValue(feature.id(), field_idx, float(value)):
                    raise ValueError(f"Fehler beim Aktualisieren von Feature {feature.id()}")
            
            # Speichere die Änderungen
            if not target_layer.commitChanges():
                raise ValueError("Fehler beim Speichern der Änderungen: " + 
                               ", ".join(target_layer.commitErrors()))
            
            self.log(f"Ziel-Layer erfolgreich mit Feld '{field_name}' aktualisiert")
            
        except Exception as e:
            self.log(f"Fehler beim Aktualisieren des Ziel-Layers: {str(e)}", Qgis.Critical)
            raise
# HIER WIRD DIE PUNKT ZU PUNKT INTERPOLATION DEFINIERT
    def run_point_interpolation(self, params):
        """Führt die Punkt-zu-Punkt Interpolation durch."""
        try:
            # Validiere Parameter
            required_params = ['covariate_layer', 'covariate_field', 'target_layer', 'variogram_model', 
                             'nlags', 'sill', 'range', 'nugget']
            for param in required_params:
                if param not in params:
                    raise ValueError(f"Fehlender Parameter: {param}")
    
            # Hole Kovariaten-Daten als Input
            covariate_layer = params['covariate_layer']
            covariate_field = params['covariate_field']
            target_layer = params['target_layer']
            
            # Debug: Zeige Kovariaten-Daten
            self.log(f"Kovariaten-Layer: {covariate_layer.name()}, Feld: {covariate_field}")
            
            # Bereite Kovariaten-Daten vor
            x, y, z = self.prepare_data(covariate_layer, covariate_field, None)
            if x is None:
                raise ValueError("Keine gültigen Kovariaten-Daten gefunden")
            
            # Debug: Zeige Input-Daten
            self.log(f"Input-Daten: x={len(x)}, y={len(y)}, z={len(z)}")
                    
            # Hole Koordinaten vom Ziel-Layer
            target_points = []
            target_features = []
            
            for feature in target_layer.getFeatures():
                geom = feature.geometry()
                if geom and geom.isGeosValid():
                    point = geom.asPoint()
                    target_points.append((point.x(), point.y()))
                    target_features.append(feature)
            
            # Debug: Zeige Ziel-Punkte
            self.log(f"Anzahl Zielpunkte: {len(target_points)}")
                        
            if not target_points:
                raise ValueError("Keine gültigen Zielpunkte gefunden")
                        
            x_points, y_points = zip(*target_points)
            
            # Debug: Parameter für Kriging
            self.log(f"Kriging Parameter: model={params['variogram_model']}, sill={params['sill']}, range={params['range']}, nugget={params['nugget']}")
            
            # Führe Interpolation durch
            interpolated_values = self.interpolate_ordinary_kriging(
                x, y, z, 
                np.array(x_points),
                np.array(y_points),
                params,
                style='points'
            )
            
            # Debug: Zeige interpolierte Werte
            if interpolated_values is not None:
                self.log(f"Interpolierte Werte: min={np.min(interpolated_values)}, max={np.max(interpolated_values)}, len={len(interpolated_values)}")
            
            if interpolated_values is None:
                raise ValueError("Interpolation fehlgeschlagen")
        
            # Erstelle Backup des Ziel-Layers vor Modifikation (nur beim ersten Mal)
            backup_path, backup_created = self.create_layer_backup(target_layer)
            if not backup_path:
                self.log(
                    "Warnung: Backup konnte nicht erstellt werden. Fahre trotzdem fort.",
                    Qgis.Warning
                )
            
            # Speichere Backup-Status für Success-Nachricht
            params['backup_created'] = backup_created
            params['backup_path'] = backup_path
        
            # Aktualisiere Ziel-Layer mit neuem Feld
            # Generiere kurzen Feldnamen für Shapefile (max. 10 Zeichen)
            # Entferne Sonderzeichen und kürze wenn nötig
            clean_name = ''.join(c for c in covariate_field if c.isalnum())
            field_name = f"{clean_name[:InterpolationConfig.FIELD_NAME_TRUNCATE]}INT"
            self.update_target_layer(target_layer, target_features, interpolated_values, field_name)
            
            # Speichere Metadaten für Punkt-Interpolation
            params['interpolated_points_count'] = len(interpolated_values)
            
            # Erstelle Output-Verzeichnis für Metadaten
            project_dir = self.get_project_dir()
            if project_dir:
                metadata_dir = project_dir / InterpolationConfig.POINT_INTERPOLATION_DIR
                metadata_dir.mkdir(exist_ok=True)
                
                # Generiere Base-Name für Metadaten
                base_name = self.generate_output_name(
                    covariate_layer, 
                    covariate_field, 
                    InterpolationConfig.POINT_INTERPOLATION_DIR
                )
                
                # Speichere Metadaten
                self.save_metadata(metadata_dir, base_name, params, interpolation_type="point")
            
            self.log("Punkt-Interpolation erfolgreich abgeschlossen", Qgis.Success)
        
        except Exception as e:
            self.log(f"Fehler bei der Punkt-Interpolation: {str(e)}", Qgis.Critical)
            raise
   
                
# HIER WERDEN DIE GANZEN FUNTKIONEN GECALLED UND DER PROGRESS GEHANDELT 
    def run(self):
        """Run method that performs all the real work"""
        
        # Check if required libraries are available
        if not INTERPOLATION_LIBS_AVAILABLE:
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Missing Dependencies",
                "Required libraries are not available. Please install the missing dependencies."
            )
            return

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            from .i_plugin_dialog import IPlugInDialog
            self.dlg = IPlugInDialog(self.iface)
            self.dlg.plugin = self  # Store reference to plugin instance
            
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        
        # See if OK was pressed
        if result:
            # Create a dialog with busy indicator
            progress = QProgressDialog(self.tr("Interpolation läuft..."), self.tr("Abbrechen"), 0, 0, self.iface.mainWindow())
            progress.setWindowTitle("I-PlugIn")
            progress.setWindowModality(Qt.WindowModal)
            progress.setMinimumDuration(0)
            progress.setAutoClose(True)
            progress.setAutoReset(True)
            progress.setMinimum(0)
            progress.setMaximum(0)  # Indeterminate mode
            
            try:
                # Show the progress dialog
                progress.show()
                
                # Get parameters from dialog
                params = self.dlg.get_parameters()
                
                # Setup output paths
                output_path, output_dir = self.setup_output_paths(
                    params['input_layer'],
                    params['input_field'],
                    params['method']
                )
                if not output_path:
                    progress.close()
                    return
                    
                params['output_path'] = output_path
                
                # Process events to keep UI responsive
                from qgis.PyQt.QtCore import QCoreApplication
                QCoreApplication.processEvents()
                
                # Check for cancellation
                if progress.wasCanceled():
                    raise Exception("Interpolation wurde vom Benutzer abgebrochen")
                
                # Prepare data
                x, y, z = self.prepare_data(
                    params['input_layer'],
                    params['input_field'],
                    params.get('boundary_layer')
                )
                
                if x is None or y is None or z is None:
                    raise ValueError("Keine gültigen Daten für die Interpolation gefunden")
                
                # Get CRS from input layer
                target_crs = params['input_layer'].crs()
                
                QCoreApplication.processEvents()
                if progress.wasCanceled():
                    raise Exception("Interpolation wurde vom Benutzer abgebrochen")
                
                # Bestimme die Extent für Grid-Erstellung
                if params.get('boundary_layer'):
                    grid_extent = params['boundary_layer'].extent()
                    self.log("Using boundary extent for grid")
                else:
                    grid_extent = params['input_layer'].extent()
                    self.log("Using input layer extent for grid")
                
                # Create output grid (Buffer wird automatisch durch GRID_BUFFER_MULTIPLIER hinzugefügt)
                grid_x, grid_y, mask = self.create_output_grid(
                    grid_extent,
                    params['cell_size'],
                    params.get('boundary_layer')
                )
                
                QCoreApplication.processEvents()
                if progress.wasCanceled():
                    raise Exception("Interpolation wurde vom Benutzer abgebrochen")
                
                # Perform interpolation
                interpolated_data = self.interpolate_ordinary_kriging(
                    x, y, z, grid_x, grid_y, params
                )
                
                QCoreApplication.processEvents()
                if progress.wasCanceled():
                    raise Exception("Interpolation wurde vom Benutzer abgebrochen")
                
                # Create and save raster layer
                # Verwende die erweiterte Extent für das Raster
                extent = grid_extent
                    
                self.create_raster_layer(
                    interpolated_data,
                    extent,
                    params['cell_size'],
                    output_path,
                    target_crs,
                    mask,
                    x=grid_x,
                    y=grid_y
                )
                
                # Save metadata
                self.save_metadata(output_dir, Path(output_path).stem, params, interpolation_type="raster")
                
                # Create vector layer from interpolated grid points
                vector_output_path = str(output_dir / f"{Path(output_path).stem}_points.shp")
                vector_created = self.create_vector_layer_from_grid(
                    grid_x, grid_y, interpolated_data,
                    vector_output_path,
                    target_crs,
                    mask=mask,
                    field_name=params['input_field']
                )
                
                # Add layer to QGIS
                layer_name = Path(output_path).stem
                layer = QgsRasterLayer(output_path, layer_name)
                
                if layer.isValid():
                    # Add to layer group
                    group = self.get_layer_group()
                    QgsProject.instance().addMapLayer(layer, False)
                    group.addLayer(layer)
                    
                    # Apply color ramp styling
                    self.apply_color_ramp_to_raster(layer)
                    
                    # Add vector layer to project if created successfully
                    if vector_created and Path(vector_output_path).exists():
                        vector_layer = QgsVectorLayer(vector_output_path, f"{layer_name}_points", "ogr")
                        if vector_layer.isValid():
                            # Wende abgestufte Symbolisierung an
                            self.apply_graduated_symbology_to_vector(vector_layer, params['input_field'])
                            
                            QgsProject.instance().addMapLayer(vector_layer, False)
                            group.addLayer(vector_layer)
                            self.log(f"Vector layer added to project: {layer_name}_points", Qgis.Success)
                    
                    # Get variogram info from params
                    variogram_info = params.get('variogram_info', {})
                    if variogram_info:
                        metrics = variogram_info.get('metrics', {})
                        parameters = variogram_info.get('parameters', {})
                        success_msg = (
                            f"Interpolation erfolgreich abgeschlossen: {layer_name}\n"
                            f"Variogramm Modell: {params['variogram_model']}\n"
                            f"RMSE: {metrics.get('rmse', 'N/A'):.3f}\n"
                            f"R²: {metrics.get('r2', 'N/A'):.3f}\n"
                            f"Range: {parameters.get('range', 'N/A'):.2f}\n"
                            f"Sill: {parameters.get('sill', 'N/A'):.2f}\n"
                            f"Nugget: {parameters.get('nugget', 'N/A'):.2f}"
                        )
                    else:
                        success_msg = f"Interpolation erfolgreich abgeschlossen: {layer_name}"
                    
                    self.iface.messageBar().pushSuccess(
                        "I-PlugIn",
                        success_msg
                    )
                else:
                    progress.close()
                    raise Exception("Failed to load output layer")
                    
                # Close the progress dialog
                progress.close()
                    
            except DataValidationError as e:
                # Close progress dialog if it exists
                if 'progress' in locals():
                    progress.close()
                    
                self.iface.messageBar().pushWarning(
                    "I-PlugIn - Datenvalidierung",
                    f"Daten-Problem: {str(e)}"
                )
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    "Datenvalidierung fehlgeschlagen",
                    str(e)
                )
                
            except GeometryError as e:
                # Close progress dialog if it exists
                if 'progress' in locals():
                    progress.close()
                    
                self.iface.messageBar().pushWarning(
                    "I-PlugIn - Geometrie",
                    f"Geometrie-Problem: {str(e)}"
                )
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    "Geometrie-Problem",
                    str(e)
                )
                
            except CoordinateSystemError as e:
                # Close progress dialog if it exists
                if 'progress' in locals():
                    progress.close()
                    
                self.iface.messageBar().pushWarning(
                    "I-PlugIn - Koordinatensystem",
                    f"CRS-Problem: {str(e)}"
                )
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    "Koordinatensystem-Problem",
                    str(e)
                )
                
            except InterpolationCalculationError as e:
                # Close progress dialog if it exists
                if 'progress' in locals():
                    progress.close()
                    
                self.iface.messageBar().pushCritical(
                    "I-PlugIn - Berechnung",
                    f"Interpolations-Fehler: {str(e)}"
                )
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "Interpolation fehlgeschlagen",
                    str(e)
                )
                
            except InterpolationError as e:
                # Catch all other plugin-specific errors
                if 'progress' in locals():
                    progress.close()
                    
                self.iface.messageBar().pushCritical(
                    "I-PlugIn",
                    f"Plugin-Fehler: {str(e)}"
                )
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "Fehler",
                    str(e)
                )
                
            except Exception as e:
                # Unexpected errors
                if 'progress' in locals():
                    progress.close()
                    
                self.log(f"Unerwarteter Fehler: {str(e)}", Qgis.Critical)
                import traceback
                self.log(f"Traceback: {traceback.format_exc()}", Qgis.Critical)
                    
                self.iface.messageBar().pushCritical(
                    "I-PlugIn - Unerwarteter Fehler",
                    f"Ein unerwarteter Fehler ist aufgetreten: {str(e)}"
                )
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "Unerwarteter Fehler",
                    f"Ein unerwarteter Fehler ist aufgetreten:\n\n{str(e)}\n\nBitte prüfen Sie das Log für Details."
                )
