# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IPlugIn
                                 A QGIS plugin
 Plugin to perform interpolation task for onfarm research module
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lucas Johannsen
        email                : lucas.johannsen@fh-kiel.de
 ***************************************************************************/

 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
import json
from datetime import datetime
from pathlib import Path
import numpy as np
from osgeo import gdal
import matplotlib.pyplot as plt

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QProgressDialog
from qgis.core import (
    QgsMessageLog,
    QgsProject,
    QgsVectorLayer,
    QgsRasterLayer,
    QgsCoordinateReferenceSystem,
    QgsVectorFileWriter,
    QgsRasterFileWriter,
    QgsCoordinateTransform,
    QgsPointXY,
    QgsProcessingFeedback,
    Qgis,
    QgsFeature, 
    QgsField, 
    QgsGeometry, 
    QgsWkbTypes
)
from pykrige import OrdinaryKriging
import processing

from .interpolation_dialog import InterpolationDialog
from .variogram_models import (
    VARIOGRAM_MODELS,
    optimize_variogram_parameters,
)
from .variogram_plotter import VariogramPlotter

# Initialize Qt resources from file resources.py
from . import resources

INTERPOLATION_LIBS_AVAILABLE = True

class IPlugIn:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IPlugIn_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Interpolation')
        self.dlg = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('Interpolation', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True,
                  add_to_menu=True, add_to_toolbar=True, status_tip=None,
                  whats_this=None, parent=None):
        """Add a toolbar icon to the toolbar."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        
        # Check if required libraries are available
        if not INTERPOLATION_LIBS_AVAILABLE:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "Missing Dependencies",
                "Some required libraries are missing. Please install:\n"
                "- pykrige\n"
                "Using pip or your package manager."
            )

        icon_path = ':/plugins/interpolation/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Interpolate'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Interpolation'),
                action)
            self.iface.removeToolBarIcon(action)

    def get_field_value(self, feature, field_name):
        """Safely get numeric value from field, handling QVariant types."""
        value = feature[field_name]
        
        # Handle NULL or None values
        if value is None:
            return None
            
        # Handle QVariant values
        if isinstance(value, QVariant):
            if value.isNull():
                return None
            # Convert QVariant to Python type
            try:
                if value.type() == QVariant.String:
                    return float(value.toString())
                else:
                    return float(value.toDouble()[0])
            except (ValueError, TypeError, AttributeError):
                return None
                
        # Handle direct numeric values
        try:
            return float(value)
        except (ValueError, TypeError):
            return None
# LAYER AUF GEOMETRY ÜBERPRÜFEN UND DIE GEOM RETURN
    def get_valid_geometry(self, feature):
        """Überprüft und validiert die Geometrie eines Features.
        
        Diese Methode führt mehrere Prüfungen durch:
        1. Prüft ob das Feature überhaupt eine Geometrie hat
        2. Prüft ob die Geometrie nicht None ist
        3. Versucht ungültige Geometrien zu reparieren
        
        Args:
            feature (QgsFeature): Das zu prüfende Feature
            
        Returns:
            QgsGeometry or None: Die validierte Geometrie oder None wenn die Geometrie
                                ungültig ist und nicht repariert werden konnte
        
        Logs:
            Info: Wenn Feature keine Geometrie hat
            Info: Wenn Geometrie None ist
            Info: Original Geometrie-Typ
            Info: Wenn Reparatur versucht wird
            Warning: Wenn Reparatur fehlschlägt
        """
        if not feature.hasGeometry():
            QgsMessageLog.logMessage("Feature has no geometry", "Interpolation", Qgis.Info)
            return None
            
        geom = feature.geometry()
        if not geom:
            QgsMessageLog.logMessage("Geometry is None", "Interpolation", Qgis.Info)
            return None
            
        QgsMessageLog.logMessage(f"Original geometry type: {geom.wkbType()}", "Interpolation", Qgis.Info)
        
        # Try to fix any invalid geometries
        if not geom.isGeosValid():
            QgsMessageLog.logMessage("Invalid geometry, attempting to fix", "Interpolation", Qgis.Info)
            geom = geom.makeValid()
            if not geom.isGeosValid():
                QgsMessageLog.logMessage("Failed to fix invalid geometry", "Interpolation", Qgis.Warning)
                return None
                
        return geom
        
    def convert_to_utm(self, layer):
        """Konvertiert einen Layer in das passende UTM-Koordinatensystem.
        
        Diese Methode führt folgende Schritte durch:
        1. Prüft ob der Layer bereits in UTM ist (EPSG:326xx oder EPSG:327xx)
        2. Berechnet den Mittelpunkt des Layers
        3. Transformiert den Mittelpunkt nach WGS84
        4. Berechnet die passende UTM-Zone basierend auf der Länge
        5. Erstellt einen neuen Layer mit dem UTM-Koordinatensystem
        
        Args:
            layer (QgsVectorLayer): Der zu konvertierende Layer
            
        Returns:
            QgsVectorLayer: Der konvertierte Layer im UTM-Format oder der originale Layer,
                           wenn dieser bereits in UTM ist
            
        Raises:
            ValueError: Wenn die Konvertierung fehlschlägt
            
        Notes:
            - Der neue Layer wird automatisch dem Projekt hinzugefügt
            - Der Dateiname des neuen Layers beginnt mit 'UTM_'
            - Für die Nord-/Südhalbkugel werden die EPSG-Codes 326xx/327xx verwendet
        """
        source_crs = layer.crs()
        
        # Check if already in UTM
        if source_crs.isValid() and source_crs.authid().startswith('EPSG:326') or source_crs.authid().startswith('EPSG:327'):
            return layer
            
        # Get layer center
        extent = layer.extent()
        center_x = (extent.xMinimum() + extent.xMaximum()) / 2
        center_y = (extent.yMinimum() + extent.yMaximum()) / 2

        # Transform center to WGS84
        wgs84_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        transformer = QgsCoordinateTransform(source_crs, wgs84_crs, QgsProject.instance())
        center_point_wgs84 = transformer.transform(QgsPointXY(center_x, center_y))
        lon = center_point_wgs84.x()
        lat = center_point_wgs84.y()

        # Calculate UTM zone
        utm_zone = int((lon + 180) / 6) + 1
        target_epsg = 32600 + utm_zone if lat >= 0 else 32700 + utm_zone
        target_crs = QgsCoordinateReferenceSystem(f"EPSG:{target_epsg}")

        # Get project directory or home directory as fallback
        project_file = QgsProject.instance().fileName()
        if project_file:
            project_dir = Path(os.path.dirname(project_file))
        else:
            project_dir = Path(os.path.expanduser("~"))
            
        # Ensure output directory exists
        project_dir.mkdir(parents=True, exist_ok=True)

        # Create output path
        new_layer_name = "UTM_" + layer.name()
        # Ensure proper path handling
        output_path = str(project_dir / f"{new_layer_name}.shp")

        # Reproject layer
        params = {
            'INPUT': layer,
            'TARGET_CRS': target_crs,
            'OUTPUT': output_path
        }
        feedback = QgsProcessingFeedback()
        result = processing.run("native:reprojectlayer", params, feedback=feedback)

        # Load and verify new layer
        new_layer = QgsVectorLayer(result['OUTPUT'], new_layer_name, "ogr")
        if not new_layer.isValid():
            QgsMessageLog.logMessage("Failed to create UTM layer", "Interpolation", Qgis.Critical)
            return None

        # Add to project and return
        QgsProject.instance().addMapLayer(new_layer)
        return new_layer
# DIE BOUNDARY POLYGONS ÜBERPRÜFEN UND RETURN 
    def combine_boundary_geometries(self, boundary_layer):
        """Kombiniert alle gültigen Polygon-Geometrien eines Boundary-Layers zu einer einzigen Geometrie.
        
        Diese Methode verarbeitet sowohl Einzel- als auch Multipart-Geometrien:
        1. Prüft jeden Feature auf gültige Geometrie
        2. Bei Multipart-Geometrien:
           - Zerlegt sie in ihre Einzelteile
           - Verarbeitet jedes Teil einzeln
        3. Bei Einzelgeometrien:
           - Fügt sie direkt zur Gesamtgeometrie hinzu
        4. Kombiniert alle gültigen Teile zu einer Gesamtgeometrie
        
        Args:
            boundary_layer (QgsVectorLayer): Der Layer mit den zu kombinierenden Polygonen
            
        Returns:
            QgsGeometry or None: Die kombinierte Geometrie aller gültigen Polygone oder
                                None wenn keine gültigen Geometrien gefunden wurden
        
        Logs:
            Info: Wenn kein Layer übergeben wurde
            Info: Anzahl der Features im Layer
            Info: Ungültige Geometrien in Features
            Info: Verarbeitung von Multi/Single-Part Geometrien
            Warning: Fehler beim Kombinieren oder Verarbeiten von Geometrien
        
        Notes:
            - Ungültige Geometrien werden übersprungen
            - Bei Fehlern beim Kombinieren wird der Prozess fortgesetzt
            - Unterstützt nur Polygon-Geometrien
        """
        if not boundary_layer:
            QgsMessageLog.logMessage("No boundary layer provided", "Interpolation", Qgis.Info)
            return None
            
        QgsMessageLog.logMessage(f"Processing boundary layer with {boundary_layer.featureCount()} features", "Interpolation", Qgis.Info)
        
        boundary_geom = None
        for feature in boundary_layer.getFeatures():
            geom = self.get_valid_geometry(feature)
            if not geom:
                QgsMessageLog.logMessage("Invalid geometry in boundary feature", "Interpolation", Qgis.Info)
                continue
                
            # Handle different geometry types
            if geom.isMultipart():
                QgsMessageLog.logMessage("Processing multipart geometry", "Interpolation", Qgis.Info)
                try:
                    if geom.type() == QgsWkbTypes.PolygonGeometry:
                        parts = geom.asMultiPolygon()
                    else:
                        QgsMessageLog.logMessage(f"Unexpected geometry type: {geom.type()}", "Interpolation", Qgis.Info)
                        continue
                        
                    for part in parts:
                        part_geom = QgsGeometry.fromPolygonXY(part)
                        if not part_geom or not part_geom.isGeosValid():
                            QgsMessageLog.logMessage("Invalid part geometry", "Interpolation", Qgis.Info)
                            continue
                            
                        if boundary_geom is None:
                            boundary_geom = part_geom
                        else:
                            try:
                                boundary_geom = boundary_geom.combine(part_geom)
                            except Exception as e:
                                QgsMessageLog.logMessage(f"Error combining geometries: {str(e)}", "Interpolation", Qgis.Warning)
                                continue
                except Exception as e:
                    QgsMessageLog.logMessage(f"Error processing multipart geometry: {str(e)}", "Interpolation", Qgis.Warning)
                    continue
            else:
                QgsMessageLog.logMessage("Processing single part geometry", "Interpolation", Qgis.Info)
                if boundary_geom is None:
                    boundary_geom = geom
                else:
                    try:
                        boundary_geom = boundary_geom.combine(geom)
                    except Exception as e:
                        QgsMessageLog.logMessage(f"Error combining geometries: {str(e)}", "Interpolation", Qgis.Warning)
                        continue
                    
        if not boundary_geom:
            QgsMessageLog.logMessage("No valid boundary geometry created", "Interpolation", Qgis.Warning)
            raise ValueError(
                "Der Grenzlayer enthält keine gültigen Polygone. "
                "Bitte überprüfen Sie die Geometrien im Layer."
            )
            
        # Try to fix any invalid geometries after combining
        if not boundary_geom.isGeosValid():
            QgsMessageLog.logMessage("Combined geometry is invalid, attempting to fix", "Interpolation", Qgis.Info)
            boundary_geom = boundary_geom.makeValid()
            if not boundary_geom.isGeosValid():
                QgsMessageLog.logMessage("Failed to fix combined geometry", "Interpolation", Qgis.Warning)
                raise ValueError(
                    "Die kombinierten Grenzpolygone sind ungültig. "
                    "Bitte überprüfen Sie die Geometrien im Layer."
                )
            
        QgsMessageLog.logMessage("Successfully created valid boundary geometry", "Interpolation", Qgis.Info)
        return boundary_geom
# CHECKS DIE DATEN DIE EINGEBEN WERDEN OB SIE IN DER BOUNDARY LIEGEN
    def validate_input_data(self, layer, field_name, boundary_layer=None):
        """Validiert die Eingabedaten für die Interpolation.
        
        Führt umfangreiche Prüfungen der Eingabedaten durch:
        1. Layer-Prüfungen:
           - Existenz von Features
           - Gültiges Koordinatensystem (UTM)
           - Automatische UTM-Konvertierung bei Bedarf
        2. Feld-Prüfungen:
           - Existenz gültiger numerischer Werte
        3. Boundary-Prüfungen (optional):
           - Gültigkeit der Geometrien
           - UTM-Konvertierung wenn nötig
           - Lage der Punkte innerhalb der Boundary
        
        Args:
            layer (QgsVectorLayer): Der zu prüfende Eingabe-Layer
            field_name (str): Name des Feldes mit den zu interpolierenden Werten
            boundary_layer (QgsVectorLayer, optional): Layer mit Begrenzungspolygonen
            
        Returns:
            tuple: (QgsVectorLayer, QgsVectorLayer or None) - (validierter Input-Layer,
                   validierter Boundary-Layer oder None)
            
        Raises:
            ValueError: Bei ungültigen Eingabedaten mit erklärender Nachricht:
                       - Keine Features im Layer
                       - Keine gültigen Werte im Feld
                       - UTM-Konvertierung fehlgeschlagen
                       - Ungültige Boundary-Geometrien
        
        Notes:
            - Bietet interaktive UTM-Konvertierung mit Benutzerabfrage
            - Prüft auch auf NaN-Werte im Zielfeld
            - Boundary-Layer ist optional
        """
        # Check if layer has features
        if layer.featureCount() == 0:
            raise ValueError(
                "Der Eingabelayer enthält keine Punkte. "
                "Bitte wählen Sie einen Layer mit Punktdaten aus."
            )
            
        # Check if field has valid values
        valid_count = 0
        zero_count = 0
        total_count = 0
        
        for feature in layer.getFeatures():
            total_count += 1
            value = self.get_field_value(feature, field_name)
            if value is not None and not np.isnan(value):
                valid_count += 1
                if value == 0:
                    zero_count += 1
                
        if valid_count == 0:
            raise ValueError(
                f"Das ausgewählte Feld '{field_name}' enthält keine gültigen Werte. "
                "Bitte wählen Sie ein Feld mit numerischen Werten aus."
            )
            
        # Warnung wenn alle oder die meisten Werte Null sind
        if zero_count > 0:
            zero_percentage = (zero_count / valid_count) * 100
            if zero_percentage > 90:  # Wenn mehr als 90% der Werte Null sind
                msg_box = QMessageBox()
                msg_box.setIcon(QMessageBox.Warning)
                msg_box.setText(f"Warnung: {zero_percentage:.1f}% der Werte sind Null")
                msg_box.setInformativeText(
                    f"Von {valid_count} gültigen Werten sind {zero_count} Null-Werte.\n"
                    "Dies könnte zu Problemen bei der Interpolation führen."
                )
                msg_box.setStandardButtons(QMessageBox.Ok)
                msg_box.exec_()
            
        # Check if layer is in UTM coordinate system
        if not layer.crs().isValid() or not (layer.crs().authid().startswith('EPSG:326') or layer.crs().authid().startswith('EPSG:327')):
            msg_box = QMessageBox()
            msg_box.setIcon(QMessageBox.Question)
            msg_box.setText("Der Layer ist nicht im UTM-Format.")
            msg_box.setInformativeText("Soll der Layer automatisch in das passende UTM-Format konvertiert werden?")
            msg_box.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
            msg_box.setDefaultButton(QMessageBox.Yes)
            
            if msg_box.exec_() == QMessageBox.Yes:
                utm_layer = self.convert_to_utm(layer)
                if utm_layer:
                    layer = utm_layer
                else:
                    raise ValueError("Die UTM-Konvertierung ist fehlgeschlagen.")
            else:
                QgsMessageLog.logMessage(
                    "Benutzer hat UTM-Konvertierung abgelehnt. Fahre mit originalem CRS fort.",
                    "Interpolation",
                    Qgis.Warning
                )
            
        # If boundary layer is specified, check if points fall within it and convert to UTM if needed
        if boundary_layer:
            if not boundary_layer.crs().isValid() or not (boundary_layer.crs().authid().startswith('EPSG:326') or boundary_layer.crs().authid().startswith('EPSG:327')):
                utm_boundary = self.convert_to_utm(boundary_layer)
                if utm_boundary:
                    boundary_layer = utm_boundary
                else:
                    raise ValueError("Die UTM-Konvertierung des Boundary-Layers ist fehlgeschlagen.")
        if boundary_layer:
            if boundary_layer.featureCount() == 0:
                raise ValueError(
                    "Der Grenzlayer enthält keine Features. "
                    "Bitte wählen Sie einen Layer mit Polygonen aus."
                )
                
            # Get first valid boundary geometry
            boundary_geom = None
            for feature in boundary_layer.getFeatures():
                geom = feature.geometry()
                if geom and geom.isGeosValid():
                    boundary_geom = geom
                    break
                    
            if not boundary_geom:
                raise ValueError(
                    "Der Grenzlayer enthält keine gültigen Polygone. "
                    "Bitte überprüfen Sie die Geometrien im Layer."
                )
                
            # Check points against boundary
            points_within = 0
            for feature in layer.getFeatures():
                geom = feature.geometry()
                if not geom:
                    continue
                    
                if geom.within(boundary_geom):
                    points_within += 1
                    
            if points_within == 0:
                raise ValueError(
                    "Keine Punkte liegen innerhalb der ausgewählten Grenze. "
                    "Bitte überprüfen Sie die Lage der Punkte und die Grenze."
                )
                
            return points_within
            
        return valid_count


################################ Interpolation beginnt #####################################################################        
# ERSTELLT NUMPY ARRAYS UM DIE DATEN FÜRS KRIGING VORZUBEREITEN
    def prepare_data(self, layer, field_name, boundary_layer=None):
        """Bereitet die Vektordaten für die Kriging-Interpolation vor.
        
        Transformiert die Eingabedaten in das für Kriging benötigte Format:
        1. Validierung der Eingabedaten:
           - Prüft Layer und Feldwerte
           - Prüft UTM-Koordinatensystem
           - Prüft Boundary wenn vorhanden
        2. Extraktion der Daten:
           - Koordinaten (x, y) aus den Geometrien
           - Werte (z) aus dem spezifizierten Feld
        3. Filterung der Daten:
           - Nur gültige Geometrien
           - Nur Punkte innerhalb der Boundary (wenn vorhanden)
           - Nur nicht-None und nicht-NaN Werte
        
        Args:
            layer (QgsVectorLayer): Layer mit den Punktdaten
            field_name (str): Name des Feldes mit den zu interpolierenden Werten
            boundary_layer (QgsVectorLayer, optional): Layer mit Begrenzungspolygonen
            
        Returns:
            tuple: (x, y, z) - NumPy Arrays mit den Koordinaten und Werten:
                   - x (np.array): X-Koordinaten der Punkte
                   - y (np.array): Y-Koordinaten der Punkte
                   - z (np.array): Zu interpolierende Werte
                   Oder (None, None, None) wenn keine gültigen Daten gefunden wurden
            
        Raises:
            ValueError: Wenn die Validierung fehlschlägt oder keine gültigen Daten
                       gefunden werden
        
        Notes:
            - Loggt die Anzahl der Features in Input- und Boundary-Layer
            - Ungültige Geometrien oder Werte werden stillschweigend übersprungen
            - Boundary-Check ist optional und wird nur durchgeführt wenn boundary_layer
              übergeben wurde
        """
        # Log initial layer states
        QgsMessageLog.logMessage(f"Input layer feature count: {layer.featureCount()}", "Interpolation", Qgis.Info)
        if boundary_layer:
            QgsMessageLog.logMessage(f"Boundary layer feature count: {boundary_layer.featureCount()}", "Interpolation", Qgis.Info)
        
        # Validate input data
        self.validate_input_data(layer, field_name, boundary_layer)
        
        # Initialize arrays for coordinates and values
        x = []
        y = []
        z = []
        
        # Iterate over features in the input layer
        for feature in layer.getFeatures():
            geom = feature.geometry()
            if not geom or not geom.isGeosValid():
                continue
                
            point = geom.asPoint()
            value = feature.attribute(field_name)
            
            # Wenn boundary_layer vorhanden, prüfe ob der Punkt in irgendeiner Parzelle liegt
            if boundary_layer:
                point_geom = QgsGeometry.fromPointXY(point)
                in_boundary = False
                for boundary_feature in boundary_layer.getFeatures():
                    if point_geom.within(boundary_feature.geometry()):
                        in_boundary = True
                        break
                if not in_boundary:
                    continue
            
            # Punkt hinzufügen wenn er valide ist
            if value is not None:
                x.append(point.x())
                y.append(point.y())
                z.append(float(value))
        
        # Convert lists to numpy arrays
        if len(x) > 0:
            x = np.array(x, dtype=np.float64)
            y = np.array(y, dtype=np.float64)
            z = np.array(z, dtype=np.float64)
            return x, y, z
        
        return None, None, None
# ERSTELLT OUTPUT GRID FÜRS KRIGING ERSTELLT DIE COORDINATES 
    def create_output_grid(self, extent, cell_size, boundary_layer=None):
        """Create output grid for interpolation."""
        if boundary_layer and boundary_layer.featureCount() > 0:
            # Initialize extent with first valid geometry
            x_min = x_max = y_min = y_max = None
            
            # Get the combined extent of all geometries
            for feature in boundary_layer.getFeatures():
                geom = feature.geometry()
                if geom and geom.isGeosValid():
                    boundary_extent = geom.boundingBox()
                    if x_min is None:
                        x_min = boundary_extent.xMinimum()
                        x_max = boundary_extent.xMaximum()
                        y_min = boundary_extent.yMinimum()
                        y_max = boundary_extent.yMaximum()
                    else:
                        x_min = min(x_min, boundary_extent.xMinimum())
                        x_max = max(x_max, boundary_extent.xMaximum())
                        y_min = min(y_min, boundary_extent.yMinimum())
                        y_max = max(y_max, boundary_extent.yMaximum())
        else:
            # Use input layer extent as fallback
            x_min = extent.xMinimum()
            x_max = extent.xMaximum()
            y_min = extent.yMinimum()
            y_max = extent.yMaximum()
        
        # Adjust extent to align with cell size grid
        # This ensures the grid cells align perfectly with the boundary
        x_min = np.floor(x_min / cell_size) * cell_size
        x_max = np.ceil(x_max / cell_size) * cell_size
        y_min = np.floor(y_min / cell_size) * cell_size
        y_max = np.ceil(y_max / cell_size) * cell_size
        
        # Calculate number of cells
        nx = int(round((x_max - x_min) / cell_size))
        ny = int(round((y_max - y_min) / cell_size))
        
        # Log grid information
        QgsMessageLog.logMessage(
            f"Grid Info - Cells: {nx}x{ny}, Extent: ({x_min}, {y_min}) to ({x_max}, {y_max})",
            "Interpolation", Qgis.Info
        )
        
        # Create grid coordinates - these will be 1D arrays as required by PyKrige
        x = np.linspace(x_min, x_max, nx)
        y = np.linspace(y_min, y_max, ny)
        
        # Create mask if boundary layer is provided
        mask = None
        if boundary_layer:
            # Create a temporary meshgrid for checking points against boundary
            xx, yy = np.meshgrid(x, y)
            mask = np.zeros((ny, nx), dtype=bool)
            
            # Check each point against all geometries
            for i in range(ny):
                for j in range(nx):
                    point = QgsGeometry.fromPointXY(QgsPointXY(xx[i, j], yy[i, j]))
                    # Für jede Parzelle prüfen
                    for feature in boundary_layer.getFeatures():
                        geom = feature.geometry()
                        if geom and geom.isGeosValid():
                            # Wenn der Punkt in irgendeiner Parzelle liegt, markieren
                            if point.within(geom):
                                mask[i, j] = True
                                break  # Punkt gefunden, nächster Punkt
        
        # Return 1D arrays for x and y coordinates and the mask
        # This is the format expected by PyKrige's execute method with style='grid'
        return x, y, mask
# ANALYSIERT DAWS VARIOGRAM UND OPTIMIERT DIE PARAMETER RETURNS DICT MIT PARAMETERN
    def calculate_optimal_lags(self, x, y):
        """Calculate optimal number of lags based on data distribution.
        
        Args:
            x, y: Koordinaten der Messpunkte
            
        Returns:
            nlags: Optimale Anzahl der Lags
            max_dist: Maximale Distanz für die Variogrammanalyse
        """
        # Berechne alle paarweisen Distanzen
        distances = []
        n_points = len(x)
        
        for i in range(n_points):
            for j in range(i + 1, n_points):
                dist = np.sqrt((x[i] - x[j])**2 + (y[i] - y[j])**2)
                distances.append(dist)
        
        distances = np.array(distances)
        
        # Berechne Statistiken
        max_dist = np.percentile(distances, 95)  # 95. Perzentil statt Maximum
        n_pairs = len(distances)
        
        # Empirische Regeln für die Anzahl der Lags:
        # 1. Quadratwurzel-Regel (oft verwendet in der Histogramm-Analyse)
        n_bins_sqrt = int(np.sqrt(n_pairs))
        
        # 2. Rice-Regel (Alternative zu Sturges, besser für nicht-normale Verteilungen)
        n_bins_rice = int(np.ceil(2 * n_pairs**(1/3)))
        
        # 3. Mindestens 30 Paare pro Lag für statistische Stabilität
        min_pairs_per_lag = 30
        max_lags = n_pairs // min_pairs_per_lag
        
        # Wähle die kleinste Anzahl von Lags, die alle Kriterien erfüllt
        nlags = min(n_bins_sqrt, n_bins_rice, max_lags)
        
        # Stelle sicher, dass wir mindestens 3 Lags haben
        nlags = max(3, nlags)
        
        # Logging für Debugging
        QgsMessageLog.logMessage(
            f"Variogram Stats:\n"
            f"Pairs: {n_pairs}\n"
            f"Sqrt Bins: {n_bins_sqrt}, Rice Bins: {n_bins_rice}\n"
            f"Max Lags (30 pairs): {max_lags}\n"
            f"Selected Lags: {nlags}\n"
            f"Max Distance: {max_dist:.1f}",
            "Interpolation", Qgis.Info
        )
        
        return nlags, max_dist
    
    def analyze_variogram(self, x, y, z, params):
        """Analyze variogram and generate visualization.
        
        Args:
            x, y: Koordinaten der Messpunkte
            z: Messwerte
            params: Dictionary mit Variogramm-Parametern
                - variogram_model: Typ des Variogramm-Modells
                - nugget: Initialer Nugget-Effekt (optional)
                - range: Initiale Range (optional)
                - sill: Initialer Sill (optional)
        
        Returns:
            Dictionary mit:
                - metrics: Anpassungsgüte (RMSE, R², AIC)
                - parameters: Optimierte Parameter (nugget, range, sill)
                - experimental: Experimentelles Variogramm
                - model: Theoretisches Variogramm
                - plot_path: Pfad zur Variogramm-Visualisierung
        """
        try:
            # Validiere Eingabedaten
            if len(x) < 30:
                raise ValueError("Zu wenige Datenpunkte für eine stabile Variogramm-Analyse (min. 30 benötigt)")
            
            # Konvertiere zu numpy arrays
            x = np.asarray(x, dtype=np.float64)
            y = np.asarray(y, dtype=np.float64)
            z = np.asarray(z, dtype=np.float64)
            
            # Prüfe auf gültiges Variogramm-Modell
            model_type = params.get('variogram_model', 'spherical').lower()
            if model_type not in VARIOGRAM_MODELS:
                raise ValueError(f"Ungültiges Variogramm-Modell: {model_type}")
            
            # Verwende Anzahl der Lags aus UI oder berechne sie
            if 'nlags' in params:
                nlags = params['nlags']
                _, max_dist = self.calculate_optimal_lags(x, y)  # Nur für max_dist
            else:
                nlags, max_dist = self.calculate_optimal_lags(x, y)
            
            # Berechne experimentelles Variogramm
            # Log nlags parameter
            QgsMessageLog.logMessage(
                f"Using {nlags} lags for variogram analysis",
                "Interpolation",
                Qgis.Info
            )
            
            ok = OrdinaryKriging(
                x, y, z,
                variogram_model=model_type,
                nlags=nlags,
                enable_plotting=False,
                coordinates_type='euclidean'
            )
            
            # Setze maximale Distanz für das Variogramm
            ok.variogram_model_parameters = [
                params.get('nugget', 0),
                params.get('sill', np.var(z)),
                min(params.get('range', max_dist), max_dist)
            ]
            
            # Hole experimentelle Variogramm-Daten
            lags = ok.lags
            experimental = ok.semivariance
            
            # Initiale Schätzung der Parameter
            initial_guess = [
                params.get('nugget', 0),  # Nugget sollte nicht negativ sein
                params.get('range', np.median(lags)),  # Range etwa in der Mitte der Distanzen
                params.get('sill', np.max(experimental))  # Sill etwa beim Maximum der Semivarianz
            ]
            
            # Optimiere Parameter
            opt_params, metrics = optimize_variogram_parameters(
                lags, experimental, model_type, initial_guess
            )
            
            # Extrahiere optimierte Parameter
            nugget, range_, sill = opt_params
            
            # Berechne theoretisches Variogramm
            model_func = VARIOGRAM_MODELS[model_type]
            model_values = model_func(lags, nugget, range_, sill)
            
            # Berechne zusätzliche Metriken
            n_params = 3  # Nugget, Range, Sill
            n_points = len(lags)
            mse = metrics['rmse'] ** 2  # MSE aus RMSE berechnen
            aic = n_points * np.log(mse) + 2 * n_params  # Akaike Information Criterion
            metrics['aic'] = aic
            metrics['mse'] = mse  # MSE zu Metriken hinzufügen
            
            # Erstelle Plot
            plotter = VariogramPlotter()
            save_path = os.path.join(self.plugin_dir, 'variogram.png')
            plotter.plot_variogram(
                lags, experimental,
                model_type,
                nugget, range_, sill,
                title=f'Variogramm-Analyse\nRMSE: {metrics["rmse"]:.3f}, R²: {metrics["r2"]:.3f}, AIC: {aic:.1f}',
                save_path=save_path,
                show=False
            )
            plotter.close()
            
            # Logging der Ergebnisse
            QgsMessageLog.logMessage(
                f"Variogram Analysis Results:\n"
                f"Model: {model_type}\n"
                f"Parameters - Nugget: {nugget:.3f}, Range: {range_:.3f}, Sill: {sill:.3f}\n"
                f"Metrics - RMSE: {metrics['rmse']:.3f}, R²: {metrics['r2']:.3f}, AIC: {aic:.1f}",
                "Interpolation", Qgis.Info
            )
            
            return {
                'metrics': metrics,
                'parameters': {
                    'nugget': nugget,
                    'range': range_,
                    'sill': sill,
                    'model_type': model_type
                },
                'experimental': {
                    'lags': lags.tolist(),
                    'semivariance': experimental.tolist()
                },
                'model': {
                    'lags': lags.tolist(),
                    'semivariance': model_values.tolist()
                },
                'plot_path': save_path
            }
            
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Variogram analysis failed: {str(e)}",
                "Interpolation",
                Qgis.Critical
            )
            import traceback
            QgsMessageLog.logMessage(
                f"Traceback: {traceback.format_exc()}",
                "Interpolation",
                Qgis.Critical
            )
            return None
# DIE TATSÄCHLICHE INTERPOLATION MIT POINT LAYER FUNKTION IMPLEMENTIERT RETURNS Z-VALUE FOR GRID OR ADDS COLUMN TO THE DATA
    def interpolate_ordinary_kriging(self, x, y, z, grid_x, grid_y, params):
        """Führt die Ordinary Kriging Interpolation durch.
        
        Der Prozess läuft in mehreren Schritten ab:
        1. Variogramm-Analyse:
           - Berechnung und Modellierung des experimentellen Variogramms
           - Optimierung der Variogramm-Parameter
           - Validierung des Modells (RMSE, R²)
        2. Kriging-Interpolation:
           - Verwendung der optimierten Variogramm-Parameter
           - Berechnung der Kriging-Gewichte
           - Interpolation auf dem spezifizierten Grid
        
        Args:
            x (np.array): X-Koordinaten der Messpunkte
            y (np.array): Y-Koordinaten der Messpunkte
            z (np.array): Messwerte an den Punkten
            grid_x (np.array): X-Koordinaten des Interpolationsgrids
            grid_y (np.array): Y-Koordinaten des Interpolationsgrids
            params (dict): Parameter für die Interpolation:
                          - nlags (int): Anzahl der Lag-Klassen
                          - variogram_model (str): Typ des Variogramm-Modells
                          - sill (float, optional): Startwert für Sill
                          - range (float, optional): Startwert für Range
                          - nugget (float, optional): Startwert für Nugget
            
        Returns:
            dict: Interpolationsergebnisse mit:
                 - 'values': Interpolierte Werte auf dem Grid
                 - 'variance': Kriging-Varianz auf dem Grid
                 - 'variogram_info': Details zur Variogramm-Analyse
            oder None bei Fehler
            
        Raises:
            ValueError: Bei fehlgeschlagener Variogramm-Analyse
            
        Notes:
            - Loggt detaillierte Informationen zur Variogramm-Analyse
            - Speichert Variogramm-Parameter für spätere Verwendung
            - Verwendet GSTools für die eigentliche Interpolation
        """
        try:
            # First analyze variogram
            variogram_results = self.analyze_variogram(x, y, z, params)
            if not variogram_results:
                raise ValueError("Variogram analysis failed")
                
            if variogram_results:
                QgsMessageLog.logMessage(
                    f"Variogram Analysis Results:\nRMSE: {variogram_results['metrics']['rmse']:.3f}\nR²: {variogram_results['metrics']['r2']:.3f}",
                    "Interpolation",
                    Qgis.Info
                )
            
            # Store variogram results in params for later use
            params['variogram_info'] = variogram_results
            
            # Get optimized variogram parameters
            variogram_params = {
                'sill': variogram_results['parameters']['sill'],
                'range': variogram_results['parameters']['range'],
                'nugget': variogram_results['parameters']['nugget']
            }
            
            # Get nlags parameter
            nlags = params.get('nlags', 10)
            
            # Log nlags parameter
            QgsMessageLog.logMessage(
                f"Using {nlags} lags for kriging interpolation",
                "Interpolation",
                Qgis.Info
            )
            
            # Initialize kriging model
            ok = OrdinaryKriging(
                x, y, z,
                variogram_model=params['variogram_model'].lower(),
                variogram_parameters=variogram_params,
                nlags=nlags,
                enable_plotting=False,
                coordinates_type='euclidean'
            )
            
            # Perform grid interpolation
            z_pred, z_std = ok.execute('grid', grid_x, grid_y)
            return z_pred.data
                
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Interpolation failed: {str(e)}",
                "Interpolation",
                Qgis.Critical
            )
            import traceback
            QgsMessageLog.logMessage(
                f"Traceback: {traceback.format_exc()}",
                "Interpolation",
                Qgis.Critical
            )
            return None
# ERSTELLT EIN RASTERLAYER WELCHES AUS DEN VECTORDATEN EIN RASTER MACHT 
    def create_raster_layer(self, data, extent, cell_size, output_path, crs, mask=None):
        """Create and save interpolated raster layer."""
        try:
            # Log input dimensions
            QgsMessageLog.logMessage(
                f"Data shape: {data.shape}, Mask shape: {mask.shape if mask is not None else 'None'}",
                "Interpolation", Qgis.Info
            )
            
            # Apply mask if provided
            if mask is not None:
                data = np.where(mask, data, np.nan)
            
            # Use the dimensions from the interpolated data
            height, width = data.shape
            
            # Log dimensions
            QgsMessageLog.logMessage(
                f"Using dimensions from data - Width: {width}, Height: {height}",
                "Interpolation", Qgis.Info
            )
            
            # Flip the data array to match GIS coordinate system (origin at top-left)
            # PyKrige returns data with shape (ny, nx) with origin at bottom-left
            data = np.flipud(data)
            
            # Create raster layer
            driver = gdal.GetDriverByName('GTiff')
            dataset = driver.Create(
                output_path,
                width,
                height,
                1,
                gdal.GDT_Float32
            )
            
            # Calculate grid extent as in create_output_grid
            x_min = np.floor(extent.xMinimum() / cell_size) * cell_size
            x_max = np.ceil(extent.xMaximum() / cell_size) * cell_size
            y_min = np.floor(extent.yMinimum() / cell_size) * cell_size
            y_max = np.ceil(extent.yMaximum() / cell_size) * cell_size
            
            # Use the exact cell size
            x_res = cell_size
            y_res = cell_size
            
            # Log georeference information
            QgsMessageLog.logMessage(
                f"Raster Info - Extent: ({x_min}, {y_min}) to ({x_max}, {y_max}), Cell Size: {cell_size}, Adjusted Origin",
                "Interpolation", Qgis.Info
            )
            # Set georeference with offset
            #x_min = extent.xMinimum() - (cell_size * 1.5)  # Verschiebung nach links
            #y_max = extent.yMaximum() + (cell_size * 1.0)  # Verschiebung nach oben
            # Set geotransform with cell centers
            dataset.SetGeoTransform((
                x_min,      # x_min (adjusted for cell center)
                x_res,      # pixel width
                0,          # rotation (0 if image is "north up")
                y_max,      # y_max (adjusted for cell center)
                0,          # rotation (0 if image is "north up")
                -y_res      # pixel height
            ))
            
            # Set projection
            dataset.SetProjection(crs.toWkt())
            
            # Write data
            band = dataset.GetRasterBand(1)
            band.WriteArray(data)
            band.SetNoDataValue(np.nan)
            
            # Close dataset
            dataset = None
            
            return True
            
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Failed to create raster layer: {str(e)}",
                "Interpolation",
                Qgis.Critical
            )
            raise
# CHECKT OB DAS PROJEKT GESPEICHERT IST
    def get_project_dir(self):
        """Get or create project directory for outputs."""
        project = QgsProject.instance()
        if not project.fileName():
            QMessageBox.warning(
                None,
                "Warnung",
                "Bitte speichern Sie zuerst das QGIS-Projekt."
            )
            return None
            
        # Create project directory if it doesn't exist
        project_dir = Path(project.fileName()).parent / "interpolation_outputs"
        project_dir.mkdir(exist_ok=True)
        
        return project_dir
# ERSTELLT ODER BENUTZT EINE LAYER GRUPPE       
    def get_layer_group(self):
        """Get or create layer group for plugin outputs."""
        root = QgsProject.instance().layerTreeRoot()
        group_name = "Interpolation Interpolationen"
        
        # Find existing group or create new one
        group = root.findGroup(group_name)
        if not group:
            group = root.addGroup(group_name)
            
        return group
# RETURNS DEN base_name         
    def generate_output_name(self, input_layer, field_name, method):
        """Generate output name based on input parameters."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        base_name = f"{method}_{input_layer.name()}_{field_name}_{timestamp}"
        return base_name
# RETURNS EIN METADATA DICT IN JSON IM ORDNER        
    def save_metadata(self, output_dir, base_name, params):
        """Save metadata about the interpolation."""
        metadata = {
            "input_layer": params["input_layer"].name(),
            "input_field": params["input_field"],
            "cell_size": params["cell_size"],
            "boundary_layer": params["boundary_layer"].name() if params.get("boundary_layer") else None,
            "timestamp": datetime.now().isoformat(),
            "kriging_parameters": {
                "variogram_model": params.get("variogram_model"),
                "nlags": params.get("nlags", None),
                "initial_parameters": {
                    "sill": params.get("sill"),
                    "range": params.get("range"),
                    "nugget": params.get("nugget")
                }
            }
        }
        
        # Füge Variogramm-Analyse-Ergebnisse hinzu, wenn vorhanden
        if 'variogram_info' in params:
            metadata['variogram_analysis'] = {
                'metrics': params['variogram_info']['metrics'],
                'parameters': params['variogram_info']['parameters'],
                'experimental': {
                    'lags': params['variogram_info']['experimental']['lags'][:10],  # Erste 10 Werte
                    'semivariance': params['variogram_info']['experimental']['semivariance'][:10]  # Erste 10 Werte
                }
            }
        
        metadata_path = output_dir / f"{base_name}_metadata.json"
        with open(metadata_path, "w") as f:
            json.dump(metadata, f, indent=4)
# ERSTELLT DIE OUTPUT PATH UND DAS DIR             
    def setup_output_paths(self, input_layer, field_name, method):
        """Setup output paths and directories."""
        project_dir = self.get_project_dir()
        if not project_dir:
            return None, None
            
        # Generate base name for outputs
        base_name = self.generate_output_name(input_layer, field_name, method)
        
        # Create method-specific subdirectory
        output_dir = project_dir / method
        output_dir.mkdir(exist_ok=True)
        
        # Generate output path
        output_path = output_dir / f"{base_name}.tif"
        
        return str(output_path), output_dir
# HIER WERDEN DIE GANZEN FUNTKIONEN GECALLED UND DER PROGRESS GEHANDELT 
    def run(self):
        """Run method that performs all the real work"""
        
        # Check if required libraries are available
        if not INTERPOLATION_LIBS_AVAILABLE:
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Missing Dependencies",
                "Required libraries are not available. Please install the missing dependencies."
            )
            return

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            from .interpolation_dialog import InterpolationDialog
            self.dlg = InterpolationDialog(self.iface)
            self.dlg.plugin = self  # Store reference to plugin instance
            
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        
        # See if OK was pressed
        if result:
            # Create a dialog with busy indicator
            progress = QProgressDialog(self.tr("Interpolation läuft..."), self.tr("Abbrechen"), 0, 0, self.iface.mainWindow())
            progress.setWindowTitle("Interpolation")
            progress.setWindowModality(Qt.WindowModal)
            progress.setMinimumDuration(0)
            progress.setAutoClose(True)
            progress.setAutoReset(True)
            progress.setMinimum(0)
            progress.setMaximum(0)  # Indeterminate mode
            
            try:
                # Show the progress dialog
                progress.show()
                
                # Get parameters from dialog
                params = self.dlg.get_parameters()
                
                # Setup output paths
                output_path, output_dir = self.setup_output_paths(
                    params['input_layer'],
                    params['input_field'],
                    params['method']
                )
                if not output_path:
                    progress.close()
                    return
                    
                params['output_path'] = output_path
                
                # Process events to keep UI responsive
                from qgis.PyQt.QtCore import QCoreApplication
                QCoreApplication.processEvents()
                
                # Check for cancellation
                if progress.wasCanceled():
                    raise Exception("Interpolation wurde vom Benutzer abgebrochen")
                
                # Prepare data
                x, y, z = self.prepare_data(
                    params['input_layer'],
                    params['input_field'],
                    params.get('boundary_layer')
                )
                
                if x is None or y is None or z is None:
                    raise ValueError("Keine gültigen Daten für die Interpolation gefunden")
                
                # Get CRS from input layer
                target_crs = params['input_layer'].crs()
                
                QCoreApplication.processEvents()
                if progress.wasCanceled():
                    raise Exception("Interpolation wurde vom Benutzer abgebrochen")
                
                # Create output grid
                grid_x, grid_y, mask = self.create_output_grid(
                    params['input_layer'].extent(),
                    params['cell_size'],
                    params.get('boundary_layer')
                )
                
                QCoreApplication.processEvents()
                if progress.wasCanceled():
                    raise Exception("Interpolation wurde vom Benutzer abgebrochen")
                
                # Perform interpolation
                interpolated_data = self.interpolate_ordinary_kriging(
                    x, y, z, grid_x, grid_y, params
                )
                
                QCoreApplication.processEvents()
                if progress.wasCanceled():
                    raise Exception("Interpolation wurde vom Benutzer abgebrochen")
                
                # Create and save raster layer
                # Bestimme die Extent basierend auf Boundary oder Input Layer
                if params.get('boundary_layer'):
                    extent = params['boundary_layer'].extent()
                    QgsMessageLog.logMessage("Using boundary extent for raster", "Interpolation", Qgis.Info)
                else:
                    extent = params['input_layer'].extent()
                    QgsMessageLog.logMessage("Using input layer extent for raster", "Interpolation", Qgis.Info)
                
                self.create_raster_layer(
                    interpolated_data,
                    extent,
                    params['cell_size'],
                    output_path,
                    target_crs,
                    mask
                )
                
                # Save metadata
                self.save_metadata(output_dir, Path(output_path).stem, params)
                
                # Add layer to QGIS
                layer_name = Path(output_path).stem
                layer = QgsRasterLayer(output_path, layer_name)
                
                if layer.isValid():
                    # Add to layer group
                    group = self.get_layer_group()
                    QgsProject.instance().addMapLayer(layer, False)
                    group.addLayer(layer)
                    
                    # Get variogram info from params
                    variogram_info = params.get('variogram_info', {})
                    if variogram_info:
                        metrics = variogram_info.get('metrics', {})
                        parameters = variogram_info.get('parameters', {})
                        success_msg = (
                            f"Interpolation erfolgreich abgeschlossen: {layer_name}\n"
                            f"Variogramm Modell: {params['variogram_model']}\n"
                            f"RMSE: {metrics.get('rmse', 'N/A'):.3f}\n"
                            f"R²: {metrics.get('r2', 'N/A'):.3f}\n"
                            f"Range: {parameters.get('range', 'N/A'):.2f}\n"
                            f"Sill: {parameters.get('sill', 'N/A'):.2f}\n"
                            f"Nugget: {parameters.get('nugget', 'N/A'):.2f}"
                        )
                    else:
                        success_msg = f"Interpolation erfolgreich abgeschlossen: {layer_name}"
                    
                    self.iface.messageBar().pushSuccess(
                        "Interpolation",
                        success_msg
                    )
                else:
                    progress.close()
                    raise Exception("Failed to load output layer")
                    
                # Close the progress dialog
                progress.close()
                    
            except Exception as e:
                # Close progress dialog if it exists
                if 'progress' in locals():
                    progress.close()
                    
                self.iface.messageBar().pushCritical(
                    "Interpolation",
                    f"Fehler bei der Interpolation: {str(e)}"
                )
